import assert from "node:assert/strict";

import { CompilerContextSnapshot } from "../../../../../packages/ttsc/src/internal/CompilerContextSnapshot";
import type { ITtscCompilerContext } from "../../../../../packages/ttsc/src/structures/ITtscCompilerContext";
import type { ITtscProjectPluginConfig } from "../../../../../packages/ttsc/src/structures/ITtscProjectPluginConfig";

/**
 * Distinguishes captured plugin JSON from host selection and worker pairing.
 *
 * Custom conversion supplies different wire selectors. Original input and parsed
 * payload mutations must not replace the captured bytes; owned selectors remain
 * mutable and are not claimed to be frozen. Worker transfer is modeled with
 * selector data and the actual serialized channel, without starting a worker.
 *
 * @evidence contracts/testing.md#behavioral-verification Calls the actual clone, serializePlugins and restorePlugins exports, observes raw selectors, JSON conversion counts, isolated parsed payloads and inconsistent-transfer errors.
 * @evidence contracts/testing.md#independent-expectations Literal host and wire selectors deliberately disagree; the captured nested value is 7 despite subsequent mutations to 99 and 101. Exact channel strings and refusal text follow the snapshot transfer contract rather than being generated by another snapshot operation.
 * @evidence contracts/testing.md#distinguishing-cases Custom JSON and undefined JSON entries preserve index pairing; captured cloning, restoration and absent-channel cloning retain conversion count one. False plugins, empty arrays, mismatched lengths and a supplied channel for false plugins distinguish supported omission from malformed transfer.
 * @evidence contracts/testing.md#execution-ownership This named API unit calls the owning source methods in process with authored objects. It starts no worker, compiler or native child and observes no filesystem; actual worker transport is outside its assertions.
 */
export function test_compilercontextsnapshot_preserves_captured_payload_and_selectors(): void {
  let conversions = 0;
  let undefinedConversions = 0;
  const nested = { value: 7 };
  const entry: ITtscProjectPluginConfig = {
    enabled: true,
    transform: "host-plugin",
    configFile: "host.json",
    toJSON: () => {
      ++conversions;
      return {
        enabled: false,
        transform: "wire-plugin",
        configFile: "wire.json",
        nested,
      };
    },
  };
  const absent: ITtscProjectPluginConfig = {
    transform: "absent-plugin",
    toJSON: () => {
      ++undefinedConversions;
      return undefined;
    },
  };
  const context: ITtscCompilerContext = {
    cwd: "native-anchor",
    env: { PRESENT: "original", ABSENT: undefined },
    plugins: [entry, absent],
  };
  const captured = CompilerContextSnapshot.clone(context);
  assert.equal(conversions, 1);
  assert.equal(undefinedConversions, 1);
  entry.enabled = false;
  entry.transform = "changed-plugin";
  entry.configFile = "changed.json";
  nested.value = 99;
  context.env!.PRESENT = "changed";
  const wire = '{"enabled":false,"transform":"wire-plugin","configFile":"wire.json","nested":{"value":7}}';
  const channel = CompilerContextSnapshot.serializePlugins(captured);
  assert.deepEqual(channel, [wire, undefined]);
  assert.ok(captured.plugins !== undefined && captured.plugins !== false);
  const adapter = captured.plugins[0]!;
  assert.deepEqual(
    [adapter.enabled, adapter.transform, adapter.configFile],
    [true, "host-plugin", "host.json"],
  );
  assert.deepEqual(captured.env, { PRESENT: "original", ABSENT: undefined });
  assert.equal(Object.hasOwn(captured.env!, "ABSENT"), true);
  const convert = adapter.toJSON;
  assert.equal(typeof convert, "function");
  assert.ok(typeof convert === "function");
  const parsed = convert();
  assert.deepEqual(parsed, {
    enabled: false,
    transform: "wire-plugin",
    configFile: "wire.json",
    nested: { value: 7 },
  });
  parsed.nested.value = 101;
  assert.deepEqual(convert().nested, { value: 7 });
  assert.equal(JSON.stringify(adapter), wire);
  assert.equal(JSON.stringify(captured.plugins[1]), undefined);
  const workerContext: ITtscCompilerContext = {
    cwd: captured.cwd,
    env: captured.env,
    plugins: [
      { enabled: true, transform: "host-plugin", configFile: "host.json" },
      { transform: "absent-plugin" },
    ],
  };
  for (const copy of [
    CompilerContextSnapshot.clone(captured),
    CompilerContextSnapshot.restorePlugins(workerContext, channel),
    CompilerContextSnapshot.restorePlugins(captured, undefined),
  ]) {
    assert.ok(copy.plugins !== undefined && copy.plugins !== false);
    assert.deepEqual(
      [copy.plugins[0]!.enabled, copy.plugins[0]!.transform, copy.plugins[0]!.configFile],
      [true, "host-plugin", "host.json"],
    );
    assert.deepEqual(CompilerContextSnapshot.serializePlugins(copy), [wire, undefined]);
    assert.equal(JSON.stringify(copy.plugins[0]), wire);
    assert.equal(JSON.stringify(copy.plugins[1]), undefined);
    assert.notEqual(copy.env, captured.env);
    assert.deepEqual(copy.env, { PRESENT: "original", ABSENT: undefined });
  }
  assert.equal(conversions, 1);
  assert.equal(undefinedConversions, 1);
  assert.equal(CompilerContextSnapshot.clone({ plugins: false }).plugins, false);
  assert.equal(CompilerContextSnapshot.serializePlugins({ plugins: false }), undefined);
  assert.equal(CompilerContextSnapshot.restorePlugins({ plugins: false }, undefined).plugins, false);
  assert.deepEqual(CompilerContextSnapshot.serializePlugins({ plugins: [] }), []);
  assert.deepEqual(CompilerContextSnapshot.restorePlugins({ plugins: [] }, []).plugins, []);
  for (const malformed of [
    () => CompilerContextSnapshot.restorePlugins(workerContext, [wire]),
    () => CompilerContextSnapshot.restorePlugins({ plugins: false }, []),
  ])
    assert.throws(malformed, {
      message: "ttsc: compiler plugin snapshot transfer is inconsistent",
    });
}
