import assert from "node:assert/strict";

import { parseNativeTransformOutput } from "../../../../../packages/ttsc/src/compiler/internal/parseNativeTransformOutput";

/**
 * Verifies native source records preserve names that also occur on
 * Object.prototype.
 *
 * Relative graph and source keys may name **proto**, constructor or toString.
 * Decoding must retain them as ordinary own data, including a proof refusal for
 * conflicting observations, so downstream enumeration and serialization retain
 * the producer's complete source population.
 *
 * 1. Decode three reserved names in source, dependency, map and graph records.
 * 2. Assert own membership, literal values and JSON serialization preservation.
 * 3. Contrast a valid predicate with a conflicting predicate under **proto**.
 *
 * @evidence contracts/testing.md#behavioral-verification Calls parseNativeTransformOutput on authored source and graph records, checks all nine returned keyed sections and verifies that conflicting __proto__ predicates produce an own conflicting-observation refusal instead of disappearing.
 * @evidence contracts/testing.md#independent-expectations The envelope contract treats nonempty relative names as source identities. Object.fromEntries constructs independent fixture records without invoking the legacy __proto__ setter; expected strings, lists, maps, hashes, nulls and failure reasons are authored protocol values, never generated by the decoder.
 * @evidence contracts/testing.md#distinguishing-cases __proto__ exercises the legacy setter name while constructor and toString are adjacent inherited-name controls. Empty graph leaves, valid file predicates and conflicting file/directory predicates distinguish retained membership from discarded proof; JSON round trips must preserve every own source key.
 * @evidence contracts/testing.md#execution-ownership The named API source-unit entry invokes the actual decoder in process with JSON strings and aggregates independent section failures. It reads no filesystem, builds no native artifact and starts no compiler or product host.
 */
export function test_ttsccompiler_transform_preserves_reserved_source_keys(): void {
  const keys = ["__proto__", "constructor", "toString"];
  const sourceMap = {
    version: 3,
    names: [],
    sources: ["original.ts"],
    sourcesContent: ["export const value = 1;"],
    mappings: "AAAA",
  };
  const sources = Object.fromEntries(
    keys.map((key) => [key, "export const value = 1;"]),
  );
  const lists = Object.fromEntries(keys.map((key) => [key, ["input.ts"]]));
  const leaves = Object.fromEntries(keys.map((key) => [key, []]));
  const maps = Object.fromEntries(keys.map((key) => [key, sourceMap]));
  const hashes = Object.fromEntries(keys.map((key) => [key, "a".repeat(64)]));
  const realpaths = Object.fromEntries(keys.map((key) => [key, null]));
  const observations = Object.fromEntries(
    keys.map((key) => [key, { fileExists: true }]),
  );
  const reasons = Object.fromEntries(
    keys.map((key) => [key, "content-unavailable"]),
  );
  const result = parseNativeTransformOutput(
    JSON.stringify({
      typescript: sources,
      dependencies: lists,
      sourceMaps: maps,
      graph: {
        edges: leaves,
        candidates: lists,
        inputHashes: hashes,
        inputRealpaths: realpaths,
        inputObservations: observations,
        inputProofFailures: reasons,
      },
    }),
    "",
  );
  const failures: Error[] = [];
  const check = (name: string, operation: () => void): void => {
    try {
      operation();
    } catch (error) {
      failures.push(new Error(name, { cause: error }));
    }
  };
  for (const [name, actual, expected] of [
    ["typescript", result.typescript, sources],
    ["dependencies", result.dependencies, lists],
    ["sourceMaps", result.sourceMaps, maps],
    ["graph.edges", result.graph?.edges, leaves],
    ["graph.candidates", result.graph?.candidates, lists],
    ["graph.inputHashes", result.graph?.inputHashes, hashes],
    ["graph.inputRealpaths", result.graph?.inputRealpaths, realpaths],
    ["graph.inputObservations", result.graph?.inputObservations, observations],
    ["graph.inputProofFailures", result.graph?.inputProofFailures, reasons],
  ] as const) {
    for (const key of keys)
      check(`${name}: own ${key}`, () => {
        assert.equal(
          Object.prototype.hasOwnProperty.call(actual, key),
          true,
          `${name}: ${key} must be own data`,
        );
      });
    check(`${name}: literal values`, () => {
      assert.deepEqual(actual, expected, name);
    });
    check(`${name}: JSON preservation`, () => {
      assert.deepEqual(
        JSON.parse(JSON.stringify(actual)),
        expected,
        `${name}: serialized source identity`,
      );
    });
  }
  const conflicting = parseNativeTransformOutput(
    JSON.stringify({
      typescript: sources,
      graph: {
        edges: leaves,
        inputObservations: Object.fromEntries([
          ["__proto__", { fileExists: true, directoryExists: true }],
          ["constructor", { fileExists: true }],
        ]),
      },
    }),
    "",
  );
  check("conflicting observation preserves valid sibling", () => {
    assert.deepEqual(conflicting.graph?.inputObservations, {
      constructor: { fileExists: true },
    });
  });
  const expected = Object.fromEntries([
    ["__proto__", "conflicting-observation"],
  ]);
  check("conflicting observation retains its source identity", () => {
    assert.deepEqual(conflicting.graph?.inputProofFailures, expected);
  });
  check("conflicting observation serializes its source identity", () => {
    assert.deepEqual(
      JSON.parse(JSON.stringify(conflicting.graph?.inputProofFailures)),
      expected,
    );
  });
  if (failures.length)
    throw new AggregateError(
      failures,
      "Native source records lost reserved source identities",
    );
}
