// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package checker is the documented github.com/microsoft/typescript-go/shim/checker plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/checker, the
// bridge that reaches the compiler's internal packages.
package checker

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tscchecker "github.com/microsoft/TypeScript/tsc/shim/checker"
  tscprinter "github.com/microsoft/TypeScript/tsc/shim/printer"
  sync "sync"
)

type Checker = tscchecker.Checker

func Checker_combineTypeMappers(p0 *tscchecker.Checker, p1 *tscchecker.TypeMapper, p2 *tscchecker.TypeMapper) *tscchecker.TypeMapper {
  return tscchecker.Checker_combineTypeMappers(p0, p1, p2)
}

func Checker_getAliasSymbolForTypeNode(p0 *tscchecker.Checker, p1 *tscast.Node) *tscast.Symbol {
  return tscchecker.Checker_getAliasSymbolForTypeNode(p0, p1)
}

func Checker_getAliasedSymbol(p0 *tscchecker.Checker, p1 *tscast.Symbol) *tscast.Symbol {
  return tscchecker.Checker_getAliasedSymbol(p0, p1)
}

func Checker_getApparentProperties(p0 *tscchecker.Checker, p1 *tscchecker.Type) []*tscast.Symbol {
  return tscchecker.Checker_getApparentProperties(p0, p1)
}

func Checker_getBaseTypes(p0 *tscchecker.Checker, p1 *tscchecker.Type) []*tscchecker.Type {
  return tscchecker.Checker_getBaseTypes(p0, p1)
}

func Checker_getDeclarationOfAliasSymbol(p0 *tscchecker.Checker, p1 *tscast.Symbol) *tscast.Node {
  return tscchecker.Checker_getDeclarationOfAliasSymbol(p0, p1)
}

func Checker_getDeclaredTypeOfSymbol(p0 *tscchecker.Checker, p1 *tscast.Symbol) *tscchecker.Type {
  return tscchecker.Checker_getDeclaredTypeOfSymbol(p0, p1)
}

func Checker_getExportsOfModule(p0 *tscchecker.Checker, p1 *tscast.Symbol) []*tscast.Symbol {
  return tscchecker.Checker_getExportsOfModule(p0, p1)
}

func Checker_getIndexInfosOfType(p0 *tscchecker.Checker, p1 *tscchecker.Type) []*tscchecker.IndexInfo {
  return tscchecker.Checker_getIndexInfosOfType(p0, p1)
}

func Checker_getMinArgumentCount(p0 *tscchecker.Checker, p1 *tscchecker.Signature) int {
  return tscchecker.Checker_getMinArgumentCount(p0, p1)
}

func Checker_getPropertiesOfType(p0 *tscchecker.Checker, p1 *tscchecker.Type) []*tscast.Symbol {
  return tscchecker.Checker_getPropertiesOfType(p0, p1)
}

func Checker_getPropertyNameForKnownSymbolName(p0 *tscchecker.Checker, p1 string) string {
  return tscchecker.Checker_getPropertyNameForKnownSymbolName(p0, p1)
}

func Checker_getRegularTypeOfLiteralType(p0 *tscchecker.Checker, p1 *tscchecker.Type) *tscchecker.Type {
  return tscchecker.Checker_getRegularTypeOfLiteralType(p0, p1)
}

func Checker_getRestTypeOfSignature(p0 *tscchecker.Checker, p1 *tscchecker.Signature) *tscchecker.Type {
  return tscchecker.Checker_getRestTypeOfSignature(p0, p1)
}

func Checker_getReturnTypeOfSignature(p0 *tscchecker.Checker, p1 *tscchecker.Signature) *tscchecker.Type {
  return tscchecker.Checker_getReturnTypeOfSignature(p0, p1)
}

func Checker_getSignaturesOfType(p0 *tscchecker.Checker, p1 *tscchecker.Type, p2 tscchecker.SignatureKind) []*tscchecker.Signature {
  return tscchecker.Checker_getSignaturesOfType(p0, p1, p2)
}

func Checker_getSynchronousIterationYieldType(p0 *tscchecker.Checker, p1 *tscchecker.Type) *tscchecker.Type {
  return tscchecker.Checker_getSynchronousIterationYieldType(p0, p1)
}

func Checker_getTargetOfImportSpecifier(p0 *tscchecker.Checker, p1 *tscast.Node) *tscast.Symbol {
  return tscchecker.Checker_getTargetOfImportSpecifier(p0, p1)
}

func Checker_getTypeArguments(p0 *tscchecker.Checker, p1 *tscchecker.Type) []*tscchecker.Type {
  return tscchecker.Checker_getTypeArguments(p0, p1)
}

func Checker_getTypeOfPropertyOfType(p0 *tscchecker.Checker, p1 *tscchecker.Type, p2 string) *tscchecker.Type {
  return tscchecker.Checker_getTypeOfPropertyOfType(p0, p1, p2)
}

func Checker_getTypeOfSymbol(p0 *tscchecker.Checker, p1 *tscast.Symbol) *tscchecker.Type {
  return tscchecker.Checker_getTypeOfSymbol(p0, p1)
}

func Checker_getTypeOfSymbolAtLocation(p0 *tscchecker.Checker, p1 *tscast.Symbol, p2 *tscast.Node) *tscchecker.Type {
  return tscchecker.Checker_getTypeOfSymbolAtLocation(p0, p1, p2)
}

func Checker_instantiateType(p0 *tscchecker.Checker, p1 *tscchecker.Type, p2 *tscchecker.TypeMapper) *tscchecker.Type {
  return tscchecker.Checker_instantiateType(p0, p1, p2)
}

func Checker_isArrayType(p0 *tscchecker.Checker, p1 *tscchecker.Type) bool {
  return tscchecker.Checker_isArrayType(p0, p1)
}

func Checker_isPropertyAssignableTo(p0 *tscchecker.Checker, p1 *tscast.Symbol, p2 *tscast.Symbol) bool {
  return tscchecker.Checker_isPropertyAssignableTo(p0, p1, p2)
}

func Checker_isSymbolAccessibleAsValue(p0 *tscchecker.Checker, p1 *tscast.Symbol, p2 *tscast.Node) bool {
  return tscchecker.Checker_isSymbolAccessibleAsValue(p0, p1, p2)
}

func Checker_isValidClassMemberOverridePair(p0 *tscchecker.Checker, p1 *tscast.Symbol, p2 *tscast.Symbol) bool {
  return tscchecker.Checker_isValidClassMemberOverridePair(p0, p1, p2)
}

func Checker_newSimpleTypeMapper(p0 *tscchecker.Type, p1 *tscchecker.Type) *tscchecker.TypeMapper {
  return tscchecker.Checker_newSimpleTypeMapper(p0, p1)
}

func Checker_newTypeMapper(p0 []*tscchecker.Type, p1 []*tscchecker.Type) *tscchecker.TypeMapper {
  return tscchecker.Checker_newTypeMapper(p0, p1)
}

func Checker_resolveEntityName(p0 *tscchecker.Checker, p1 *tscast.Node, p2 tscast.SymbolFlags, p3 bool, p4 bool, p5 *tscast.Node) *tscast.Symbol {
  return tscchecker.Checker_resolveEntityName(p0, p1, p2, p3, p4, p5)
}

func Checker_symbolToValueString(p0 *tscchecker.Checker, p1 *tscast.Symbol, p2 *tscast.Node) string {
  return tscchecker.Checker_symbolToValueString(p0, p1, p2)
}

func Checker_typeToStringFullyQualified(p0 *tscchecker.Checker, p1 *tscchecker.Type, p2 *tscast.Node) string {
  return tscchecker.Checker_typeToStringFullyQualified(p0, p1, p2)
}

type ElementFlags = tscchecker.ElementFlags

const ElementFlagsFixed = tscchecker.ElementFlagsFixed

const ElementFlagsNonRequired = tscchecker.ElementFlagsNonRequired

const ElementFlagsNonRest = tscchecker.ElementFlagsNonRest

const ElementFlagsNone = tscchecker.ElementFlagsNone

const ElementFlagsOptional = tscchecker.ElementFlagsOptional

const ElementFlagsRequired = tscchecker.ElementFlagsRequired

const ElementFlagsRest = tscchecker.ElementFlagsRest

const ElementFlagsVariable = tscchecker.ElementFlagsVariable

const ElementFlagsVariadic = tscchecker.ElementFlagsVariadic

func GetPropertyNameFromType(p0 *tscchecker.Type) string {
  return tscchecker.GetPropertyNameFromType(p0)
}

func GetSetAccessorValueParameter(p0 *tscast.Node) *tscast.Node {
  return tscchecker.GetSetAccessorValueParameter(p0)
}

type IndexInfo = tscchecker.IndexInfo

func IsTupleType(p0 *tscchecker.Type) bool {
  return tscchecker.IsTupleType(p0)
}

func IsTypeUsableAsPropertyName(p0 *tscchecker.Type) bool {
  return tscchecker.IsTypeUsableAsPropertyName(p0)
}

const IterationTypeKindNext = tscchecker.IterationTypeKindNext

const IterationTypeKindReturn = tscchecker.IterationTypeKindReturn

const IterationTypeKindYield = tscchecker.IterationTypeKindYield

const IterationUseAllowsAsyncIterablesFlag = tscchecker.IterationUseAllowsAsyncIterablesFlag

const IterationUseAllowsStringInputFlag = tscchecker.IterationUseAllowsStringInputFlag

const IterationUseAllowsSyncIterablesFlag = tscchecker.IterationUseAllowsSyncIterablesFlag

const IterationUseAsyncGeneratorReturnType = tscchecker.IterationUseAsyncGeneratorReturnType

const IterationUseAsyncYieldStar = tscchecker.IterationUseAsyncYieldStar

const IterationUseCacheFlags = tscchecker.IterationUseCacheFlags

const IterationUseDestructuring = tscchecker.IterationUseDestructuring

const IterationUseDestructuringFlag = tscchecker.IterationUseDestructuringFlag

const IterationUseElement = tscchecker.IterationUseElement

const IterationUseForAwaitOf = tscchecker.IterationUseForAwaitOf

const IterationUseForOf = tscchecker.IterationUseForOf

const IterationUseForOfFlag = tscchecker.IterationUseForOfFlag

const IterationUseGeneratorReturnType = tscchecker.IterationUseGeneratorReturnType

const IterationUsePossiblyOutOfBounds = tscchecker.IterationUsePossiblyOutOfBounds

const IterationUseSpread = tscchecker.IterationUseSpread

const IterationUseSpreadFlag = tscchecker.IterationUseSpreadFlag

const IterationUseYieldStar = tscchecker.IterationUseYieldStar

const IterationUseYieldStarFlag = tscchecker.IterationUseYieldStarFlag

func NewChecker(p0 tscchecker.Program, p1 *tscchecker.Tracer) (*tscchecker.Checker, *sync.Mutex) {
  return tscchecker.NewChecker(p0, p1)
}

type NodeBuilderImpl = tscchecker.NodeBuilderImpl

type ObjectFlags = tscchecker.ObjectFlags

const ObjectFlagsAnonymous = tscchecker.ObjectFlagsAnonymous

const ObjectFlagsArrayLiteral = tscchecker.ObjectFlagsArrayLiteral

const ObjectFlagsClass = tscchecker.ObjectFlagsClass

const ObjectFlagsClassOrInterface = tscchecker.ObjectFlagsClassOrInterface

const ObjectFlagsContainsIntersections = tscchecker.ObjectFlagsContainsIntersections

const ObjectFlagsContainsObjectOrArrayLiteral = tscchecker.ObjectFlagsContainsObjectOrArrayLiteral

const ObjectFlagsContainsSpread = tscchecker.ObjectFlagsContainsSpread

const ObjectFlagsContainsWideningType = tscchecker.ObjectFlagsContainsWideningType

const ObjectFlagsCouldContainTypeVariables = tscchecker.ObjectFlagsCouldContainTypeVariables

const ObjectFlagsCouldContainTypeVariablesComputed = tscchecker.ObjectFlagsCouldContainTypeVariablesComputed

const ObjectFlagsEvolvingArray = tscchecker.ObjectFlagsEvolvingArray

const ObjectFlagsFreshLiteral = tscchecker.ObjectFlagsFreshLiteral

const ObjectFlagsFromTypeNode = tscchecker.ObjectFlagsFromTypeNode

const ObjectFlagsIdenticalBaseTypeCalculated = tscchecker.ObjectFlagsIdenticalBaseTypeCalculated

const ObjectFlagsIdenticalBaseTypeExists = tscchecker.ObjectFlagsIdenticalBaseTypeExists

const ObjectFlagsInstantiated = tscchecker.ObjectFlagsInstantiated

const ObjectFlagsInstantiatedMapped = tscchecker.ObjectFlagsInstantiatedMapped

const ObjectFlagsInstantiationExpressionType = tscchecker.ObjectFlagsInstantiationExpressionType

const ObjectFlagsInterface = tscchecker.ObjectFlagsInterface

const ObjectFlagsIsClassInstanceClone = tscchecker.ObjectFlagsIsClassInstanceClone

const ObjectFlagsIsConstrainedTypeVariable = tscchecker.ObjectFlagsIsConstrainedTypeVariable

const ObjectFlagsIsGenericIndexType = tscchecker.ObjectFlagsIsGenericIndexType

const ObjectFlagsIsGenericObjectType = tscchecker.ObjectFlagsIsGenericObjectType

const ObjectFlagsIsGenericType = tscchecker.ObjectFlagsIsGenericType

const ObjectFlagsIsGenericTypeComputed = tscchecker.ObjectFlagsIsGenericTypeComputed

const ObjectFlagsIsNeverIntersection = tscchecker.ObjectFlagsIsNeverIntersection

const ObjectFlagsIsNeverIntersectionComputed = tscchecker.ObjectFlagsIsNeverIntersectionComputed

const ObjectFlagsIsUniformEnum = tscchecker.ObjectFlagsIsUniformEnum

const ObjectFlagsIsUniformEnumComputed = tscchecker.ObjectFlagsIsUniformEnumComputed

const ObjectFlagsIsUnknownLikeUnion = tscchecker.ObjectFlagsIsUnknownLikeUnion

const ObjectFlagsIsUnknownLikeUnionComputed = tscchecker.ObjectFlagsIsUnknownLikeUnionComputed

const ObjectFlagsJSLiteral = tscchecker.ObjectFlagsJSLiteral

const ObjectFlagsJsxAttributes = tscchecker.ObjectFlagsJsxAttributes

const ObjectFlagsMapped = tscchecker.ObjectFlagsMapped

const ObjectFlagsMembersResolved = tscchecker.ObjectFlagsMembersResolved

const ObjectFlagsNonInferrableType = tscchecker.ObjectFlagsNonInferrableType

const ObjectFlagsNone = tscchecker.ObjectFlagsNone

const ObjectFlagsObjectLiteral = tscchecker.ObjectFlagsObjectLiteral

const ObjectFlagsObjectLiteralPatternWithComputedProperties = tscchecker.ObjectFlagsObjectLiteralPatternWithComputedProperties

const ObjectFlagsObjectRestType = tscchecker.ObjectFlagsObjectRestType

const ObjectFlagsObjectTypeKindMask = tscchecker.ObjectFlagsObjectTypeKindMask

const ObjectFlagsPrimitiveUnion = tscchecker.ObjectFlagsPrimitiveUnion

const ObjectFlagsPropagatingFlags = tscchecker.ObjectFlagsPropagatingFlags

const ObjectFlagsReference = tscchecker.ObjectFlagsReference

const ObjectFlagsRequiresWidening = tscchecker.ObjectFlagsRequiresWidening

const ObjectFlagsReverseMapped = tscchecker.ObjectFlagsReverseMapped

const ObjectFlagsSingleSignatureType = tscchecker.ObjectFlagsSingleSignatureType

const ObjectFlagsTuple = tscchecker.ObjectFlagsTuple

type Program = tscchecker.Program

type Signature = tscchecker.Signature

type SignatureFlags = tscchecker.SignatureFlags

const SignatureFlagsAbstract = tscchecker.SignatureFlagsAbstract

const SignatureFlagsCallChainFlags = tscchecker.SignatureFlagsCallChainFlags

const SignatureFlagsConstruct = tscchecker.SignatureFlagsConstruct

const SignatureFlagsHasLiteralTypes = tscchecker.SignatureFlagsHasLiteralTypes

const SignatureFlagsHasRestParameter = tscchecker.SignatureFlagsHasRestParameter

const SignatureFlagsIsInnerCallChain = tscchecker.SignatureFlagsIsInnerCallChain

const SignatureFlagsIsNonInferrable = tscchecker.SignatureFlagsIsNonInferrable

const SignatureFlagsIsOuterCallChain = tscchecker.SignatureFlagsIsOuterCallChain

const SignatureFlagsIsSignatureCandidateForOverloadFailure = tscchecker.SignatureFlagsIsSignatureCandidateForOverloadFailure

const SignatureFlagsIsUntypedSignatureInJSFile = tscchecker.SignatureFlagsIsUntypedSignatureInJSFile

const SignatureFlagsNone = tscchecker.SignatureFlagsNone

const SignatureFlagsPropagatingFlags = tscchecker.SignatureFlagsPropagatingFlags

type SignatureKind = tscchecker.SignatureKind

const SignatureKindCall = tscchecker.SignatureKindCall

const SignatureKindConstruct = tscchecker.SignatureKindConstruct

func Signature_hasRestParameter(p0 *tscchecker.Signature) bool {
  return tscchecker.Signature_hasRestParameter(p0)
}

func Signature_parameterCount(p0 *tscchecker.Signature) int {
  return tscchecker.Signature_parameterCount(p0)
}

func Signature_parameters(p0 *tscchecker.Signature) []*tscast.Symbol {
  return tscchecker.Signature_parameters(p0)
}

type Tracer = tscchecker.Tracer

type Type = tscchecker.Type

type TypeAlias = tscchecker.TypeAlias

type TypeFlags = tscchecker.TypeFlags

const TypeFlagsAny = tscchecker.TypeFlagsAny

const TypeFlagsAnyOrUnknown = tscchecker.TypeFlagsAnyOrUnknown

const TypeFlagsBigInt = tscchecker.TypeFlagsBigInt

const TypeFlagsBigIntLike = tscchecker.TypeFlagsBigIntLike

const TypeFlagsBigIntLiteral = tscchecker.TypeFlagsBigIntLiteral

const TypeFlagsBoolean = tscchecker.TypeFlagsBoolean

const TypeFlagsBooleanLike = tscchecker.TypeFlagsBooleanLike

const TypeFlagsBooleanLiteral = tscchecker.TypeFlagsBooleanLiteral

const TypeFlagsConditional = tscchecker.TypeFlagsConditional

const TypeFlagsDefinitelyFalsy = tscchecker.TypeFlagsDefinitelyFalsy

const TypeFlagsDefinitelyNonNullable = tscchecker.TypeFlagsDefinitelyNonNullable

const TypeFlagsDisjointDomains = tscchecker.TypeFlagsDisjointDomains

const TypeFlagsESSymbol = tscchecker.TypeFlagsESSymbol

const TypeFlagsESSymbolLike = tscchecker.TypeFlagsESSymbolLike

const TypeFlagsEnum = tscchecker.TypeFlagsEnum

const TypeFlagsEnumLike = tscchecker.TypeFlagsEnumLike

const TypeFlagsEnumLiteral = tscchecker.TypeFlagsEnumLiteral

const TypeFlagsFreshable = tscchecker.TypeFlagsFreshable

const TypeFlagsIncludesConstrainedTypeVariable = tscchecker.TypeFlagsIncludesConstrainedTypeVariable

const TypeFlagsIncludesEmptyObject = tscchecker.TypeFlagsIncludesEmptyObject

const TypeFlagsIncludesError = tscchecker.TypeFlagsIncludesError

const TypeFlagsIncludesInstantiable = tscchecker.TypeFlagsIncludesInstantiable

const TypeFlagsIncludesMask = tscchecker.TypeFlagsIncludesMask

const TypeFlagsIncludesMissingType = tscchecker.TypeFlagsIncludesMissingType

const TypeFlagsIncludesNonWideningType = tscchecker.TypeFlagsIncludesNonWideningType

const TypeFlagsIncludesWildcard = tscchecker.TypeFlagsIncludesWildcard

const TypeFlagsIndex = tscchecker.TypeFlagsIndex

const TypeFlagsIndexedAccess = tscchecker.TypeFlagsIndexedAccess

const TypeFlagsInstantiable = tscchecker.TypeFlagsInstantiable

const TypeFlagsInstantiableNonPrimitive = tscchecker.TypeFlagsInstantiableNonPrimitive

const TypeFlagsInstantiablePrimitive = tscchecker.TypeFlagsInstantiablePrimitive

const TypeFlagsIntersection = tscchecker.TypeFlagsIntersection

const TypeFlagsIntrinsic = tscchecker.TypeFlagsIntrinsic

const TypeFlagsLiteral = tscchecker.TypeFlagsLiteral

const TypeFlagsNarrowable = tscchecker.TypeFlagsNarrowable

const TypeFlagsNever = tscchecker.TypeFlagsNever

const TypeFlagsNonPrimitive = tscchecker.TypeFlagsNonPrimitive

const TypeFlagsNone = tscchecker.TypeFlagsNone

const TypeFlagsNotPrimitiveUnion = tscchecker.TypeFlagsNotPrimitiveUnion

const TypeFlagsNull = tscchecker.TypeFlagsNull

const TypeFlagsNullable = tscchecker.TypeFlagsNullable

const TypeFlagsNumber = tscchecker.TypeFlagsNumber

const TypeFlagsNumberLike = tscchecker.TypeFlagsNumberLike

const TypeFlagsNumberLiteral = tscchecker.TypeFlagsNumberLiteral

const TypeFlagsObject = tscchecker.TypeFlagsObject

const TypeFlagsObjectFlagsType = tscchecker.TypeFlagsObjectFlagsType

const TypeFlagsPossiblyFalsy = tscchecker.TypeFlagsPossiblyFalsy

const TypeFlagsPrimitive = tscchecker.TypeFlagsPrimitive

const TypeFlagsReserved1 = tscchecker.TypeFlagsReserved1

const TypeFlagsReserved2 = tscchecker.TypeFlagsReserved2

const TypeFlagsReserved3 = tscchecker.TypeFlagsReserved3

const TypeFlagsSimplifiable = tscchecker.TypeFlagsSimplifiable

const TypeFlagsSingleton = tscchecker.TypeFlagsSingleton

const TypeFlagsString = tscchecker.TypeFlagsString

const TypeFlagsStringLike = tscchecker.TypeFlagsStringLike

const TypeFlagsStringLiteral = tscchecker.TypeFlagsStringLiteral

const TypeFlagsStringMapping = tscchecker.TypeFlagsStringMapping

const TypeFlagsStringOrNumberLiteral = tscchecker.TypeFlagsStringOrNumberLiteral

const TypeFlagsStringOrNumberLiteralOrUnique = tscchecker.TypeFlagsStringOrNumberLiteralOrUnique

const TypeFlagsStructuredOrInstantiable = tscchecker.TypeFlagsStructuredOrInstantiable

const TypeFlagsStructuredType = tscchecker.TypeFlagsStructuredType

const TypeFlagsSubstitution = tscchecker.TypeFlagsSubstitution

const TypeFlagsTemplateLiteral = tscchecker.TypeFlagsTemplateLiteral

const TypeFlagsTypeParameter = tscchecker.TypeFlagsTypeParameter

const TypeFlagsTypeVariable = tscchecker.TypeFlagsTypeVariable

const TypeFlagsUndefined = tscchecker.TypeFlagsUndefined

const TypeFlagsUnion = tscchecker.TypeFlagsUnion

const TypeFlagsUnionOrIntersection = tscchecker.TypeFlagsUnionOrIntersection

const TypeFlagsUniqueESSymbol = tscchecker.TypeFlagsUniqueESSymbol

const TypeFlagsUnit = tscchecker.TypeFlagsUnit

const TypeFlagsUnknown = tscchecker.TypeFlagsUnknown

const TypeFlagsVoid = tscchecker.TypeFlagsVoid

const TypeFlagsVoidLike = tscchecker.TypeFlagsVoidLike

type TypeMapper = tscchecker.TypeMapper

type TypeMapperKind = tscchecker.TypeMapperKind

const TypeMapperKindArray = tscchecker.TypeMapperKindArray

const TypeMapperKindMerged = tscchecker.TypeMapperKindMerged

const TypeMapperKindSimple = tscchecker.TypeMapperKindSimple

const TypeMapperKindUnknown = tscchecker.TypeMapperKindUnknown

func Type_getTypeNameSymbol(p0 *tscchecker.Type) *tscast.Symbol {
  return tscchecker.Type_getTypeNameSymbol(p0)
}

func ValueToString(p0 any) string {
  return tscchecker.ValueToString(p0)
}

func WithNodeBuilderContext(p0 *tscchecker.Checker, p1 *tscprinter.EmitContext, p2 *tscast.Node, p3 func(*tscchecker.NodeBuilderImpl) (*tscast.Node, error)) (*tscast.Node, error) {
  return tscchecker.WithNodeBuilderContext(p0, p1, p2, p3)
}
