// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package scanner is the documented github.com/microsoft/typescript-go/shim/scanner plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/scanner, the
// bridge that reaches the compiler's internal packages.
package scanner

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tsccore "github.com/microsoft/TypeScript/tsc/shim/core"
  tscscanner "github.com/microsoft/TypeScript/tsc/shim/scanner"
  iter "iter"
)

func ComputeLineOfPosition(p0 []tsccore.TextPos, p1 int) int {
  return tscscanner.ComputeLineOfPosition(p0, p1)
}

func ComputePositionOfLineAndByteOffset(p0 []tsccore.TextPos, p1 int, p2 int) int {
  return tscscanner.ComputePositionOfLineAndByteOffset(p0, p1, p2)
}

// ComputePositionOfLineAndUTF16Character holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.UTF16Offset).
var ComputePositionOfLineAndUTF16Character = tscscanner.ComputePositionOfLineAndUTF16Character

func DeclarationNameToString(p0 *tscast.Node) string {
  return tscscanner.DeclarationNameToString(p0)
}

type ErrorCallback = tscscanner.ErrorCallback

type EscapeSequenceScanningFlags = tscscanner.EscapeSequenceScanningFlags

const EscapeSequenceScanningFlagsAllowExtendedUnicodeEscape = tscscanner.EscapeSequenceScanningFlagsAllowExtendedUnicodeEscape

const EscapeSequenceScanningFlagsAnnexB = tscscanner.EscapeSequenceScanningFlagsAnnexB

const EscapeSequenceScanningFlagsAnyUnicodeMode = tscscanner.EscapeSequenceScanningFlagsAnyUnicodeMode

const EscapeSequenceScanningFlagsAtomEscape = tscscanner.EscapeSequenceScanningFlagsAtomEscape

const EscapeSequenceScanningFlagsRegularExpression = tscscanner.EscapeSequenceScanningFlagsRegularExpression

const EscapeSequenceScanningFlagsReportErrors = tscscanner.EscapeSequenceScanningFlagsReportErrors

const EscapeSequenceScanningFlagsReportInvalidEscapeErrors = tscscanner.EscapeSequenceScanningFlagsReportInvalidEscapeErrors

const EscapeSequenceScanningFlagsString = tscscanner.EscapeSequenceScanningFlagsString

func GetECMAEndLinePosition(p0 *tscast.SourceFile, p1 int) int {
  return tscscanner.GetECMAEndLinePosition(p0, p1)
}

func GetECMALineAndByteOffsetOfPosition(p0 tscast.SourceFileLike, p1 int) (int, int) {
  return tscscanner.GetECMALineAndByteOffsetOfPosition(p0, p1)
}

// GetECMALineAndUTF16CharacterOfPosition holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.UTF16Offset).
var GetECMALineAndUTF16CharacterOfPosition = tscscanner.GetECMALineAndUTF16CharacterOfPosition

func GetECMALineOfPosition(p0 tscast.SourceFileLike, p1 int) int {
  return tscscanner.GetECMALineOfPosition(p0, p1)
}

func GetECMALineStarts(p0 tscast.SourceFileLike) []tsccore.TextPos {
  return tscscanner.GetECMALineStarts(p0)
}

func GetECMAPositionOfLineAndByteOffset(p0 tscast.SourceFileLike, p1 int, p2 int) int {
  return tscscanner.GetECMAPositionOfLineAndByteOffset(p0, p1, p2)
}

// GetECMAPositionOfLineAndUTF16Character holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.UTF16Offset).
var GetECMAPositionOfLineAndUTF16Character = tscscanner.GetECMAPositionOfLineAndUTF16Character

func GetErrorRangeForNode(p0 *tscast.SourceFile, p1 *tscast.Node) tsccore.TextRange {
  return tscscanner.GetErrorRangeForNode(p0, p1)
}

func GetIdentifierToken(p0 string) tscast.Kind {
  return tscscanner.GetIdentifierToken(p0)
}

func GetLeadingCommentRanges(p0 *tscast.NodeFactory, p1 string, p2 int) iter.Seq[tscast.CommentRange] {
  return tscscanner.GetLeadingCommentRanges(p0, p1, p2)
}

func GetRangeOfTokenAtPosition(p0 *tscast.SourceFile, p1 int) tsccore.TextRange {
  return tscscanner.GetRangeOfTokenAtPosition(p0, p1)
}

func GetScannerForSourceFile(p0 *tscast.SourceFile, p1 int) *tscscanner.Scanner {
  return tscscanner.GetScannerForSourceFile(p0, p1)
}

func GetShebang(p0 string) string {
  return tscscanner.GetShebang(p0)
}

func GetSourceTextOfNodeFromSourceFile(p0 *tscast.SourceFile, p1 *tscast.Node, p2 bool) string {
  return tscscanner.GetSourceTextOfNodeFromSourceFile(p0, p1, p2)
}

func GetTextOfJSDocComment(p0 *tscast.NodeList) string {
  return tscscanner.GetTextOfJSDocComment(p0)
}

func GetTextOfNode(p0 *tscast.Node) string {
  return tscscanner.GetTextOfNode(p0)
}

func GetTextOfNodeFromSourceText(p0 string, p1 *tscast.Node, p2 bool) string {
  return tscscanner.GetTextOfNodeFromSourceText(p0, p1, p2)
}

func GetTokenPosOfNode(p0 *tscast.Node, p1 *tscast.SourceFile, p2 bool) int {
  return tscscanner.GetTokenPosOfNode(p0, p1, p2)
}

func GetTrailingCommentRanges(p0 *tscast.NodeFactory, p1 string, p2 int) iter.Seq[tscast.CommentRange] {
  return tscscanner.GetTrailingCommentRanges(p0, p1, p2)
}

func GetViableKeywordSuggestions() []string {
  return tscscanner.GetViableKeywordSuggestions()
}

func IdentifierToKeywordKind(p0 *tscast.Identifier) tscast.Kind {
  return tscscanner.IdentifierToKeywordKind(p0)
}

func IsIdentifierPart(p0 rune) bool {
  return tscscanner.IsIdentifierPart(p0)
}

// IsIdentifierPartEx holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.LanguageVariant).
var IsIdentifierPartEx = tscscanner.IsIdentifierPartEx

func IsIdentifierStart(p0 rune) bool {
  return tscscanner.IsIdentifierStart(p0)
}

// IsIdentifierText holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.LanguageVariant).
var IsIdentifierText = tscscanner.IsIdentifierText

func IsIntrinsicJsxName(p0 string) bool {
  return tscscanner.IsIntrinsicJsxName(p0)
}

func IsValidIdentifier(p0 string) bool {
  return tscscanner.IsValidIdentifier(p0)
}

func IsValidRegularExpressionLiteral(p0 string) bool {
  return tscscanner.IsValidRegularExpressionLiteral(p0)
}

func NewScanner() *tscscanner.Scanner {
  return tscscanner.NewScanner()
}

func ScanTokenAtPosition(p0 *tscast.SourceFile, p1 int) tscast.Kind {
  return tscscanner.ScanTokenAtPosition(p0, p1)
}

type Scanner = tscscanner.Scanner

type ScannerState = tscscanner.ScannerState

func SkipTrivia(p0 string, p1 int) int {
  return tscscanner.SkipTrivia(p0, p1)
}

func SkipTriviaEx(p0 string, p1 int, p2 *tscscanner.SkipTriviaOptions) int {
  return tscscanner.SkipTriviaEx(p0, p1, p2)
}

type SkipTriviaOptions = tscscanner.SkipTriviaOptions

func StringToToken(p0 string) tscast.Kind {
  return tscscanner.StringToToken(p0)
}

func TokenToString(p0 tscast.Kind) string {
  return tscscanner.TokenToString(p0)
}
