// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package diagnosticwriter is the documented github.com/microsoft/typescript-go/shim/diagnosticwriter plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/diagnosticwriter, the
// bridge that reaches the compiler's internal packages.
package diagnosticwriter

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tscdiagnosticwriter "github.com/microsoft/TypeScript/tsc/shim/diagnosticwriter"
  io "io"
)

func FormatASTDiagnosticsWithColorAndContext(p0 io.Writer, p1 []*tscast.Diagnostic, p2 string) {
  tscdiagnosticwriter.FormatASTDiagnosticsWithColorAndContext(p0, p1, p2)
}

func FormatMixedDiagnostics(p0 io.Writer, p1 []*tscast.Diagnostic, p2 []*tscdiagnosticwriter.LintDiagnostic, p3 string) int {
  return tscdiagnosticwriter.FormatMixedDiagnostics(p0, p1, p2, p3)
}

type LintCategory = tscdiagnosticwriter.LintCategory

const LintCategoryError = tscdiagnosticwriter.LintCategoryError

const LintCategoryWarning = tscdiagnosticwriter.LintCategoryWarning

type LintDiagnostic = tscdiagnosticwriter.LintDiagnostic

func NewLintDiagnostic(p0 *tscast.SourceFile, p1 int, p2 int, p3 int32, p4 tscdiagnosticwriter.LintCategory, p5 string) *tscdiagnosticwriter.LintDiagnostic {
  return tscdiagnosticwriter.NewLintDiagnostic(p0, p1, p2, p3, p4, p5)
}

func NormalizeLintRange(p0 *tscast.SourceFile, p1 int, p2 int) (int, int) {
  return tscdiagnosticwriter.NormalizeLintRange(p0, p1, p2)
}
