// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package astnav is the documented github.com/microsoft/typescript-go/shim/astnav plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/astnav, the
// bridge that reaches the compiler's internal packages.
package astnav

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tscastnav "github.com/microsoft/TypeScript/tsc/shim/astnav"
)

func GetTouchingToken(p0 *tscast.SourceFile, p1 int) *tscast.Node {
  return tscastnav.GetTouchingToken(p0, p1)
}
