// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package lsp is the documented github.com/microsoft/typescript-go/shim/lsp plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/lsp, the
// bridge that reaches the compiler's internal packages.
package lsp

import (
  tsclsp "github.com/microsoft/TypeScript/tsc/shim/lsp"
  io "io"
)

func NewServer(p0 *tsclsp.ServerOptions) *tsclsp.Server {
  return tsclsp.NewServer(p0)
}

type Reader = tsclsp.Reader

type Server = tsclsp.Server

type ServerOptions = tsclsp.ServerOptions

func ToReader(p0 io.Reader) tsclsp.Reader {
  return tsclsp.ToReader(p0)
}

func ToWriter(p0 io.Writer) tsclsp.Writer {
  return tsclsp.ToWriter(p0)
}

type Writer = tsclsp.Writer
