// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package compiler is the documented github.com/microsoft/typescript-go/shim/compiler plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/compiler, the
// bridge that reaches the compiler's internal packages.
package compiler

import (
  context "context"
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tsccompiler "github.com/microsoft/TypeScript/tsc/shim/compiler"
  tsccore "github.com/microsoft/TypeScript/tsc/shim/core"
  tscprinter "github.com/microsoft/TypeScript/tsc/shim/printer"
  tsctransformers "github.com/microsoft/TypeScript/tsc/shim/transformers"
  tsctspath "github.com/microsoft/TypeScript/tsc/shim/tspath"
  tscvfs "github.com/microsoft/TypeScript/tsc/shim/vfs"
)

type CheckerPool = tsccompiler.CheckerPool

func CombineEmitResults(p0 []*tsccompiler.EmitResult) *tsccompiler.EmitResult {
  return tsccompiler.CombineEmitResults(p0)
}

type CompilerHost = tsccompiler.CompilerHost

type DuplicateSourceFile = tsccompiler.DuplicateSourceFile

const EmitAll = tsccompiler.EmitAll

func EmitFreshWithBuildInfo(p0 context.Context, p1 *tsccompiler.Program, p2 tsccompiler.EmitOptions) *tsccompiler.EmitResult {
  return tsccompiler.EmitFreshWithBuildInfo(p0, p1, p2)
}

type EmitHost = tsccompiler.EmitHost

type EmitOnly = tsccompiler.EmitOnly

const EmitOnlyBuilderSignature = tsccompiler.EmitOnlyBuilderSignature

const EmitOnlyDts = tsccompiler.EmitOnlyDts

const EmitOnlyJs = tsccompiler.EmitOnlyJs

type EmitOptions = tsccompiler.EmitOptions

type EmitResult = tsccompiler.EmitResult

func FileAffectsGlobalScope(p0 *tscast.SourceFile) bool {
  return tsccompiler.FileAffectsGlobalScope(p0)
}

type FileIncludeReason = tsccompiler.FileIncludeReason

func FilterNoEmitSemanticDiagnostics(p0 []*tscast.Diagnostic, p1 *tsccore.CompilerOptions) []*tscast.Diagnostic {
  return tsccompiler.FilterNoEmitSemanticDiagnostics(p0, p1)
}

type ForceEmitPaths = tsccompiler.ForceEmitPaths

func GetDiagnosticsOfAnyProgram(p0 context.Context, p1 tsccompiler.ProgramLike, p2 []*tscast.SourceFile, p3 bool, p4 func(context.Context, *tscast.SourceFile) []*tscast.Diagnostic, p5 func(context.Context, *tscast.SourceFile) []*tscast.Diagnostic) []*tscast.Diagnostic {
  return tsccompiler.GetDiagnosticsOfAnyProgram(p0, p1, p2, p3, p4, p5)
}

// GetOutputPathsFor holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/outputpaths.OutputPathsHost).
var GetOutputPathsFor = tsccompiler.GetOutputPathsFor

func GetReferencedFilePaths(p0 *tsccompiler.Program, p1 *tscast.SourceFile) []tsctspath.PathKey {
  return tsccompiler.GetReferencedFilePaths(p0, p1)
}

func GetScriptTransformers(p0 tscprinter.EmitResolver, p1 tscprinter.EmitHost, p2 *tscast.SourceFile) []*tsctransformers.Transformer {
  return tsccompiler.GetScriptTransformers(p0, p1, p2)
}

func GetSourceFilesToEmit(p0 tsccompiler.SourceFileMayBeEmittedHost, p1 []*tscast.SourceFile, p2 bool, p3 bool) []*tscast.SourceFile {
  return tsccompiler.GetSourceFilesToEmit(p0, p1, p2, p3)
}

func HandleNoEmitOptions(p0 context.Context, p1 tsccompiler.ProgramLike, p2 []*tscast.SourceFile, p3 func() *tsccompiler.EmitResult) *tsccompiler.EmitResult {
  return tsccompiler.HandleNoEmitOptions(p0, p1, p2, p3)
}

type LibFile = tsccompiler.LibFile

// NewCachedFSCompilerHost holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/diagnostics.Message).
var NewCachedFSCompilerHost = tsccompiler.NewCachedFSCompilerHost

// NewCompilerHost holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/diagnostics.Message).
var NewCompilerHost = tsccompiler.NewCompilerHost

func NewProgram(p0 tsccompiler.ProgramOptions) *tsccompiler.Program {
  return tsccompiler.NewProgram(p0)
}

type OutputPaths = tsccompiler.OutputPaths

func PrintFileWithSourceMap(p0 *tscprinter.EmitContext, p1 *tscast.Node, p2 *tscast.SourceFile, p3 *tsccore.CompilerOptions, p4 tsccompiler.SourceMapHost, p5 tsctspath.RootedFilePath, p6 tsctspath.RootedFilePath) tsccompiler.PrintedFile {
  return tsccompiler.PrintFileWithSourceMap(p0, p1, p2, p3, p4, p5, p6)
}

type PrintedFile = tsccompiler.PrintedFile

type Program = tsccompiler.Program

type ProgramConfig = tsccompiler.ProgramConfig

type ProgramFactories = tsccompiler.ProgramFactories

type ProgramHosts = tsccompiler.ProgramHosts

type ProgramLike = tsccompiler.ProgramLike

type ProgramOptions = tsccompiler.ProgramOptions

type ProgramResolutionKind = tsccompiler.ProgramResolutionKind

const ProgramResolutionKindModule = tsccompiler.ProgramResolutionKindModule

const ProgramResolutionKindTypeReference = tsccompiler.ProgramResolutionKindTypeReference

type ProgramResolutionTask = tsccompiler.ProgramResolutionTask

func ProgramResolutionTasks(p0 *tsccompiler.Program) []tsccompiler.ProgramResolutionTask {
  return tsccompiler.ProgramResolutionTasks(p0)
}

func ReplayAutomaticTypeDirectiveDiscovery(p0 *tsccompiler.Program, p1 tscvfs.FS) {
  tsccompiler.ReplayAutomaticTypeDirectiveDiscovery(p0, p1)
}

func ReplayProgramResolutions(p0 []tsccompiler.ProgramResolutionTask, p1 tscvfs.FS) bool {
  return tsccompiler.ReplayProgramResolutions(p0, p1)
}

func SortAndDeduplicateDiagnostics(p0 []*tscast.Diagnostic) []*tscast.Diagnostic {
  return tsccompiler.SortAndDeduplicateDiagnostics(p0)
}

type SourceFileMayBeEmittedHost = tsccompiler.SourceFileMayBeEmittedHost

func SourceMapDirectory(p0 *tsccore.CompilerOptions, p1 tsccompiler.SourceMapHost, p2 tsctspath.RootedFilePath, p3 *tscast.SourceFile) tsctspath.RootedDirectoryPath {
  return tsccompiler.SourceMapDirectory(p0, p1, p2, p3)
}

type SourceMapEmitResult = tsccompiler.SourceMapEmitResult

type SourceMapHost = tsccompiler.SourceMapHost

type WriteFile = tsccompiler.WriteFile

type WriteFileData = tsccompiler.WriteFileData
