package graph

import (
  "path/filepath"
  "testing"

  "github.com/samchon/ttsc/packages/ttsc/driver"
)

// TestDumpIsAFunctionOfTheSource compares the serialized results of two
// independent loads of one unedited native project. Its two classes each have
// a private #count, but output equality alone does not prove either private
// member is present, collision-free or stable across a process restart.
//
// 1. Load the same Counter private-member and Other private-member source in two independent programs.
// 2. Build and serialize each graph without sharing a builder.
// 3. Require byte-identical dumps for these two loads; structural facts are not asserted here.
//
// @evidence contracts/testing.md#behavioral-verification Two independent compiler Programs and graph builders serialize the same authored declarations to identical dump bytes.
// @evidence contracts/testing.md#independent-expectations One unchanged fixture supplies both independent loads, so their literal equality requirement is not generated by the serializer. This oracle detects differing bytes but cannot prove structural completeness, private-member collision freedom or stability under other allocation histories.
// @evidence contracts/testing.md#distinguishing-cases Two independently constructed Programs and builders over the same private-member fixture must agree. No edited-source, empty-output or process-restart counterpart is asserted by this entry.
// @evidence contracts/testing.md#execution-ownership This Go source-unit writes one native project and loads and closes two actual driver Programs in-process, calling Build, SourceTexts and MarshalDump directly. A restored empty linked-plugin manifest excludes ambient hooks; no consumer installation or native product command runs.
func TestDumpIsAFunctionOfTheSource(t *testing.T) {
  t.Setenv(driver.LinkedPluginsEnv, "")
  root := t.TempDir()
  writeFile(t, filepath.Join(root, "tsconfig.json"), fixtureTSConfig)
  writeFile(t, filepath.Join(root, "src", "main.ts"), `export class Counter {
  #count = 0;
  #step: number;
  constructor(step: number) {
    this.#step = step;
  }
  bump(): number {
    this.#count += this.#step;
    return this.#count;
  }
}

export class Other {
  #count = 0;
  read(): number {
    return this.#count;
  }
}
`)

  first := dumpBytes(t, root)
  second := dumpBytes(t, root)
  if string(first) != string(second) {
    t.Fatalf("two dumps of one unedited snapshot differ: the graph is not a function of the source")
  }
}

func dumpBytes(t *testing.T, root string) []byte {
  t.Helper()
  prog, diags, err := driver.LoadProgram(root, "tsconfig.json", driver.LoadProgramOptions{})
  if err != nil {
    t.Fatal(err)
  }
  if len(diags) != 0 {
    t.Fatalf("unexpected diagnostics: %v", diags)
  }
  defer func() { _ = prog.Close() }()

  data, err := MarshalDump(Build(prog), root, "tsconfig.json", nil, SourceTexts(prog), DumpOrigin{}, false)
  if err != nil {
    t.Fatalf("MarshalDump: %v", err)
  }
  return data
}
