package graph

import (
  "path/filepath"
  "slices"
  "testing"

  "github.com/samchon/ttsc/packages/ttsc/driver"
)

// TestLiteralsDoNotDependOnDeclarationLineWrapping verifies that collectLiterals
// answers with the union's members for two authored layouts: the same
// eight-member type written one member per line and written on one line both
// report all eight.
//
// Exact eight-value expectations reject a six-value truncation in either form;
// output equality alone would not. Other layouts and population limits are not
// asserted by this entry.
//
//  1. Compile a fixture with a wrapped union and a flat union of the same eight
//     string literals.
//  2. Build the graph.
//  3. Assert both nodes carry all eight values, in source form, and that the two
//     lists are identical.
//
// @evidence contracts/testing.md#behavioral-verification Build must report the exact ordered eight-value array for both authored Wrapped and Flat aliases, then their arrays must agree. The check covers these two layouts, not all declaration formatting or type populations.
// @evidence contracts/testing.md#independent-expectations Both aliases have independent literal quoted a-through-h expected arrays; exact checks precede pair equality so two equally truncated results cannot pass. The wrapped form includes one authored trailing comment. No expected list is generated by the literal renderer.
// @evidence contracts/testing.md#distinguishing-cases Compile a fixture with a wrapped union and a flat union of the same eight string literals; Build the graph; Assert both nodes carry all eight values, in source form, and that the two lists are identical.
// @evidence contracts/testing.md#execution-ownership This Go source-unit writes a native project, constructs/closes its driver Program in-process and directly calls Build and the existing-node literalsOf helper. Actual filename/shared nodeID formatting select aliases, not an independent ID-grammar oracle. A restored empty linked-plugin manifest excludes ambient hooks; no emit, consumer installation or product process runs.
func TestLiteralsDoNotDependOnDeclarationLineWrapping(t *testing.T) {
  t.Setenv(driver.LinkedPluginsEnv, "")
  root := t.TempDir()
  writeFile(t, filepath.Join(root, "tsconfig.json"), fixtureTSConfig)
  writeFile(t, filepath.Join(root, "src", "main.ts"), `export type Wrapped =
  | 'a' // a trailing comment the old snippet scrape also had to survive
  | 'b'
  | 'c'
  | 'd'
  | 'e'
  | 'f'
  | 'g'
  | 'h';

export type Flat = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h';
`)

  prog, diags, err := driver.LoadProgram(root, "tsconfig.json", driver.LoadProgramOptions{})
  if err != nil {
    t.Fatal(err)
  }
  if len(diags) != 0 {
    t.Fatalf("unexpected diagnostics: %v", diags)
  }
  defer func() { _ = prog.Close() }()

  graph := Build(prog)
  path := sourceFile(t, prog, "main.ts").FileName()

  want := []string{`"a"`, `"b"`, `"c"`, `"d"`, `"e"`, `"f"`, `"g"`, `"h"`}
  wrapped := literalsOf(t, graph, nodeID(path, "Wrapped", NodeTypeAlias))
  flat := literalsOf(t, graph, nodeID(path, "Flat", NodeTypeAlias))

  if !slices.Equal(wrapped, want) {
    t.Fatalf("wrapped union under-reported its members: got %v, want %v", wrapped, want)
  }
  if !slices.Equal(flat, want) {
    t.Fatalf("flat union under-reported its members: got %v, want %v", flat, want)
  }
  // The point of the fix stated directly: layout is not allowed to change the
  // answer for one and the same type.
  if !slices.Equal(wrapped, flat) {
    t.Fatalf("line wrapping changed the value set: wrapped %v, flat %v", wrapped, flat)
  }
}

// literalsOf returns the recorded value set of the node id names, failing the
// test when the graph holds no such node.
func literalsOf(t *testing.T, graph *Graph, id string) []string {
  t.Helper()
  node, ok := graph.Nodes[id]
  if !ok {
    t.Fatalf("graph has no node %q; nodes: %v", id, nodeIDSet(graph))
  }
  return node.Literals
}
