package graph

import (
  "path/filepath"
  "testing"
)

// TestNodeIDsPreserveHashBearingComponents verifies graph identity: quoted
// path and symbol hashes remain structured facts through dump relativization.
//
// A source path and an authored private member may both contain '#'. Splitting
// the display id at either raw occurrence would lose the intended path/symbol
// boundary. The
// codec must escape those components while keeping ordinary ids byte-identical.
//
//  1. Build ordinary and hash-bearing ids from their raw structured facts.
//  2. Relativize the hash-bearing id as the dump does.
//  3. Recover its raw file component and assert the escaped wire spelling.
//
// @evidence contracts/testing.md#behavioral-verification Verifies graph identity: quoted path and symbol hashes remain structured facts through dump relativization.
// @evidence contracts/testing.md#independent-expectations The body supplies exact literal ordinary and escaped IDs: ordinary src/main.ts#main:function, doubled Windows backslashes with escaped path hash and an unchanged colon-bearing symbol name, and escaped relative path/private-member hashes. Parsing must recover the authored raw path/name, and nodeFile must return literal src#generated/main#file.ts. These string expectations are not generated by the codec; real compiler private-member binding and physical source identity are not authenticated.
// @evidence contracts/testing.md#distinguishing-cases Build ordinary and hash-bearing ids from their raw structured facts; Relativize the hash-bearing id as the dump does; Recover its raw file component and assert the escaped wire spelling.
// @evidence contracts/testing.md#execution-ownership This same-package Go unit directly calls nodeID, parseNodeID, newDumpContext, relID and nodeFile on authored strings. Only the temporary parent directory is created; the hash-bearing project/source paths are absent and can use native existing-ancestor canonicalization. No source files, compiler Program, dump serialization, installed consumer or product process are created.
func TestNodeIDsPreserveHashBearingComponents(t *testing.T) {
  if got, want := nodeID("src/main.ts", "main", NodeFunction), "src/main.ts#main:function"; got != want {
    t.Fatalf("ordinary id = %q, want %q", got, want)
  }
  if got, want := nodeID(`C:\work\a#b\main.ts`, "label:part", NodeVariable), `C:\\work\\a\#b\\main.ts#label:part:variable`; got != want {
    t.Fatalf("escaped id = %q, want %q", got, want)
  } else if parts, ok := parseNodeID(got); !ok || parts.path != `C:\work\a#b\main.ts` || parts.name != "label:part" {
    t.Fatalf("decoded id = %#v, %t; want raw path and name", parts, ok)
  }

  root := filepath.Join(t.TempDir(), "a#b")
  file := filepath.Join(root, "src#generated", "main#file.ts")
  id := nodeID(file, "Counter.#count", NodeVariable)
  context := newDumpContext(root, nil)
  got := context.relID(id)
  want := "src\\#generated/main\\#file.ts#Counter.\\#count:variable"
  if got != want {
    t.Fatalf("relativized id = %q, want %q", got, want)
  }
  if file := nodeFile(got); file != "src#generated/main#file.ts" {
    t.Fatalf("decoded file = %q, want raw hash-bearing relative path", file)
  }
  if err := context.pathError(); err != nil {
    t.Fatalf("relativizing the authored ID failed: %v", err)
  }
}
