packages:
  - 'config'
  - 'packages/*'
  - 'tests/*'
catalogs:
  tsgo:
    '@typescript/native-preview': 7.0.0-dev.20260511.1
  utils:
    '@nestia/e2e': ^11.2.0
    '@types/node': ^25.3.0
    rimraf: ^6.1.2
