import assert from "node:assert/strict";
import path from "node:path";

import { createFilesystemPathIdentityContext } from "../../../../../packages/ttsc/src/internal/pathIdentity/createFilesystemPathIdentityContext";
import { normalizeHostInputName } from "../../../../../packages/unplugin/src/core/transform/filesystem/normalizeHostInputName";
import { pathIdentityKey } from "../../../../../packages/unplugin/src/core/transform/filesystem/pathIdentityKey";

/**
 * Verifies observed directory policy merges ordinary Windows spellings while
 * preserving sensitive existing files and unresolved candidate spellings.
 *
 * Windows grammar alone does not supply a directory's case policy. The authored
 * native view supplies canonical ordinary prefixes and two distinct sensitive
 * files, so this case does not infer policy from its execution host.
 *
 * 1. Resolve ordinary aliases through one explicit Windows identity context.
 * 2. Contrast sensitive existing twins and missing Future/future candidates.
 * 3. Normalize the literal ASCII watcher name under both directory policies.
 *
 * @evidence contracts/testing.md#behavioral-verification Calls actual pathIdentityKey over a maintained explicit-platform identity context and actual normalizeHostInputName. Ordinary aliases compare equal; sensitive existing and missing twins compare unequal; Selection.JS folds only under insensitive policy.
 * @evidence contracts/testing.md#independent-expectations The supplied directory capability and literal native prefix/file answers define equivalence independently of the resolver. Expected equal/unequal relations and literal selection.js/Selection.JS are not generated by another product helper. ENOENT answers mark unresolved suffixes without pretending real host files exist.
 * @evidence contracts/testing.md#distinguishing-cases Ordinary insensitive aliases contrast with sensitive existing Main/main and missing Future/future. Both normalization policies retain the original ASCII event assertion. Native envelope/output/cache/external deduplication and UNC host observations remain with E2E rather than being certified by this authored view.
 * @evidence contracts/testing.md#execution-ownership This discoverable unit owns the five direct assertions and the supported Win32 context operations. It starts no process, native filesystem probe, compiler, binary or host; it models declared filesystem answers rather than claiming actual Windows-volume reproduction.
 */
export async function test_path_identity_preserves_directory_case_ownership(): Promise<void> {
  const windows = createFilesystemPathIdentityContext({
    platform: "win32",
    caseSensitive: (directory) =>
      directory.toLowerCase().startsWith("c:\\sensitive"),
    realpath: (location) => {
      const resolved = path.win32.resolve(location);
      const folded = resolved.toLowerCase();
      if (folded === "c:\\ordinary") return "C:\\Ordinary";
      if (folded === "c:\\ordinary\\src") return "C:\\Ordinary\\src";
      if (resolved === "C:\\Sensitive") return resolved;
      if (resolved === "C:\\Sensitive\\src") return resolved;
      if (resolved === "C:\\Sensitive\\src\\Main.ts") return resolved;
      if (resolved === "C:\\Sensitive\\src\\main.ts") return resolved;
      throw Object.assign(new Error("authored native entry is absent"), {
        code: "ENOENT",
      });
    },
  });
  assert.equal(
    pathIdentityKey("C:\\ORDINARY\\src\\Main.ts", windows),
    pathIdentityKey("c:\\ordinary\\SRC\\main.ts", windows),
    "ordinary insensitive aliases share identity",
  );
  assert.notEqual(
    pathIdentityKey("C:\\Sensitive\\src\\Main.ts", windows),
    pathIdentityKey("C:\\Sensitive\\src\\main.ts", windows),
    "sensitive existing twins remain independent",
  );
  assert.notEqual(
    pathIdentityKey("C:\\Sensitive\\src\\Future.ts", windows),
    pathIdentityKey("C:\\Sensitive\\src\\future.ts", windows),
    "missing candidates inherit sensitive directory ownership",
  );
  assert.equal(normalizeHostInputName("Selection.JS", false), "selection.js");
  assert.equal(normalizeHostInputName("Selection.JS", true), "Selection.JS");
}
