// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package ast is the documented github.com/microsoft/typescript-go/shim/ast plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/ast, the
// bridge that reaches the compiler's internal packages.
package ast

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
)

type AbstractKeyword = tscast.AbstractKeyword

type AccessExpression = tscast.AccessExpression

type AccessKind = tscast.AccessKind

type AccessorDeclaration = tscast.AccessorDeclaration

type AccessorDeclarationBase = tscast.AccessorDeclarationBase

type AccessorKeyword = tscast.AccessorKeyword

type AdditiveOperator = tscast.AdditiveOperator

type AdditiveOperatorOrHigher = tscast.AdditiveOperatorOrHigher

type AllAccessorDeclarations = tscast.AllAccessorDeclarations

type AnyImportOrRequireStatement = tscast.AnyImportOrRequireStatement

type AnyImportSyntax = tscast.AnyImportSyntax

type AnyValidImportOrReExport = tscast.AnyValidImportOrReExport

type ArgumentList = tscast.ArgumentList

type ArrayBindingElement = tscast.ArrayBindingElement

type ArrayDestructuringAssignment = tscast.ArrayDestructuringAssignment

type ArrayLiteralExpression = tscast.ArrayLiteralExpression

type ArrayLiteralExpressionNode = tscast.ArrayLiteralExpressionNode

type ArrayTypeNode = tscast.ArrayTypeNode

type ArrayTypeNodeNode = tscast.ArrayTypeNodeNode

type ArrowFunction = tscast.ArrowFunction

type ArrowFunctionNode = tscast.ArrowFunctionNode

type AsExpression = tscast.AsExpression

type AsExpressionNode = tscast.AsExpressionNode

type AssertKeyword = tscast.AssertKeyword

type AssertionExpression = tscast.AssertionExpression

type AssertsKeyword = tscast.AssertsKeyword

type AssignmentOperator = tscast.AssignmentOperator

type AssignmentOperatorOrHigher = tscast.AssignmentOperatorOrHigher

type AssignmentOperatorToken = tscast.AssignmentOperatorToken

type AsteriskToken = tscast.AsteriskToken

type AsyncKeyword = tscast.AsyncKeyword

type AwaitExpression = tscast.AwaitExpression

type AwaitExpressionNode = tscast.AwaitExpressionNode

type AwaitKeyword = tscast.AwaitKeyword

type BigIntLiteral = tscast.BigIntLiteral

type BigIntLiteralNode = tscast.BigIntLiteralNode

type BinaryExpression = tscast.BinaryExpression

type BinaryExpressionNode = tscast.BinaryExpressionNode

type BinaryOperator = tscast.BinaryOperator

type BinaryOperatorToken = tscast.BinaryOperatorToken

type BindingElement = tscast.BindingElement

type BindingElementList = tscast.BindingElementList

type BindingElementNode = tscast.BindingElementNode

type BindingName = tscast.BindingName

type BindingPattern = tscast.BindingPattern

type BindingPatternNode = tscast.BindingPatternNode

type BitwiseOperator = tscast.BitwiseOperator

type BitwiseOperatorOrHigher = tscast.BitwiseOperatorOrHigher

type Block = tscast.Block

type BlockNode = tscast.BlockNode

type BlockOrExpression = tscast.BlockOrExpression

type BodyBase = tscast.BodyBase

type BooleanLiteral = tscast.BooleanLiteral

type BreakOrContinueStatement = tscast.BreakOrContinueStatement

type BreakStatement = tscast.BreakStatement

type BreakStatementNode = tscast.BreakStatementNode

type CallExpression = tscast.CallExpression

type CallExpressionNode = tscast.CallExpressionNode

type CallLikeExpression = tscast.CallLikeExpression

type CallOrNewExpression = tscast.CallOrNewExpression

type CallSignatureDeclaration = tscast.CallSignatureDeclaration

type CallSignatureDeclarationNode = tscast.CallSignatureDeclarationNode

type CaseBlock = tscast.CaseBlock

type CaseBlockNode = tscast.CaseBlockNode

type CaseClausesList = tscast.CaseClausesList

type CaseKeyword = tscast.CaseKeyword

type CaseOrDefaultClause = tscast.CaseOrDefaultClause

type CaseOrDefaultClauseNode = tscast.CaseOrDefaultClauseNode

type CatchClause = tscast.CatchClause

type CatchClauseNode = tscast.CatchClauseNode

type CheckFlags = tscast.CheckFlags

type CheckJsDirective = tscast.CheckJsDirective

type ClassDeclaration = tscast.ClassDeclaration

type ClassDeclarationNode = tscast.ClassDeclarationNode

type ClassElement = tscast.ClassElement

type ClassElementBase = tscast.ClassElementBase

type ClassElementList = tscast.ClassElementList

type ClassExpression = tscast.ClassExpression

type ClassExpressionNode = tscast.ClassExpressionNode

type ClassLikeBase = tscast.ClassLikeBase

type ClassLikeDeclaration = tscast.ClassLikeDeclaration

type ClassStaticBlockDeclaration = tscast.ClassStaticBlockDeclaration

type ClassStaticBlockDeclarationNode = tscast.ClassStaticBlockDeclarationNode

type ColonToken = tscast.ColonToken

type CommentDirective = tscast.CommentDirective

type CommentDirectiveKind = tscast.CommentDirectiveKind

const CommentDirectiveKindExpectError = tscast.CommentDirectiveKindExpectError

const CommentDirectiveKindIgnore = tscast.CommentDirectiveKindIgnore

const CommentDirectiveKindUnknown = tscast.CommentDirectiveKindUnknown

type CommentRange = tscast.CommentRange

type CompositeBase = tscast.CompositeBase

type CompoundAssignmentOperator = tscast.CompoundAssignmentOperator

type ComputedPropertyName = tscast.ComputedPropertyName

type ComputedPropertyNameNode = tscast.ComputedPropertyNameNode

type ConciseBody = tscast.ConciseBody

type ConditionalExpression = tscast.ConditionalExpression

type ConditionalExpressionNode = tscast.ConditionalExpressionNode

type ConditionalTypeNode = tscast.ConditionalTypeNode

type ConditionalTypeNodeNode = tscast.ConditionalTypeNodeNode

type ConstKeyword = tscast.ConstKeyword

type ConstructSignatureDeclaration = tscast.ConstructSignatureDeclaration

type ConstructSignatureDeclarationNode = tscast.ConstructSignatureDeclarationNode

type ConstructorDeclaration = tscast.ConstructorDeclaration

type ConstructorDeclarationNode = tscast.ConstructorDeclarationNode

type ConstructorTypeNode = tscast.ConstructorTypeNode

type ConstructorTypeNodeNode = tscast.ConstructorTypeNodeNode

type ContinueStatement = tscast.ContinueStatement

type ContinueStatementNode = tscast.ContinueStatementNode

type DebuggerStatement = tscast.DebuggerStatement

type DebuggerStatementNode = tscast.DebuggerStatementNode

type Declaration = tscast.Declaration

type DeclarationBase = tscast.DeclarationBase

type DeclarationName = tscast.DeclarationName

type DeclareKeyword = tscast.DeclareKeyword

type Decorator = tscast.Decorator

type DecoratorNode = tscast.DecoratorNode

type DefaultKeyword = tscast.DefaultKeyword

type DeleteExpression = tscast.DeleteExpression

type DeleteExpressionNode = tscast.DeleteExpressionNode

type DestructuringAssignment = tscast.DestructuringAssignment

type Diagnostic = tscast.Diagnostic

type DiagnosticsCollection = tscast.DiagnosticsCollection

type DoStatement = tscast.DoStatement

type DoStatementNode = tscast.DoStatementNode

type DotDotDotToken = tscast.DotDotDotToken

type DotToken = tscast.DotToken

type ElementAccessExpression = tscast.ElementAccessExpression

type ElementAccessExpressionNode = tscast.ElementAccessExpressionNode

type ElementList = tscast.ElementList

type EmptyStatement = tscast.EmptyStatement

type EmptyStatementNode = tscast.EmptyStatementNode

type EndOfFile = tscast.EndOfFile

type EntityName = tscast.EntityName

type EnumDeclaration = tscast.EnumDeclaration

type EnumDeclarationNode = tscast.EnumDeclarationNode

type EnumMember = tscast.EnumMember

type EnumMemberList = tscast.EnumMemberList

type EnumMemberNode = tscast.EnumMemberNode

type EqualityOperator = tscast.EqualityOperator

type EqualityOperatorOrHigher = tscast.EqualityOperatorOrHigher

type EqualsGreaterThanToken = tscast.EqualsGreaterThanToken

type EqualsToken = tscast.EqualsToken

type ExclamationToken = tscast.ExclamationToken

type ExponentiationOperator = tscast.ExponentiationOperator

type ExportAssignment = tscast.ExportAssignment

type ExportAssignmentNode = tscast.ExportAssignmentNode

type ExportDeclaration = tscast.ExportDeclaration

type ExportDeclarationNode = tscast.ExportDeclarationNode

type ExportKeyword = tscast.ExportKeyword

type ExportSpecifier = tscast.ExportSpecifier

type ExportSpecifierList = tscast.ExportSpecifierList

type ExportSpecifierNode = tscast.ExportSpecifierNode

type ExportableBase = tscast.ExportableBase

type Expression = tscast.Expression

type ExpressionBase = tscast.ExpressionBase

type ExpressionStatement = tscast.ExpressionStatement

type ExpressionStatementNode = tscast.ExpressionStatementNode

type ExpressionWithTypeArguments = tscast.ExpressionWithTypeArguments

type ExpressionWithTypeArgumentsList = tscast.ExpressionWithTypeArgumentsList

type ExpressionWithTypeArgumentsNode = tscast.ExpressionWithTypeArgumentsNode

type ExternalModuleIndicatorOptions = tscast.ExternalModuleIndicatorOptions

type ExternalModuleReference = tscast.ExternalModuleReference

type ExternalModuleReferenceNode = tscast.ExternalModuleReferenceNode

type FalseLiteral = tscast.FalseLiteral

type FileReference = tscast.FileReference

type FindAncestorResult = tscast.FindAncestorResult

type FlowFlags = tscast.FlowFlags

type FlowLabel = tscast.FlowLabel

type FlowList = tscast.FlowList

type FlowNode = tscast.FlowNode

type FlowNodeBase = tscast.FlowNodeBase

type FlowReduceLabelData = tscast.FlowReduceLabelData

type FlowSwitchClauseData = tscast.FlowSwitchClauseData

type ForInOrOfStatement = tscast.ForInOrOfStatement

type ForInOrOfStatementNode = tscast.ForInOrOfStatementNode

type ForInitializer = tscast.ForInitializer

type ForStatement = tscast.ForStatement

type ForStatementNode = tscast.ForStatementNode

type FunctionBody = tscast.FunctionBody

type FunctionDeclaration = tscast.FunctionDeclaration

type FunctionDeclarationNode = tscast.FunctionDeclarationNode

type FunctionExpression = tscast.FunctionExpression

type FunctionExpressionNode = tscast.FunctionExpressionNode

type FunctionFlags = tscast.FunctionFlags

type FunctionLikeBase = tscast.FunctionLikeBase

type FunctionLikeDeclaration = tscast.FunctionLikeDeclaration

type FunctionLikeWithBodyBase = tscast.FunctionLikeWithBodyBase

type FunctionOrConstructorTypeNodeBase = tscast.FunctionOrConstructorTypeNodeBase

type FunctionTypeNode = tscast.FunctionTypeNode

type FunctionTypeNodeNode = tscast.FunctionTypeNodeNode

type GetAccessorDeclaration = tscast.GetAccessorDeclaration

type GetAccessorDeclarationNode = tscast.GetAccessorDeclarationNode

func GetCombinedModifierFlags(p0 *tscast.Node) tscast.ModifierFlags {
  return tscast.GetCombinedModifierFlags(p0)
}

func GetCombinedNodeFlags(p0 *tscast.Node) tscast.NodeFlags {
  return tscast.GetCombinedNodeFlags(p0)
}

func GetExpressionPrecedence(p0 *tscast.Expression) tscast.OperatorPrecedence {
  return tscast.GetExpressionPrecedence(p0)
}

func GetNextJSDocCommentLocation(p0 *tscast.Node) *tscast.Node {
  return tscast.GetNextJSDocCommentLocation(p0)
}

func GetNodeAtPosition(p0 *tscast.SourceFile, p1 int, p2 bool) *tscast.Node {
  return tscast.GetNodeAtPosition(p0, p1, p2)
}

func GetSourceFileOfNode(p0 *tscast.Node) *tscast.SourceFile {
  return tscast.GetSourceFileOfNode(p0)
}

type HasFileName = tscast.HasFileName

type HeritageClause = tscast.HeritageClause

type HeritageClauseList = tscast.HeritageClauseList

type HeritageClauseNode = tscast.HeritageClauseNode

type Identifier = tscast.Identifier

type IdentifierNode = tscast.IdentifierNode

type IfStatement = tscast.IfStatement

type IfStatementNode = tscast.IfStatementNode

type ImportAttribute = tscast.ImportAttribute

type ImportAttributeList = tscast.ImportAttributeList

type ImportAttributeName = tscast.ImportAttributeName

type ImportAttributeNode = tscast.ImportAttributeNode

type ImportAttributes = tscast.ImportAttributes

type ImportAttributesNode = tscast.ImportAttributesNode

type ImportClause = tscast.ImportClause

type ImportClauseNode = tscast.ImportClauseNode

type ImportClauseOrBindingPattern = tscast.ImportClauseOrBindingPattern

type ImportDeclaration = tscast.ImportDeclaration

type ImportDeclarationNode = tscast.ImportDeclarationNode

type ImportEqualsDeclaration = tscast.ImportEqualsDeclaration

type ImportEqualsDeclarationNode = tscast.ImportEqualsDeclarationNode

type ImportExpression = tscast.ImportExpression

type ImportPhaseModifierSyntaxKind = tscast.ImportPhaseModifierSyntaxKind

type ImportSpecifier = tscast.ImportSpecifier

type ImportSpecifierList = tscast.ImportSpecifierList

type ImportSpecifierNode = tscast.ImportSpecifierNode

type ImportTypeNode = tscast.ImportTypeNode

type ImportTypeNodeNode = tscast.ImportTypeNodeNode

type InKeyword = tscast.InKeyword

type IncrementExpression = tscast.IncrementExpression

type IndexSignatureDeclaration = tscast.IndexSignatureDeclaration

type IndexSignatureDeclarationNode = tscast.IndexSignatureDeclarationNode

type IndexedAccessTypeNode = tscast.IndexedAccessTypeNode

type IndexedAccessTypeNodeNode = tscast.IndexedAccessTypeNodeNode

type InferTypeNode = tscast.InferTypeNode

type InferTypeNodeNode = tscast.InferTypeNodeNode

type InterfaceDeclaration = tscast.InterfaceDeclaration

type InterfaceDeclarationNode = tscast.InterfaceDeclarationNode

type IntersectionTypeNode = tscast.IntersectionTypeNode

type IntersectionTypeNodeNode = tscast.IntersectionTypeNodeNode

func IsAmbientModuleSymbolName(p0 string) bool {
  return tscast.IsAmbientModuleSymbolName(p0)
}

func IsBindingElement(p0 *tscast.Node) bool {
  return tscast.IsBindingElement(p0)
}

func IsBindingPattern(p0 *tscast.Node) bool {
  return tscast.IsBindingPattern(p0)
}

func IsConst(p0 *tscast.Node) bool {
  return tscast.IsConst(p0)
}

func IsConstAssertion(p0 *tscast.Node) bool {
  return tscast.IsConstAssertion(p0)
}

func IsDeclaration(p0 *tscast.Node) bool {
  return tscast.IsDeclaration(p0)
}

func IsDeclarationNameOrImportPropertyName(p0 *tscast.Node) bool {
  return tscast.IsDeclarationNameOrImportPropertyName(p0)
}

func IsElementAccessExpression(p0 *tscast.Node) bool {
  return tscast.IsElementAccessExpression(p0)
}

func IsExpressionNode(p0 *tscast.Node) bool {
  return tscast.IsExpressionNode(p0)
}

func IsFunctionLike(p0 *tscast.Node) bool {
  return tscast.IsFunctionLike(p0)
}

func IsImplicitlyExportedJSDocDeclaration(p0 *tscast.Node) bool {
  return tscast.IsImplicitlyExportedJSDocDeclaration(p0)
}

func IsLet(p0 *tscast.Node) bool {
  return tscast.IsLet(p0)
}

func IsModuleBlock(p0 *tscast.Node) bool {
  return tscast.IsModuleBlock(p0)
}

func IsNamedEvaluationSource(p0 *tscast.Node) bool {
  return tscast.IsNamedEvaluationSource(p0)
}

func IsPartOfTypeNode(p0 *tscast.Node) bool {
  return tscast.IsPartOfTypeNode(p0)
}

func IsPropertyAccessExpression(p0 *tscast.Node) bool {
  return tscast.IsPropertyAccessExpression(p0)
}

func IsPropertyAssignment(p0 *tscast.Node) bool {
  return tscast.IsPropertyAssignment(p0)
}

func IsPropertyDeclaration(p0 *tscast.Node) bool {
  return tscast.IsPropertyDeclaration(p0)
}

func IsProtoSetter(p0 *tscast.Node) bool {
  return tscast.IsProtoSetter(p0)
}

func IsStringLiteral(p0 *tscast.Node) bool {
  return tscast.IsStringLiteral(p0)
}

func IsTokenKind(p0 tscast.Kind) bool {
  return tscast.IsTokenKind(p0)
}

func IsTypeDeclaration(p0 *tscast.Node) bool {
  return tscast.IsTypeDeclaration(p0)
}

func IsTypeDeclarationName(p0 *tscast.Node) bool {
  return tscast.IsTypeDeclarationName(p0)
}

func IsVar(p0 *tscast.Node) bool {
  return tscast.IsVar(p0)
}

type IterationStatementBase = tscast.IterationStatementBase

type JSDeclarationKind = tscast.JSDeclarationKind

type JSDoc = tscast.JSDoc

type JSDocAllType = tscast.JSDocAllType

type JSDocAllTypeNode = tscast.JSDocAllTypeNode

type JSDocAugmentsTag = tscast.JSDocAugmentsTag

type JSDocAugmentsTagNode = tscast.JSDocAugmentsTagNode

type JSDocCallbackTag = tscast.JSDocCallbackTag

type JSDocCallbackTagNode = tscast.JSDocCallbackTagNode

type JSDocComment = tscast.JSDocComment

type JSDocCommentBase = tscast.JSDocCommentBase

type JSDocDeprecatedTag = tscast.JSDocDeprecatedTag

type JSDocDeprecatedTagNode = tscast.JSDocDeprecatedTagNode

type JSDocImplementsTag = tscast.JSDocImplementsTag

type JSDocImplementsTagNode = tscast.JSDocImplementsTagNode

type JSDocImportTag = tscast.JSDocImportTag

type JSDocImportTagNode = tscast.JSDocImportTagNode

type JSDocLink = tscast.JSDocLink

type JSDocLinkCode = tscast.JSDocLinkCode

type JSDocLinkCodeNode = tscast.JSDocLinkCodeNode

type JSDocLinkNode = tscast.JSDocLinkNode

type JSDocLinkPlain = tscast.JSDocLinkPlain

type JSDocLinkPlainNode = tscast.JSDocLinkPlainNode

type JSDocNameReference = tscast.JSDocNameReference

type JSDocNameReferenceNode = tscast.JSDocNameReferenceNode

type JSDocNode = tscast.JSDocNode

type JSDocNodeSyntaxKind = tscast.JSDocNodeSyntaxKind

type JSDocNonNullableType = tscast.JSDocNonNullableType

type JSDocNonNullableTypeNode = tscast.JSDocNonNullableTypeNode

type JSDocNullableType = tscast.JSDocNullableType

type JSDocNullableTypeNode = tscast.JSDocNullableTypeNode

type JSDocOptionalType = tscast.JSDocOptionalType

type JSDocOptionalTypeNode = tscast.JSDocOptionalTypeNode

type JSDocOverloadTag = tscast.JSDocOverloadTag

type JSDocOverloadTagNode = tscast.JSDocOverloadTagNode

type JSDocOverrideTag = tscast.JSDocOverrideTag

type JSDocOverrideTagNode = tscast.JSDocOverrideTagNode

type JSDocParameterOrPropertyTag = tscast.JSDocParameterOrPropertyTag

type JSDocParameterOrPropertyTagNode = tscast.JSDocParameterOrPropertyTagNode

type JSDocPrivateTag = tscast.JSDocPrivateTag

type JSDocPrivateTagNode = tscast.JSDocPrivateTagNode

type JSDocProtectedTag = tscast.JSDocProtectedTag

type JSDocProtectedTagNode = tscast.JSDocProtectedTagNode

type JSDocPublicTag = tscast.JSDocPublicTag

type JSDocPublicTagNode = tscast.JSDocPublicTagNode

type JSDocReadonlyTag = tscast.JSDocReadonlyTag

type JSDocReadonlyTagNode = tscast.JSDocReadonlyTagNode

type JSDocReturnTag = tscast.JSDocReturnTag

type JSDocReturnTagNode = tscast.JSDocReturnTagNode

type JSDocSatisfiesTag = tscast.JSDocSatisfiesTag

type JSDocSatisfiesTagNode = tscast.JSDocSatisfiesTagNode

type JSDocSeeTag = tscast.JSDocSeeTag

type JSDocSeeTagNode = tscast.JSDocSeeTagNode

type JSDocSignature = tscast.JSDocSignature

type JSDocSignatureNode = tscast.JSDocSignatureNode

type JSDocTag = tscast.JSDocTag

type JSDocTagBase = tscast.JSDocTagBase

type JSDocTemplateTag = tscast.JSDocTemplateTag

type JSDocTemplateTagNode = tscast.JSDocTemplateTagNode

type JSDocText = tscast.JSDocText

type JSDocTextNode = tscast.JSDocTextNode

type JSDocThisTag = tscast.JSDocThisTag

type JSDocThisTagNode = tscast.JSDocThisTagNode

type JSDocThrowsTag = tscast.JSDocThrowsTag

type JSDocThrowsTagNode = tscast.JSDocThrowsTagNode

type JSDocTypeBase = tscast.JSDocTypeBase

type JSDocTypeExpression = tscast.JSDocTypeExpression

type JSDocTypeExpressionNode = tscast.JSDocTypeExpressionNode

type JSDocTypeLiteral = tscast.JSDocTypeLiteral

type JSDocTypeLiteralNode = tscast.JSDocTypeLiteralNode

type JSDocTypeTag = tscast.JSDocTypeTag

type JSDocTypeTagNode = tscast.JSDocTypeTagNode

type JSDocTypedefTag = tscast.JSDocTypedefTag

type JSDocTypedefTagNode = tscast.JSDocTypedefTagNode

type JSDocUnknownTag = tscast.JSDocUnknownTag

type JSDocUnknownTagNode = tscast.JSDocUnknownTagNode

type JSDocVariadicType = tscast.JSDocVariadicType

type JSDocVariadicTypeNode = tscast.JSDocVariadicTypeNode

type JsxAttribute = tscast.JsxAttribute

type JsxAttributeLike = tscast.JsxAttributeLike

type JsxAttributeList = tscast.JsxAttributeList

type JsxAttributeName = tscast.JsxAttributeName

type JsxAttributeNode = tscast.JsxAttributeNode

type JsxAttributeValue = tscast.JsxAttributeValue

type JsxAttributes = tscast.JsxAttributes

type JsxAttributesNode = tscast.JsxAttributesNode

type JsxChild = tscast.JsxChild

type JsxChildList = tscast.JsxChildList

type JsxClosingElement = tscast.JsxClosingElement

type JsxClosingElementNode = tscast.JsxClosingElementNode

type JsxClosingFragment = tscast.JsxClosingFragment

type JsxClosingFragmentNode = tscast.JsxClosingFragmentNode

type JsxElement = tscast.JsxElement

type JsxElementNode = tscast.JsxElementNode

type JsxExpression = tscast.JsxExpression

type JsxExpressionNode = tscast.JsxExpressionNode

type JsxFragment = tscast.JsxFragment

type JsxFragmentNode = tscast.JsxFragmentNode

type JsxNamespacedName = tscast.JsxNamespacedName

type JsxNamespacedNameNode = tscast.JsxNamespacedNameNode

type JsxOpeningElement = tscast.JsxOpeningElement

type JsxOpeningElementNode = tscast.JsxOpeningElementNode

type JsxOpeningFragment = tscast.JsxOpeningFragment

type JsxOpeningFragmentNode = tscast.JsxOpeningFragmentNode

type JsxOpeningLikeElement = tscast.JsxOpeningLikeElement

type JsxSelfClosingElement = tscast.JsxSelfClosingElement

type JsxSelfClosingElementNode = tscast.JsxSelfClosingElementNode

type JsxSpreadAttribute = tscast.JsxSpreadAttribute

type JsxSpreadAttributeNode = tscast.JsxSpreadAttributeNode

type JsxTagNameExpression = tscast.JsxTagNameExpression

type JsxText = tscast.JsxText

type JsxTextNode = tscast.JsxTextNode

type JsxTokenSyntaxKind = tscast.JsxTokenSyntaxKind

type KeywordExpression = tscast.KeywordExpression

type KeywordExpressionNode = tscast.KeywordExpressionNode

type KeywordExpressionSyntaxKind = tscast.KeywordExpressionSyntaxKind

type KeywordSyntaxKind = tscast.KeywordSyntaxKind

type KeywordTypeNode = tscast.KeywordTypeNode

type KeywordTypeNodeNode = tscast.KeywordTypeNodeNode

type KeywordTypeSyntaxKind = tscast.KeywordTypeSyntaxKind

type Kind = tscast.Kind

const KindAbstractKeyword = tscast.KindAbstractKeyword

const KindAccessorKeyword = tscast.KindAccessorKeyword

const KindAmpersandAmpersandEqualsToken = tscast.KindAmpersandAmpersandEqualsToken

const KindAmpersandAmpersandToken = tscast.KindAmpersandAmpersandToken

const KindAmpersandEqualsToken = tscast.KindAmpersandEqualsToken

const KindAmpersandToken = tscast.KindAmpersandToken

const KindAnyKeyword = tscast.KindAnyKeyword

const KindArrayBindingPattern = tscast.KindArrayBindingPattern

const KindArrayLiteralExpression = tscast.KindArrayLiteralExpression

const KindArrayType = tscast.KindArrayType

const KindArrowFunction = tscast.KindArrowFunction

const KindAsExpression = tscast.KindAsExpression

const KindAsKeyword = tscast.KindAsKeyword

const KindAssertKeyword = tscast.KindAssertKeyword

const KindAssertsKeyword = tscast.KindAssertsKeyword

const KindAsteriskAsteriskEqualsToken = tscast.KindAsteriskAsteriskEqualsToken

const KindAsteriskAsteriskToken = tscast.KindAsteriskAsteriskToken

const KindAsteriskEqualsToken = tscast.KindAsteriskEqualsToken

const KindAsteriskToken = tscast.KindAsteriskToken

const KindAsyncKeyword = tscast.KindAsyncKeyword

const KindAtToken = tscast.KindAtToken

const KindAwaitExpression = tscast.KindAwaitExpression

const KindAwaitKeyword = tscast.KindAwaitKeyword

const KindBacktickToken = tscast.KindBacktickToken

const KindBarBarEqualsToken = tscast.KindBarBarEqualsToken

const KindBarBarToken = tscast.KindBarBarToken

const KindBarEqualsToken = tscast.KindBarEqualsToken

const KindBarToken = tscast.KindBarToken

const KindBigIntKeyword = tscast.KindBigIntKeyword

const KindBigIntLiteral = tscast.KindBigIntLiteral

const KindBinaryExpression = tscast.KindBinaryExpression

const KindBindingElement = tscast.KindBindingElement

const KindBlock = tscast.KindBlock

const KindBooleanKeyword = tscast.KindBooleanKeyword

const KindBreakKeyword = tscast.KindBreakKeyword

const KindBreakStatement = tscast.KindBreakStatement

const KindCallExpression = tscast.KindCallExpression

const KindCallSignature = tscast.KindCallSignature

const KindCaretEqualsToken = tscast.KindCaretEqualsToken

const KindCaretToken = tscast.KindCaretToken

const KindCaseBlock = tscast.KindCaseBlock

const KindCaseClause = tscast.KindCaseClause

const KindCaseKeyword = tscast.KindCaseKeyword

const KindCatchClause = tscast.KindCatchClause

const KindCatchKeyword = tscast.KindCatchKeyword

const KindClassDeclaration = tscast.KindClassDeclaration

const KindClassExpression = tscast.KindClassExpression

const KindClassKeyword = tscast.KindClassKeyword

const KindClassStaticBlockDeclaration = tscast.KindClassStaticBlockDeclaration

const KindCloseBraceToken = tscast.KindCloseBraceToken

const KindCloseBracketToken = tscast.KindCloseBracketToken

const KindCloseParenToken = tscast.KindCloseParenToken

const KindColonToken = tscast.KindColonToken

const KindCommaToken = tscast.KindCommaToken

const KindComputedPropertyName = tscast.KindComputedPropertyName

const KindConditionalExpression = tscast.KindConditionalExpression

const KindConditionalType = tscast.KindConditionalType

const KindConflictMarkerTrivia = tscast.KindConflictMarkerTrivia

const KindConstKeyword = tscast.KindConstKeyword

const KindConstructSignature = tscast.KindConstructSignature

const KindConstructor = tscast.KindConstructor

const KindConstructorKeyword = tscast.KindConstructorKeyword

const KindConstructorType = tscast.KindConstructorType

const KindContinueKeyword = tscast.KindContinueKeyword

const KindContinueStatement = tscast.KindContinueStatement

const KindCount = tscast.KindCount

const KindDebuggerKeyword = tscast.KindDebuggerKeyword

const KindDebuggerStatement = tscast.KindDebuggerStatement

const KindDeclareKeyword = tscast.KindDeclareKeyword

const KindDecorator = tscast.KindDecorator

const KindDefaultClause = tscast.KindDefaultClause

const KindDefaultKeyword = tscast.KindDefaultKeyword

const KindDeferKeyword = tscast.KindDeferKeyword

const KindDeleteExpression = tscast.KindDeleteExpression

const KindDeleteKeyword = tscast.KindDeleteKeyword

const KindDoKeyword = tscast.KindDoKeyword

const KindDoStatement = tscast.KindDoStatement

const KindDotDotDotToken = tscast.KindDotDotDotToken

const KindDotToken = tscast.KindDotToken

const KindElementAccessExpression = tscast.KindElementAccessExpression

const KindElseKeyword = tscast.KindElseKeyword

const KindEmptyStatement = tscast.KindEmptyStatement

const KindEndOfFile = tscast.KindEndOfFile

const KindEnumDeclaration = tscast.KindEnumDeclaration

const KindEnumKeyword = tscast.KindEnumKeyword

const KindEnumMember = tscast.KindEnumMember

const KindEqualsEqualsEqualsToken = tscast.KindEqualsEqualsEqualsToken

const KindEqualsEqualsToken = tscast.KindEqualsEqualsToken

const KindEqualsGreaterThanToken = tscast.KindEqualsGreaterThanToken

const KindEqualsToken = tscast.KindEqualsToken

const KindExclamationEqualsEqualsToken = tscast.KindExclamationEqualsEqualsToken

const KindExclamationEqualsToken = tscast.KindExclamationEqualsToken

const KindExclamationToken = tscast.KindExclamationToken

const KindExportAssignment = tscast.KindExportAssignment

const KindExportDeclaration = tscast.KindExportDeclaration

const KindExportKeyword = tscast.KindExportKeyword

const KindExportSpecifier = tscast.KindExportSpecifier

const KindExpressionStatement = tscast.KindExpressionStatement

const KindExpressionWithTypeArguments = tscast.KindExpressionWithTypeArguments

const KindExtendsKeyword = tscast.KindExtendsKeyword

const KindExternalModuleReference = tscast.KindExternalModuleReference

const KindFalseKeyword = tscast.KindFalseKeyword

const KindFinallyKeyword = tscast.KindFinallyKeyword

const KindFirstAssignment = tscast.KindFirstAssignment

const KindFirstBinaryOperator = tscast.KindFirstBinaryOperator

const KindFirstCompoundAssignment = tscast.KindFirstCompoundAssignment

const KindFirstContextualKeyword = tscast.KindFirstContextualKeyword

const KindFirstFutureReservedWord = tscast.KindFirstFutureReservedWord

const KindFirstJSDocNode = tscast.KindFirstJSDocNode

const KindFirstJSDocTagNode = tscast.KindFirstJSDocTagNode

const KindFirstKeyword = tscast.KindFirstKeyword

const KindFirstLiteralToken = tscast.KindFirstLiteralToken

const KindFirstNode = tscast.KindFirstNode

const KindFirstPunctuation = tscast.KindFirstPunctuation

const KindFirstReservedWord = tscast.KindFirstReservedWord

const KindFirstStatement = tscast.KindFirstStatement

const KindFirstTemplateToken = tscast.KindFirstTemplateToken

const KindFirstToken = tscast.KindFirstToken

const KindFirstTriviaToken = tscast.KindFirstTriviaToken

const KindFirstTypeNode = tscast.KindFirstTypeNode

const KindForInStatement = tscast.KindForInStatement

const KindForKeyword = tscast.KindForKeyword

const KindForOfStatement = tscast.KindForOfStatement

const KindForStatement = tscast.KindForStatement

const KindFromKeyword = tscast.KindFromKeyword

const KindFunctionDeclaration = tscast.KindFunctionDeclaration

const KindFunctionExpression = tscast.KindFunctionExpression

const KindFunctionKeyword = tscast.KindFunctionKeyword

const KindFunctionType = tscast.KindFunctionType

const KindGetAccessor = tscast.KindGetAccessor

const KindGetKeyword = tscast.KindGetKeyword

const KindGlobalKeyword = tscast.KindGlobalKeyword

const KindGreaterThanEqualsToken = tscast.KindGreaterThanEqualsToken

const KindGreaterThanGreaterThanEqualsToken = tscast.KindGreaterThanGreaterThanEqualsToken

const KindGreaterThanGreaterThanGreaterThanEqualsToken = tscast.KindGreaterThanGreaterThanGreaterThanEqualsToken

const KindGreaterThanGreaterThanGreaterThanToken = tscast.KindGreaterThanGreaterThanGreaterThanToken

const KindGreaterThanGreaterThanToken = tscast.KindGreaterThanGreaterThanToken

const KindGreaterThanToken = tscast.KindGreaterThanToken

const KindHashToken = tscast.KindHashToken

const KindHeritageClause = tscast.KindHeritageClause

const KindIdentifier = tscast.KindIdentifier

const KindIfKeyword = tscast.KindIfKeyword

const KindIfStatement = tscast.KindIfStatement

const KindImmediateKeyword = tscast.KindImmediateKeyword

const KindImplementsKeyword = tscast.KindImplementsKeyword

const KindImportAttribute = tscast.KindImportAttribute

const KindImportAttributes = tscast.KindImportAttributes

const KindImportClause = tscast.KindImportClause

const KindImportDeclaration = tscast.KindImportDeclaration

const KindImportEqualsDeclaration = tscast.KindImportEqualsDeclaration

const KindImportKeyword = tscast.KindImportKeyword

const KindImportSpecifier = tscast.KindImportSpecifier

const KindImportType = tscast.KindImportType

const KindInKeyword = tscast.KindInKeyword

const KindIndexSignature = tscast.KindIndexSignature

const KindIndexedAccessType = tscast.KindIndexedAccessType

const KindInferKeyword = tscast.KindInferKeyword

const KindInferType = tscast.KindInferType

const KindInstanceOfKeyword = tscast.KindInstanceOfKeyword

const KindInterfaceDeclaration = tscast.KindInterfaceDeclaration

const KindInterfaceKeyword = tscast.KindInterfaceKeyword

const KindIntersectionType = tscast.KindIntersectionType

const KindIntrinsicKeyword = tscast.KindIntrinsicKeyword

const KindIsKeyword = tscast.KindIsKeyword

const KindJSDoc = tscast.KindJSDoc

const KindJSDocAllType = tscast.KindJSDocAllType

const KindJSDocAugmentsTag = tscast.KindJSDocAugmentsTag

const KindJSDocCallbackTag = tscast.KindJSDocCallbackTag

const KindJSDocCommentTextToken = tscast.KindJSDocCommentTextToken

const KindJSDocDeprecatedTag = tscast.KindJSDocDeprecatedTag

const KindJSDocImplementsTag = tscast.KindJSDocImplementsTag

const KindJSDocImportTag = tscast.KindJSDocImportTag

const KindJSDocLink = tscast.KindJSDocLink

const KindJSDocLinkCode = tscast.KindJSDocLinkCode

const KindJSDocLinkPlain = tscast.KindJSDocLinkPlain

const KindJSDocNameReference = tscast.KindJSDocNameReference

const KindJSDocNonNullableType = tscast.KindJSDocNonNullableType

const KindJSDocNullableType = tscast.KindJSDocNullableType

const KindJSDocOptionalType = tscast.KindJSDocOptionalType

const KindJSDocOverloadTag = tscast.KindJSDocOverloadTag

const KindJSDocOverrideTag = tscast.KindJSDocOverrideTag

const KindJSDocParameterTag = tscast.KindJSDocParameterTag

const KindJSDocPrivateTag = tscast.KindJSDocPrivateTag

const KindJSDocPropertyTag = tscast.KindJSDocPropertyTag

const KindJSDocProtectedTag = tscast.KindJSDocProtectedTag

const KindJSDocPublicTag = tscast.KindJSDocPublicTag

const KindJSDocReadonlyTag = tscast.KindJSDocReadonlyTag

const KindJSDocReturnTag = tscast.KindJSDocReturnTag

const KindJSDocSatisfiesTag = tscast.KindJSDocSatisfiesTag

const KindJSDocSeeTag = tscast.KindJSDocSeeTag

const KindJSDocSignature = tscast.KindJSDocSignature

const KindJSDocTemplateTag = tscast.KindJSDocTemplateTag

const KindJSDocText = tscast.KindJSDocText

const KindJSDocThisTag = tscast.KindJSDocThisTag

const KindJSDocThrowsTag = tscast.KindJSDocThrowsTag

const KindJSDocTypeExpression = tscast.KindJSDocTypeExpression

const KindJSDocTypeLiteral = tscast.KindJSDocTypeLiteral

const KindJSDocTypeTag = tscast.KindJSDocTypeTag

const KindJSDocTypedefTag = tscast.KindJSDocTypedefTag

const KindJSDocUnknownTag = tscast.KindJSDocUnknownTag

const KindJSDocVariadicType = tscast.KindJSDocVariadicType

const KindJSImportDeclaration = tscast.KindJSImportDeclaration

const KindJSTypeAliasDeclaration = tscast.KindJSTypeAliasDeclaration

const KindJsxAttribute = tscast.KindJsxAttribute

const KindJsxAttributes = tscast.KindJsxAttributes

const KindJsxClosingElement = tscast.KindJsxClosingElement

const KindJsxClosingFragment = tscast.KindJsxClosingFragment

const KindJsxElement = tscast.KindJsxElement

const KindJsxExpression = tscast.KindJsxExpression

const KindJsxFragment = tscast.KindJsxFragment

const KindJsxNamespacedName = tscast.KindJsxNamespacedName

const KindJsxOpeningElement = tscast.KindJsxOpeningElement

const KindJsxOpeningFragment = tscast.KindJsxOpeningFragment

const KindJsxSelfClosingElement = tscast.KindJsxSelfClosingElement

const KindJsxSpreadAttribute = tscast.KindJsxSpreadAttribute

const KindJsxText = tscast.KindJsxText

const KindJsxTextAllWhiteSpaces = tscast.KindJsxTextAllWhiteSpaces

const KindKeyOfKeyword = tscast.KindKeyOfKeyword

const KindLabeledStatement = tscast.KindLabeledStatement

const KindLastAssignment = tscast.KindLastAssignment

const KindLastBinaryOperator = tscast.KindLastBinaryOperator

const KindLastCompoundAssignment = tscast.KindLastCompoundAssignment

const KindLastContextualKeyword = tscast.KindLastContextualKeyword

const KindLastFutureReservedWord = tscast.KindLastFutureReservedWord

const KindLastJSDocNode = tscast.KindLastJSDocNode

const KindLastJSDocTagNode = tscast.KindLastJSDocTagNode

const KindLastKeyword = tscast.KindLastKeyword

const KindLastLiteralToken = tscast.KindLastLiteralToken

const KindLastPunctuation = tscast.KindLastPunctuation

const KindLastReservedWord = tscast.KindLastReservedWord

const KindLastStatement = tscast.KindLastStatement

const KindLastTemplateToken = tscast.KindLastTemplateToken

const KindLastToken = tscast.KindLastToken

const KindLastTriviaToken = tscast.KindLastTriviaToken

const KindLastTypeNode = tscast.KindLastTypeNode

const KindLastUnaryOperator = tscast.KindLastUnaryOperator

const KindLessThanEqualsToken = tscast.KindLessThanEqualsToken

const KindLessThanLessThanEqualsToken = tscast.KindLessThanLessThanEqualsToken

const KindLessThanLessThanToken = tscast.KindLessThanLessThanToken

const KindLessThanSlashToken = tscast.KindLessThanSlashToken

const KindLessThanToken = tscast.KindLessThanToken

const KindLetKeyword = tscast.KindLetKeyword

const KindLiteralType = tscast.KindLiteralType

const KindMappedType = tscast.KindMappedType

const KindMetaProperty = tscast.KindMetaProperty

const KindMethodDeclaration = tscast.KindMethodDeclaration

const KindMethodSignature = tscast.KindMethodSignature

const KindMinusEqualsToken = tscast.KindMinusEqualsToken

const KindMinusMinusToken = tscast.KindMinusMinusToken

const KindMinusToken = tscast.KindMinusToken

const KindMissingDeclaration = tscast.KindMissingDeclaration

const KindModuleBlock = tscast.KindModuleBlock

const KindModuleDeclaration = tscast.KindModuleDeclaration

const KindModuleKeyword = tscast.KindModuleKeyword

const KindMultiLineCommentTrivia = tscast.KindMultiLineCommentTrivia

const KindNamedExports = tscast.KindNamedExports

const KindNamedImports = tscast.KindNamedImports

const KindNamedTupleMember = tscast.KindNamedTupleMember

const KindNamespaceExport = tscast.KindNamespaceExport

const KindNamespaceExportDeclaration = tscast.KindNamespaceExportDeclaration

const KindNamespaceImport = tscast.KindNamespaceImport

const KindNamespaceKeyword = tscast.KindNamespaceKeyword

const KindNeverKeyword = tscast.KindNeverKeyword

const KindNewExpression = tscast.KindNewExpression

const KindNewKeyword = tscast.KindNewKeyword

const KindNewLineTrivia = tscast.KindNewLineTrivia

const KindNoSubstitutionTemplateLiteral = tscast.KindNoSubstitutionTemplateLiteral

const KindNonNullExpression = tscast.KindNonNullExpression

const KindNonTextFileMarkerTrivia = tscast.KindNonTextFileMarkerTrivia

const KindNotEmittedStatement = tscast.KindNotEmittedStatement

const KindNotEmittedTypeElement = tscast.KindNotEmittedTypeElement

const KindNullKeyword = tscast.KindNullKeyword

const KindNumberKeyword = tscast.KindNumberKeyword

const KindNumericLiteral = tscast.KindNumericLiteral

const KindObjectBindingPattern = tscast.KindObjectBindingPattern

const KindObjectKeyword = tscast.KindObjectKeyword

const KindObjectLiteralExpression = tscast.KindObjectLiteralExpression

const KindOfKeyword = tscast.KindOfKeyword

const KindOmittedExpression = tscast.KindOmittedExpression

const KindOpenBraceToken = tscast.KindOpenBraceToken

const KindOpenBracketToken = tscast.KindOpenBracketToken

const KindOpenParenToken = tscast.KindOpenParenToken

const KindOptionalType = tscast.KindOptionalType

const KindOutKeyword = tscast.KindOutKeyword

const KindOverrideKeyword = tscast.KindOverrideKeyword

const KindPackageKeyword = tscast.KindPackageKeyword

const KindParameter = tscast.KindParameter

const KindParenthesizedExpression = tscast.KindParenthesizedExpression

const KindParenthesizedType = tscast.KindParenthesizedType

const KindPartiallyEmittedExpression = tscast.KindPartiallyEmittedExpression

const KindPercentEqualsToken = tscast.KindPercentEqualsToken

const KindPercentToken = tscast.KindPercentToken

const KindPlusEqualsToken = tscast.KindPlusEqualsToken

const KindPlusPlusToken = tscast.KindPlusPlusToken

const KindPlusToken = tscast.KindPlusToken

const KindPostfixUnaryExpression = tscast.KindPostfixUnaryExpression

const KindPrefixUnaryExpression = tscast.KindPrefixUnaryExpression

const KindPrivateIdentifier = tscast.KindPrivateIdentifier

const KindPrivateKeyword = tscast.KindPrivateKeyword

const KindPropertyAccessExpression = tscast.KindPropertyAccessExpression

const KindPropertyAssignment = tscast.KindPropertyAssignment

const KindPropertyDeclaration = tscast.KindPropertyDeclaration

const KindPropertySignature = tscast.KindPropertySignature

const KindProtectedKeyword = tscast.KindProtectedKeyword

const KindPublicKeyword = tscast.KindPublicKeyword

const KindQualifiedName = tscast.KindQualifiedName

const KindQuestionDotToken = tscast.KindQuestionDotToken

const KindQuestionQuestionEqualsToken = tscast.KindQuestionQuestionEqualsToken

const KindQuestionQuestionToken = tscast.KindQuestionQuestionToken

const KindQuestionToken = tscast.KindQuestionToken

const KindReadonlyKeyword = tscast.KindReadonlyKeyword

const KindRegularExpressionLiteral = tscast.KindRegularExpressionLiteral

const KindRequireKeyword = tscast.KindRequireKeyword

const KindRestType = tscast.KindRestType

const KindReturnKeyword = tscast.KindReturnKeyword

const KindReturnStatement = tscast.KindReturnStatement

const KindSatisfiesExpression = tscast.KindSatisfiesExpression

const KindSatisfiesKeyword = tscast.KindSatisfiesKeyword

const KindSemicolonClassElement = tscast.KindSemicolonClassElement

const KindSemicolonToken = tscast.KindSemicolonToken

const KindSetAccessor = tscast.KindSetAccessor

const KindSetKeyword = tscast.KindSetKeyword

const KindShorthandPropertyAssignment = tscast.KindShorthandPropertyAssignment

const KindSingleLineCommentTrivia = tscast.KindSingleLineCommentTrivia

const KindSlashEqualsToken = tscast.KindSlashEqualsToken

const KindSlashToken = tscast.KindSlashToken

const KindSourceFile = tscast.KindSourceFile

const KindSourceKeyword = tscast.KindSourceKeyword

const KindSpreadAssignment = tscast.KindSpreadAssignment

const KindSpreadElement = tscast.KindSpreadElement

const KindStaticKeyword = tscast.KindStaticKeyword

const KindStringKeyword = tscast.KindStringKeyword

const KindStringLiteral = tscast.KindStringLiteral

const KindSuperKeyword = tscast.KindSuperKeyword

const KindSwitchKeyword = tscast.KindSwitchKeyword

const KindSwitchStatement = tscast.KindSwitchStatement

const KindSymbolKeyword = tscast.KindSymbolKeyword

const KindSyntaxList = tscast.KindSyntaxList

const KindSyntheticExpression = tscast.KindSyntheticExpression

const KindSyntheticReferenceExpression = tscast.KindSyntheticReferenceExpression

const KindTaggedTemplateExpression = tscast.KindTaggedTemplateExpression

const KindTemplateExpression = tscast.KindTemplateExpression

const KindTemplateHead = tscast.KindTemplateHead

const KindTemplateLiteralType = tscast.KindTemplateLiteralType

const KindTemplateLiteralTypeSpan = tscast.KindTemplateLiteralTypeSpan

const KindTemplateMiddle = tscast.KindTemplateMiddle

const KindTemplateSpan = tscast.KindTemplateSpan

const KindTemplateTail = tscast.KindTemplateTail

const KindThisKeyword = tscast.KindThisKeyword

const KindThisType = tscast.KindThisType

const KindThrowKeyword = tscast.KindThrowKeyword

const KindThrowStatement = tscast.KindThrowStatement

const KindTildeToken = tscast.KindTildeToken

const KindTrueKeyword = tscast.KindTrueKeyword

const KindTryKeyword = tscast.KindTryKeyword

const KindTryStatement = tscast.KindTryStatement

const KindTupleType = tscast.KindTupleType

const KindTypeAliasDeclaration = tscast.KindTypeAliasDeclaration

const KindTypeAssertionExpression = tscast.KindTypeAssertionExpression

const KindTypeKeyword = tscast.KindTypeKeyword

const KindTypeLiteral = tscast.KindTypeLiteral

const KindTypeOfExpression = tscast.KindTypeOfExpression

const KindTypeOfKeyword = tscast.KindTypeOfKeyword

const KindTypeOperator = tscast.KindTypeOperator

const KindTypeParameter = tscast.KindTypeParameter

const KindTypePredicate = tscast.KindTypePredicate

const KindTypeQuery = tscast.KindTypeQuery

const KindTypeReference = tscast.KindTypeReference

const KindUndefinedKeyword = tscast.KindUndefinedKeyword

const KindUnionType = tscast.KindUnionType

const KindUniqueKeyword = tscast.KindUniqueKeyword

const KindUnknown = tscast.KindUnknown

const KindUnknownKeyword = tscast.KindUnknownKeyword

const KindUsingKeyword = tscast.KindUsingKeyword

const KindVarKeyword = tscast.KindVarKeyword

const KindVariableDeclaration = tscast.KindVariableDeclaration

const KindVariableDeclarationList = tscast.KindVariableDeclarationList

const KindVariableStatement = tscast.KindVariableStatement

const KindVoidExpression = tscast.KindVoidExpression

const KindVoidKeyword = tscast.KindVoidKeyword

const KindWhileKeyword = tscast.KindWhileKeyword

const KindWhileStatement = tscast.KindWhileStatement

const KindWhitespaceTrivia = tscast.KindWhitespaceTrivia

const KindWithKeyword = tscast.KindWithKeyword

const KindWithStatement = tscast.KindWithStatement

const KindYieldExpression = tscast.KindYieldExpression

const KindYieldKeyword = tscast.KindYieldKeyword

type LabeledStatement = tscast.LabeledStatement

type LabeledStatementNode = tscast.LabeledStatementNode

type LeftHandSideExpression = tscast.LeftHandSideExpression

type LeftHandSideExpressionBase = tscast.LeftHandSideExpressionBase

type LiteralExpression = tscast.LiteralExpression

type LiteralExpressionBase = tscast.LiteralExpressionBase

type LiteralLikeNode = tscast.LiteralLikeNode

type LiteralLikeNodeBase = tscast.LiteralLikeNodeBase

type LiteralSyntaxKind = tscast.LiteralSyntaxKind

type LiteralToken = tscast.LiteralToken

type LiteralTypeNode = tscast.LiteralTypeNode

type LiteralTypeNodeNode = tscast.LiteralTypeNodeNode

type LocalsContainerBase = tscast.LocalsContainerBase

type LogicalOperator = tscast.LogicalOperator

type LogicalOperatorOrHigher = tscast.LogicalOperatorOrHigher

type LogicalOrCoalescingAssignmentOperator = tscast.LogicalOrCoalescingAssignmentOperator

type MappedTypeNode = tscast.MappedTypeNode

type MappedTypeNodeNode = tscast.MappedTypeNodeNode

type MemberExpressionBase = tscast.MemberExpressionBase

type MemberName = tscast.MemberName

type MetaProperty = tscast.MetaProperty

type MetaPropertyNode = tscast.MetaPropertyNode

type MethodDeclaration = tscast.MethodDeclaration

type MethodDeclarationNode = tscast.MethodDeclarationNode

type MethodSignatureDeclaration = tscast.MethodSignatureDeclaration

type MethodSignatureDeclarationNode = tscast.MethodSignatureDeclarationNode

type MinusToken = tscast.MinusToken

type MissingDeclaration = tscast.MissingDeclaration

type MissingDeclarationNode = tscast.MissingDeclarationNode

type Modifier = tscast.Modifier

type ModifierFlags = tscast.ModifierFlags

const ModifierFlagsAbstract = tscast.ModifierFlagsAbstract

const ModifierFlagsAccessibilityModifier = tscast.ModifierFlagsAccessibilityModifier

const ModifierFlagsAccessor = tscast.ModifierFlagsAccessor

const ModifierFlagsAll = tscast.ModifierFlagsAll

const ModifierFlagsAmbient = tscast.ModifierFlagsAmbient

const ModifierFlagsAsync = tscast.ModifierFlagsAsync

const ModifierFlagsConst = tscast.ModifierFlagsConst

const ModifierFlagsDecorator = tscast.ModifierFlagsDecorator

const ModifierFlagsDefault = tscast.ModifierFlagsDefault

const ModifierFlagsDeprecated = tscast.ModifierFlagsDeprecated

const ModifierFlagsExport = tscast.ModifierFlagsExport

const ModifierFlagsExportDefault = tscast.ModifierFlagsExportDefault

const ModifierFlagsHasComputedFlags = tscast.ModifierFlagsHasComputedFlags

const ModifierFlagsHasComputedJSDocModifiers = tscast.ModifierFlagsHasComputedJSDocModifiers

const ModifierFlagsIn = tscast.ModifierFlagsIn

const ModifierFlagsJSDocCacheOnlyModifiers = tscast.ModifierFlagsJSDocCacheOnlyModifiers

const ModifierFlagsJSDocOnlyModifiers = tscast.ModifierFlagsJSDocOnlyModifiers

const ModifierFlagsJSDocOverride = tscast.ModifierFlagsJSDocOverride

const ModifierFlagsJSDocPrivate = tscast.ModifierFlagsJSDocPrivate

const ModifierFlagsJSDocProtected = tscast.ModifierFlagsJSDocProtected

const ModifierFlagsJSDocPublic = tscast.ModifierFlagsJSDocPublic

const ModifierFlagsJSDocReadonly = tscast.ModifierFlagsJSDocReadonly

const ModifierFlagsJavaScript = tscast.ModifierFlagsJavaScript

const ModifierFlagsModifier = tscast.ModifierFlagsModifier

const ModifierFlagsNonCacheOnlyModifiers = tscast.ModifierFlagsNonCacheOnlyModifiers

const ModifierFlagsNonPublicAccessibilityModifier = tscast.ModifierFlagsNonPublicAccessibilityModifier

const ModifierFlagsNone = tscast.ModifierFlagsNone

const ModifierFlagsOut = tscast.ModifierFlagsOut

const ModifierFlagsOverride = tscast.ModifierFlagsOverride

const ModifierFlagsParameterPropertyModifier = tscast.ModifierFlagsParameterPropertyModifier

const ModifierFlagsPrivate = tscast.ModifierFlagsPrivate

const ModifierFlagsProtected = tscast.ModifierFlagsProtected

const ModifierFlagsPublic = tscast.ModifierFlagsPublic

const ModifierFlagsReadonly = tscast.ModifierFlagsReadonly

const ModifierFlagsStatic = tscast.ModifierFlagsStatic

const ModifierFlagsSyntacticModifiers = tscast.ModifierFlagsSyntacticModifiers

const ModifierFlagsSyntacticOnlyModifiers = tscast.ModifierFlagsSyntacticOnlyModifiers

const ModifierFlagsSyntacticOrJSDocModifiers = tscast.ModifierFlagsSyntacticOrJSDocModifiers

const ModifierFlagsTypeScriptModifier = tscast.ModifierFlagsTypeScriptModifier

type ModifierLike = tscast.ModifierLike

type ModifierList = tscast.ModifierList

type ModifierSyntaxKind = tscast.ModifierSyntaxKind

type ModifiersBase = tscast.ModifiersBase

type ModuleBlock = tscast.ModuleBlock

type ModuleBlockNode = tscast.ModuleBlockNode

type ModuleBody = tscast.ModuleBody

type ModuleDeclaration = tscast.ModuleDeclaration

type ModuleDeclarationNode = tscast.ModuleDeclarationNode

type ModuleExportName = tscast.ModuleExportName

type ModuleInstanceState = tscast.ModuleInstanceState

type ModuleName = tscast.ModuleName

type ModuleReference = tscast.ModuleReference

type MultiplicativeOperator = tscast.MultiplicativeOperator

type MultiplicativeOperatorOrHigher = tscast.MultiplicativeOperatorOrHigher

type MutableNode = tscast.MutableNode

type NamedExportBindings = tscast.NamedExportBindings

type NamedExports = tscast.NamedExports

type NamedExportsNode = tscast.NamedExportsNode

type NamedImportBindings = tscast.NamedImportBindings

type NamedImports = tscast.NamedImports

type NamedImportsNode = tscast.NamedImportsNode

type NamedImportsOrExports = tscast.NamedImportsOrExports

type NamedMember = tscast.NamedMember

type NamedMemberBase = tscast.NamedMemberBase

type NamedTupleMember = tscast.NamedTupleMember

type NamedTupleMemberNode = tscast.NamedTupleMemberNode

type NamespaceExport = tscast.NamespaceExport

type NamespaceExportDeclaration = tscast.NamespaceExportDeclaration

type NamespaceExportDeclarationNode = tscast.NamespaceExportDeclarationNode

type NamespaceExportNode = tscast.NamespaceExportNode

type NamespaceImport = tscast.NamespaceImport

type NamespaceImportNode = tscast.NamespaceImportNode

type NewExpression = tscast.NewExpression

type NewExpressionNode = tscast.NewExpressionNode

func NewNodeFactory(p0 tscast.NodeFactoryHooks) *tscast.NodeFactory {
  return tscast.NewNodeFactory(p0)
}

func NewNodeVisitor(p0 func(*tscast.Node) *tscast.Node, p1 *tscast.NodeFactory, p2 tscast.NodeVisitorHooks) *tscast.NodeVisitor {
  return tscast.NewNodeVisitor(p0, p1, p2)
}

func NewSourceFileDataKey[T any]() *tscast.SourceFileDataKey[T] {
  return tscast.NewSourceFileDataKey[T]()
}

type NoSubstitutionTemplateLiteral = tscast.NoSubstitutionTemplateLiteral

type NoSubstitutionTemplateLiteralNode = tscast.NoSubstitutionTemplateLiteralNode

type Node = tscast.Node

type NodeBase = tscast.NodeBase

type NodeBody = tscast.NodeBody

type NodeDefault = tscast.NodeDefault

type NodeFactory = tscast.NodeFactory

type NodeFactoryCoercible = tscast.NodeFactoryCoercible

type NodeFactoryHooks = tscast.NodeFactoryHooks

type NodeFlags = tscast.NodeFlags

const NodeFlagsAmbient = tscast.NodeFlagsAmbient

const NodeFlagsAwaitContext = tscast.NodeFlagsAwaitContext

const NodeFlagsAwaitUsing = tscast.NodeFlagsAwaitUsing

const NodeFlagsBlockScoped = tscast.NodeFlagsBlockScoped

const NodeFlagsConst = tscast.NodeFlagsConst

const NodeFlagsConstant = tscast.NodeFlagsConstant

const NodeFlagsContainsThis = tscast.NodeFlagsContainsThis

const NodeFlagsContextFlags = tscast.NodeFlagsContextFlags

const NodeFlagsDecoratorContext = tscast.NodeFlagsDecoratorContext

const NodeFlagsDisallowConditionalTypesContext = tscast.NodeFlagsDisallowConditionalTypesContext

const NodeFlagsDisallowInContext = tscast.NodeFlagsDisallowInContext

const NodeFlagsExportContext = tscast.NodeFlagsExportContext

const NodeFlagsHasAsyncFunctions = tscast.NodeFlagsHasAsyncFunctions

const NodeFlagsHasExplicitReturn = tscast.NodeFlagsHasExplicitReturn

const NodeFlagsHasImplicitReturn = tscast.NodeFlagsHasImplicitReturn

const NodeFlagsHasJSDoc = tscast.NodeFlagsHasJSDoc

const NodeFlagsIdentifierHasExtendedUnicodeEscape = tscast.NodeFlagsIdentifierHasExtendedUnicodeEscape

const NodeFlagsIdentifierIsInJSDocNamespace = tscast.NodeFlagsIdentifierIsInJSDocNamespace

const NodeFlagsInWithStatement = tscast.NodeFlagsInWithStatement

const NodeFlagsJSDoc = tscast.NodeFlagsJSDoc

const NodeFlagsJavaScriptFile = tscast.NodeFlagsJavaScriptFile

const NodeFlagsJsonFile = tscast.NodeFlagsJsonFile

const NodeFlagsLet = tscast.NodeFlagsLet

const NodeFlagsNestedNamespace = tscast.NodeFlagsNestedNamespace

const NodeFlagsNone = tscast.NodeFlagsNone

const NodeFlagsOptionalChain = tscast.NodeFlagsOptionalChain

const NodeFlagsPermanentlySetIncrementalFlags = tscast.NodeFlagsPermanentlySetIncrementalFlags

const NodeFlagsPossiblyContainsDeprecatedTag = tscast.NodeFlagsPossiblyContainsDeprecatedTag

const NodeFlagsPossiblyContainsDynamicImport = tscast.NodeFlagsPossiblyContainsDynamicImport

const NodeFlagsPossiblyContainsImportMeta = tscast.NodeFlagsPossiblyContainsImportMeta

const NodeFlagsReachabilityAndEmitFlags = tscast.NodeFlagsReachabilityAndEmitFlags

const NodeFlagsReachabilityCheckFlags = tscast.NodeFlagsReachabilityCheckFlags

const NodeFlagsReparsed = tscast.NodeFlagsReparsed

const NodeFlagsReparserTransformedLiteral = tscast.NodeFlagsReparserTransformedLiteral

const NodeFlagsSynthesized = tscast.NodeFlagsSynthesized

const NodeFlagsThisNodeHasError = tscast.NodeFlagsThisNodeHasError

const NodeFlagsThisNodeOrAnySubNodesHasError = tscast.NodeFlagsThisNodeOrAnySubNodesHasError

const NodeFlagsTypeExcludesFlags = tscast.NodeFlagsTypeExcludesFlags

const NodeFlagsUnreachable = tscast.NodeFlagsUnreachable

const NodeFlagsUsing = tscast.NodeFlagsUsing

const NodeFlagsYieldContext = tscast.NodeFlagsYieldContext

type NodeId = tscast.NodeId

type NodeList = tscast.NodeList

func NodeText(p0 *tscast.Node) string {
  return tscast.NodeText(p0)
}

type NodeVisitor = tscast.NodeVisitor

type NodeVisitorHooks = tscast.NodeVisitorHooks

type NodeWithTypeArgumentsBase = tscast.NodeWithTypeArgumentsBase

type NonNullExpression = tscast.NonNullExpression

type NonNullExpressionNode = tscast.NonNullExpressionNode

type NotEmittedStatement = tscast.NotEmittedStatement

type NotEmittedStatementNode = tscast.NotEmittedStatementNode

type NotEmittedTypeElement = tscast.NotEmittedTypeElement

type NotEmittedTypeElementNode = tscast.NotEmittedTypeElementNode

type NullLiteral = tscast.NullLiteral

type NumericLiteral = tscast.NumericLiteral

type NumericLiteralNode = tscast.NumericLiteralNode

type NumericOrStringLikeLiteral = tscast.NumericOrStringLikeLiteral

type ObjectDestructuringAssignment = tscast.ObjectDestructuringAssignment

type ObjectLiteralElement = tscast.ObjectLiteralElement

type ObjectLiteralElementBase = tscast.ObjectLiteralElementBase

type ObjectLiteralElementLike = tscast.ObjectLiteralElementLike

type ObjectLiteralExpression = tscast.ObjectLiteralExpression

type ObjectLiteralExpressionNode = tscast.ObjectLiteralExpressionNode

type ObjectLiteralLike = tscast.ObjectLiteralLike

type ObjectLiteralLikeNode = tscast.ObjectLiteralLikeNode

type ObjectTypeDeclaration = tscast.ObjectTypeDeclaration

type OmittedExpression = tscast.OmittedExpression

type OmittedExpressionNode = tscast.OmittedExpressionNode

type OperatorPrecedence = tscast.OperatorPrecedence

const OperatorPrecedenceAdditive = tscast.OperatorPrecedenceAdditive

const OperatorPrecedenceAssignment = tscast.OperatorPrecedenceAssignment

const OperatorPrecedenceBitwiseAND = tscast.OperatorPrecedenceBitwiseAND

const OperatorPrecedenceBitwiseOR = tscast.OperatorPrecedenceBitwiseOR

const OperatorPrecedenceBitwiseXOR = tscast.OperatorPrecedenceBitwiseXOR

const OperatorPrecedenceCoalesce = tscast.OperatorPrecedenceCoalesce

const OperatorPrecedenceComma = tscast.OperatorPrecedenceComma

const OperatorPrecedenceConditional = tscast.OperatorPrecedenceConditional

const OperatorPrecedenceDisallowComma = tscast.OperatorPrecedenceDisallowComma

const OperatorPrecedenceEquality = tscast.OperatorPrecedenceEquality

const OperatorPrecedenceExponentiation = tscast.OperatorPrecedenceExponentiation

type OperatorPrecedenceFlags = tscast.OperatorPrecedenceFlags

const OperatorPrecedenceHighest = tscast.OperatorPrecedenceHighest

const OperatorPrecedenceInvalid = tscast.OperatorPrecedenceInvalid

const OperatorPrecedenceLeftHandSide = tscast.OperatorPrecedenceLeftHandSide

const OperatorPrecedenceLogicalAND = tscast.OperatorPrecedenceLogicalAND

const OperatorPrecedenceLogicalOR = tscast.OperatorPrecedenceLogicalOR

const OperatorPrecedenceLowest = tscast.OperatorPrecedenceLowest

const OperatorPrecedenceMember = tscast.OperatorPrecedenceMember

const OperatorPrecedenceMultiplicative = tscast.OperatorPrecedenceMultiplicative

const OperatorPrecedenceOptionalChain = tscast.OperatorPrecedenceOptionalChain

const OperatorPrecedenceParentheses = tscast.OperatorPrecedenceParentheses

const OperatorPrecedencePrimary = tscast.OperatorPrecedencePrimary

const OperatorPrecedenceRelational = tscast.OperatorPrecedenceRelational

const OperatorPrecedenceShift = tscast.OperatorPrecedenceShift

const OperatorPrecedenceSpread = tscast.OperatorPrecedenceSpread

const OperatorPrecedenceUnary = tscast.OperatorPrecedenceUnary

const OperatorPrecedenceUpdate = tscast.OperatorPrecedenceUpdate

const OperatorPrecedenceYield = tscast.OperatorPrecedenceYield

type OptionalTypeNode = tscast.OptionalTypeNode

type OptionalTypeNodeNode = tscast.OptionalTypeNodeNode

type OutKeyword = tscast.OutKeyword

type OuterExpressionKinds = tscast.OuterExpressionKinds

type OverrideKeyword = tscast.OverrideKeyword

type ParameterDeclaration = tscast.ParameterDeclaration

type ParameterDeclarationNode = tscast.ParameterDeclarationNode

type ParameterList = tscast.ParameterList

type ParenthesizedExpression = tscast.ParenthesizedExpression

type ParenthesizedExpressionNode = tscast.ParenthesizedExpressionNode

type ParenthesizedTypeNode = tscast.ParenthesizedTypeNode

type ParenthesizedTypeNodeNode = tscast.ParenthesizedTypeNodeNode

type PartiallyEmittedExpression = tscast.PartiallyEmittedExpression

type PartiallyEmittedExpressionNode = tscast.PartiallyEmittedExpressionNode

type PatternAmbientModule = tscast.PatternAmbientModule

type PlusToken = tscast.PlusToken

type PositionMap = tscast.PositionMap

type PostfixUnaryExpression = tscast.PostfixUnaryExpression

type PostfixUnaryExpressionNode = tscast.PostfixUnaryExpressionNode

type PostfixUnaryOperator = tscast.PostfixUnaryOperator

type Pragma = tscast.Pragma

type PragmaArgument = tscast.PragmaArgument

type PragmaArgumentSpecification = tscast.PragmaArgumentSpecification

type PragmaKindFlags = tscast.PragmaKindFlags

type PragmaSpecification = tscast.PragmaSpecification

type PrefixUnaryExpression = tscast.PrefixUnaryExpression

type PrefixUnaryExpressionNode = tscast.PrefixUnaryExpressionNode

type PrefixUnaryOperator = tscast.PrefixUnaryOperator

type PrimaryExpressionBase = tscast.PrimaryExpressionBase

type PrivateIdentifier = tscast.PrivateIdentifier

type PrivateIdentifierNode = tscast.PrivateIdentifierNode

type PrivateKeyword = tscast.PrivateKeyword

type PropertyAccessExpression = tscast.PropertyAccessExpression

type PropertyAccessExpressionNode = tscast.PropertyAccessExpressionNode

type PropertyAssignment = tscast.PropertyAssignment

type PropertyAssignmentNode = tscast.PropertyAssignmentNode

type PropertyDeclaration = tscast.PropertyDeclaration

type PropertyDeclarationNode = tscast.PropertyDeclarationNode

type PropertyDefinitionList = tscast.PropertyDefinitionList

type PropertyName = tscast.PropertyName

type PropertyNameLiteral = tscast.PropertyNameLiteral

type PropertySignatureDeclaration = tscast.PropertySignatureDeclaration

type PropertySignatureDeclarationNode = tscast.PropertySignatureDeclarationNode

type ProtectedKeyword = tscast.ProtectedKeyword

type PseudoLiteralSyntaxKind = tscast.PseudoLiteralSyntaxKind

type PseudoLiteralToken = tscast.PseudoLiteralToken

type PublicKeyword = tscast.PublicKeyword

type PunctuationSyntaxKind = tscast.PunctuationSyntaxKind

type QualifiedName = tscast.QualifiedName

type QualifiedNameNode = tscast.QualifiedNameNode

type QuestionDotToken = tscast.QuestionDotToken

type QuestionToken = tscast.QuestionToken

type ReadonlyKeyword = tscast.ReadonlyKeyword

type RegularExpressionLiteral = tscast.RegularExpressionLiteral

type RegularExpressionLiteralNode = tscast.RegularExpressionLiteralNode

type RelationalOperator = tscast.RelationalOperator

type RelationalOperatorOrHigher = tscast.RelationalOperatorOrHigher

type RepopulateDiagnosticInfo = tscast.RepopulateDiagnosticInfo

type RepopulateDiagnosticKind = tscast.RepopulateDiagnosticKind

type RestTypeNode = tscast.RestTypeNode

type RestTypeNodeNode = tscast.RestTypeNodeNode

type ReturnStatement = tscast.ReturnStatement

type ReturnStatementNode = tscast.ReturnStatementNode

type SatisfiesExpression = tscast.SatisfiesExpression

type SatisfiesExpressionNode = tscast.SatisfiesExpressionNode

type SemanticMeaning = tscast.SemanticMeaning

type SemicolonClassElement = tscast.SemicolonClassElement

type SemicolonClassElementNode = tscast.SemicolonClassElementNode

type SetAccessorDeclaration = tscast.SetAccessorDeclaration

type SetAccessorDeclarationNode = tscast.SetAccessorDeclarationNode

func SetParentInChildren(p0 *tscast.Node) {
  tscast.SetParentInChildren(p0)
}

func SetParentInChildrenUnset(p0 *tscast.Node) {
  tscast.SetParentInChildrenUnset(p0)
}

type ShiftOperator = tscast.ShiftOperator

type ShiftOperatorOrHigher = tscast.ShiftOperatorOrHigher

type ShorthandPropertyAssignment = tscast.ShorthandPropertyAssignment

type ShorthandPropertyAssignmentNode = tscast.ShorthandPropertyAssignmentNode

type SignatureDeclaration = tscast.SignatureDeclaration

type SourceFile = tscast.SourceFile

type SourceFileDataKey[T any] = tscast.SourceFileDataKey[T]

type SourceFileLike = tscast.SourceFileLike

type SourceFileMetaData = tscast.SourceFileMetaData

type SourceFileNode = tscast.SourceFileNode

type SourceFileParseOptions = tscast.SourceFileParseOptions

type SpreadAssignment = tscast.SpreadAssignment

type SpreadAssignmentNode = tscast.SpreadAssignmentNode

type SpreadElement = tscast.SpreadElement

type SpreadElementNode = tscast.SpreadElementNode

type Statement = tscast.Statement

type StatementBase = tscast.StatementBase

type StatementList = tscast.StatementList

type StaticKeyword = tscast.StaticKeyword

type StringLiteral = tscast.StringLiteral

type StringLiteralLike = tscast.StringLiteralLike

type StringLiteralLikeNode = tscast.StringLiteralLikeNode

type StringLiteralNode = tscast.StringLiteralNode

type SubtreeFacts = tscast.SubtreeFacts

type SuperExpression = tscast.SuperExpression

type SwitchStatement = tscast.SwitchStatement

type SwitchStatementNode = tscast.SwitchStatementNode

type Symbol = tscast.Symbol

type SymbolFlags = tscast.SymbolFlags

const SymbolFlagsAccessor = tscast.SymbolFlagsAccessor

const SymbolFlagsAccessorExcludes = tscast.SymbolFlagsAccessorExcludes

const SymbolFlagsAlias = tscast.SymbolFlagsAlias

const SymbolFlagsAliasExcludes = tscast.SymbolFlagsAliasExcludes

const SymbolFlagsAll = tscast.SymbolFlagsAll

const SymbolFlagsAssignment = tscast.SymbolFlagsAssignment

const SymbolFlagsBlockScoped = tscast.SymbolFlagsBlockScoped

const SymbolFlagsBlockScopedVariable = tscast.SymbolFlagsBlockScopedVariable

const SymbolFlagsBlockScopedVariableExcludes = tscast.SymbolFlagsBlockScopedVariableExcludes

const SymbolFlagsClass = tscast.SymbolFlagsClass

const SymbolFlagsClassExcludes = tscast.SymbolFlagsClassExcludes

const SymbolFlagsClassMember = tscast.SymbolFlagsClassMember

const SymbolFlagsConstEnum = tscast.SymbolFlagsConstEnum

const SymbolFlagsConstEnumExcludes = tscast.SymbolFlagsConstEnumExcludes

const SymbolFlagsConstEnumOnlyModule = tscast.SymbolFlagsConstEnumOnlyModule

const SymbolFlagsConstructor = tscast.SymbolFlagsConstructor

const SymbolFlagsEnum = tscast.SymbolFlagsEnum

const SymbolFlagsEnumMember = tscast.SymbolFlagsEnumMember

const SymbolFlagsEnumMemberExcludes = tscast.SymbolFlagsEnumMemberExcludes

const SymbolFlagsExportDoesNotSupportDefaultModifier = tscast.SymbolFlagsExportDoesNotSupportDefaultModifier

const SymbolFlagsExportHasLocal = tscast.SymbolFlagsExportHasLocal

const SymbolFlagsExportStar = tscast.SymbolFlagsExportStar

const SymbolFlagsExportSupportsDefaultModifier = tscast.SymbolFlagsExportSupportsDefaultModifier

const SymbolFlagsExportValue = tscast.SymbolFlagsExportValue

const SymbolFlagsFunction = tscast.SymbolFlagsFunction

const SymbolFlagsFunctionExcludes = tscast.SymbolFlagsFunctionExcludes

const SymbolFlagsFunctionScopedVariable = tscast.SymbolFlagsFunctionScopedVariable

const SymbolFlagsFunctionScopedVariableExcludes = tscast.SymbolFlagsFunctionScopedVariableExcludes

const SymbolFlagsGetAccessor = tscast.SymbolFlagsGetAccessor

const SymbolFlagsGetAccessorExcludes = tscast.SymbolFlagsGetAccessorExcludes

const SymbolFlagsGlobalLookup = tscast.SymbolFlagsGlobalLookup

const SymbolFlagsInterface = tscast.SymbolFlagsInterface

const SymbolFlagsInterfaceExcludes = tscast.SymbolFlagsInterfaceExcludes

const SymbolFlagsLateBindingContainer = tscast.SymbolFlagsLateBindingContainer

const SymbolFlagsMethod = tscast.SymbolFlagsMethod

const SymbolFlagsMethodExcludes = tscast.SymbolFlagsMethodExcludes

const SymbolFlagsModule = tscast.SymbolFlagsModule

const SymbolFlagsModuleExports = tscast.SymbolFlagsModuleExports

const SymbolFlagsModuleMember = tscast.SymbolFlagsModuleMember

const SymbolFlagsNamespace = tscast.SymbolFlagsNamespace

const SymbolFlagsNamespaceModule = tscast.SymbolFlagsNamespaceModule

const SymbolFlagsNamespaceModuleExcludes = tscast.SymbolFlagsNamespaceModuleExcludes

const SymbolFlagsNone = tscast.SymbolFlagsNone

const SymbolFlagsObjectLiteral = tscast.SymbolFlagsObjectLiteral

const SymbolFlagsOptional = tscast.SymbolFlagsOptional

const SymbolFlagsParameterExcludes = tscast.SymbolFlagsParameterExcludes

const SymbolFlagsProperty = tscast.SymbolFlagsProperty

const SymbolFlagsPropertyExcludes = tscast.SymbolFlagsPropertyExcludes

const SymbolFlagsPropertyOrAccessor = tscast.SymbolFlagsPropertyOrAccessor

const SymbolFlagsPrototype = tscast.SymbolFlagsPrototype

const SymbolFlagsRegularEnum = tscast.SymbolFlagsRegularEnum

const SymbolFlagsRegularEnumExcludes = tscast.SymbolFlagsRegularEnumExcludes

const SymbolFlagsReplaceableByMethod = tscast.SymbolFlagsReplaceableByMethod

const SymbolFlagsSetAccessor = tscast.SymbolFlagsSetAccessor

const SymbolFlagsSetAccessorExcludes = tscast.SymbolFlagsSetAccessorExcludes

const SymbolFlagsSignature = tscast.SymbolFlagsSignature

const SymbolFlagsTransient = tscast.SymbolFlagsTransient

const SymbolFlagsType = tscast.SymbolFlagsType

const SymbolFlagsTypeAlias = tscast.SymbolFlagsTypeAlias

const SymbolFlagsTypeAliasExcludes = tscast.SymbolFlagsTypeAliasExcludes

const SymbolFlagsTypeLiteral = tscast.SymbolFlagsTypeLiteral

const SymbolFlagsTypeParameter = tscast.SymbolFlagsTypeParameter

const SymbolFlagsTypeParameterExcludes = tscast.SymbolFlagsTypeParameterExcludes

const SymbolFlagsValue = tscast.SymbolFlagsValue

const SymbolFlagsValueModule = tscast.SymbolFlagsValueModule

const SymbolFlagsValueModuleExcludes = tscast.SymbolFlagsValueModuleExcludes

const SymbolFlagsVariable = tscast.SymbolFlagsVariable

type SymbolId = tscast.SymbolId

type SymbolTable = tscast.SymbolTable

type SyntaxList = tscast.SyntaxList

type SyntaxListNode = tscast.SyntaxListNode

type SyntheticExpression = tscast.SyntheticExpression

type SyntheticExpressionNode = tscast.SyntheticExpressionNode

type SyntheticReferenceExpression = tscast.SyntheticReferenceExpression

type SyntheticReferenceExpressionNode = tscast.SyntheticReferenceExpressionNode

type TaggedTemplateExpression = tscast.TaggedTemplateExpression

type TaggedTemplateExpressionNode = tscast.TaggedTemplateExpressionNode

type TemplateExpression = tscast.TemplateExpression

type TemplateExpressionNode = tscast.TemplateExpressionNode

type TemplateHead = tscast.TemplateHead

type TemplateHeadNode = tscast.TemplateHeadNode

type TemplateLiteral = tscast.TemplateLiteral

type TemplateLiteralLikeNode = tscast.TemplateLiteralLikeNode

type TemplateLiteralLikeNodeBase = tscast.TemplateLiteralLikeNodeBase

type TemplateLiteralToken = tscast.TemplateLiteralToken

type TemplateLiteralTypeNode = tscast.TemplateLiteralTypeNode

type TemplateLiteralTypeNodeNode = tscast.TemplateLiteralTypeNodeNode

type TemplateLiteralTypeSpan = tscast.TemplateLiteralTypeSpan

type TemplateLiteralTypeSpanList = tscast.TemplateLiteralTypeSpanList

type TemplateLiteralTypeSpanNode = tscast.TemplateLiteralTypeSpanNode

type TemplateMiddle = tscast.TemplateMiddle

type TemplateMiddleNode = tscast.TemplateMiddleNode

type TemplateMiddleOrTail = tscast.TemplateMiddleOrTail

type TemplateSpan = tscast.TemplateSpan

type TemplateSpanList = tscast.TemplateSpanList

type TemplateSpanNode = tscast.TemplateSpanNode

type TemplateTail = tscast.TemplateTail

type TemplateTailNode = tscast.TemplateTailNode

type ThisExpression = tscast.ThisExpression

type ThisTypeNode = tscast.ThisTypeNode

type ThisTypeNodeNode = tscast.ThisTypeNodeNode

type ThrowStatement = tscast.ThrowStatement

type ThrowStatementNode = tscast.ThrowStatementNode

type Token = tscast.Token

type TokenCacheKey = tscast.TokenCacheKey

type TokenFlags = tscast.TokenFlags

const TokenFlagsBinaryOrOctalSpecifier = tscast.TokenFlagsBinaryOrOctalSpecifier

const TokenFlagsBinarySpecifier = tscast.TokenFlagsBinarySpecifier

const TokenFlagsContainsInvalidEscape = tscast.TokenFlagsContainsInvalidEscape

const TokenFlagsContainsInvalidSeparator = tscast.TokenFlagsContainsInvalidSeparator

const TokenFlagsContainsLeadingZero = tscast.TokenFlagsContainsLeadingZero

const TokenFlagsContainsSeparator = tscast.TokenFlagsContainsSeparator

const TokenFlagsExtendedUnicodeEscape = tscast.TokenFlagsExtendedUnicodeEscape

const TokenFlagsHexEscape = tscast.TokenFlagsHexEscape

const TokenFlagsHexSpecifier = tscast.TokenFlagsHexSpecifier

const TokenFlagsIsInvalid = tscast.TokenFlagsIsInvalid

const TokenFlagsNone = tscast.TokenFlagsNone

const TokenFlagsNumericLiteralFlags = tscast.TokenFlagsNumericLiteralFlags

const TokenFlagsOctal = tscast.TokenFlagsOctal

const TokenFlagsOctalSpecifier = tscast.TokenFlagsOctalSpecifier

const TokenFlagsPrecedingJSDocComment = tscast.TokenFlagsPrecedingJSDocComment

const TokenFlagsPrecedingJSDocLeadingAsterisks = tscast.TokenFlagsPrecedingJSDocLeadingAsterisks

const TokenFlagsPrecedingJSDocWithDeprecated = tscast.TokenFlagsPrecedingJSDocWithDeprecated

const TokenFlagsPrecedingJSDocWithSeeOrLink = tscast.TokenFlagsPrecedingJSDocWithSeeOrLink

const TokenFlagsPrecedingLineBreak = tscast.TokenFlagsPrecedingLineBreak

const TokenFlagsRegularExpressionLiteralFlags = tscast.TokenFlagsRegularExpressionLiteralFlags

const TokenFlagsScientific = tscast.TokenFlagsScientific

const TokenFlagsSingleQuote = tscast.TokenFlagsSingleQuote

const TokenFlagsStringLiteralFlags = tscast.TokenFlagsStringLiteralFlags

const TokenFlagsTemplateLiteralLikeFlags = tscast.TokenFlagsTemplateLiteralLikeFlags

const TokenFlagsUnicodeEscape = tscast.TokenFlagsUnicodeEscape

const TokenFlagsUnterminated = tscast.TokenFlagsUnterminated

const TokenFlagsWithSpecifier = tscast.TokenFlagsWithSpecifier

type TokenNode = tscast.TokenNode

type TokenSyntaxKind = tscast.TokenSyntaxKind

type TriviaSyntaxKind = tscast.TriviaSyntaxKind

type TrueLiteral = tscast.TrueLiteral

type TryStatement = tscast.TryStatement

type TryStatementNode = tscast.TryStatementNode

type TupleTypeNode = tscast.TupleTypeNode

type TupleTypeNodeNode = tscast.TupleTypeNodeNode

type TypeAliasDeclaration = tscast.TypeAliasDeclaration

type TypeAliasDeclarationNode = tscast.TypeAliasDeclarationNode

type TypeArgumentList = tscast.TypeArgumentList

type TypeAssertion = tscast.TypeAssertion

type TypeAssertionNode = tscast.TypeAssertionNode

type TypeElement = tscast.TypeElement

type TypeElementBase = tscast.TypeElementBase

type TypeElementList = tscast.TypeElementList

type TypeList = tscast.TypeList

type TypeLiteralNode = tscast.TypeLiteralNode

type TypeLiteralNodeNode = tscast.TypeLiteralNodeNode

type TypeNode = tscast.TypeNode

type TypeNodeBase = tscast.TypeNodeBase

type TypeOfExpression = tscast.TypeOfExpression

type TypeOfExpressionNode = tscast.TypeOfExpressionNode

type TypeOnlyImportDeclaration = tscast.TypeOnlyImportDeclaration

type TypeOperatorNode = tscast.TypeOperatorNode

type TypeOperatorNodeNode = tscast.TypeOperatorNodeNode

type TypeParameterDeclaration = tscast.TypeParameterDeclaration

type TypeParameterDeclarationNode = tscast.TypeParameterDeclarationNode

type TypeParameterList = tscast.TypeParameterList

type TypePrecedence = tscast.TypePrecedence

type TypePredicateNode = tscast.TypePredicateNode

type TypePredicateNodeNode = tscast.TypePredicateNodeNode

type TypePredicateParameterName = tscast.TypePredicateParameterName

type TypeQueryNode = tscast.TypeQueryNode

type TypeQueryNodeNode = tscast.TypeQueryNodeNode

type TypeReferenceNode = tscast.TypeReferenceNode

type TypeReferenceNodeNode = tscast.TypeReferenceNodeNode

type TypeSyntaxBase = tscast.TypeSyntaxBase

type UnaryExpressionBase = tscast.UnaryExpressionBase

type UnionOrIntersectionTypeNode = tscast.UnionOrIntersectionTypeNode

type UnionOrIntersectionTypeNodeBase = tscast.UnionOrIntersectionTypeNodeBase

type UnionTypeNode = tscast.UnionTypeNode

type UnionTypeNodeNode = tscast.UnionTypeNodeNode

type UpdateExpressionBase = tscast.UpdateExpressionBase

type ValidImportTypeNode = tscast.ValidImportTypeNode

type VariableDeclaration = tscast.VariableDeclaration

type VariableDeclarationList = tscast.VariableDeclarationList

type VariableDeclarationListNode = tscast.VariableDeclarationListNode

type VariableDeclarationNode = tscast.VariableDeclarationNode

type VariableDeclarationNodeList = tscast.VariableDeclarationNodeList

type VariableOrParameterDeclaration = tscast.VariableOrParameterDeclaration

type VariableOrPropertyDeclaration = tscast.VariableOrPropertyDeclaration

type VariableStatement = tscast.VariableStatement

type VariableStatementNode = tscast.VariableStatementNode

type Visitor = tscast.Visitor

type VoidExpression = tscast.VoidExpression

type VoidExpressionNode = tscast.VoidExpressionNode

type WhileStatement = tscast.WhileStatement

type WhileStatementNode = tscast.WhileStatementNode

type WithStatement = tscast.WithStatement

type WithStatementNode = tscast.WithStatementNode

type YieldExpression = tscast.YieldExpression

type YieldExpressionNode = tscast.YieldExpressionNode
