// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package vfs is the documented github.com/microsoft/typescript-go/shim/vfs plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/vfs, the
// bridge that reaches the compiler's internal packages.
package vfs

import (
  tsctspath "github.com/microsoft/TypeScript/tsc/shim/tspath"
  tscvfs "github.com/microsoft/TypeScript/tsc/shim/vfs"
)

func DecodeBytes(p0 string) (string, bool) {
  return tscvfs.DecodeBytes(p0)
}

type DirEntry = tscvfs.DirEntry

type Entries = tscvfs.Entries

var ErrClosed = tscvfs.ErrClosed

var ErrExist = tscvfs.ErrExist

var ErrInvalid = tscvfs.ErrInvalid

var ErrNotExist = tscvfs.ErrNotExist

var ErrPermission = tscvfs.ErrPermission

type FS = tscvfs.FS

type FileInfo = tscvfs.FileInfo

var SkipAll = tscvfs.SkipAll

var SkipDir = tscvfs.SkipDir

func WalkDir(p0 tscvfs.FS, p1 tsctspath.RootedPath, p2 tscvfs.WalkDirFunc) error {
  return tscvfs.WalkDir(p0, p1, p2)
}

type WalkDirFunc = tscvfs.WalkDirFunc
