// Code generated by packages/ttsc/tools/gen_shims. DO NOT EDIT.

package checker

import (
  checker "github.com/microsoft/TypeScript/tsc/internal/checker"
  unsafe "unsafe"
)

type extra_NodeBuilder struct {
  ctxStack  []*checker.NodeBuilderContext
  host      checker.Host
  impl      *checker.NodeBuilderImpl
  verbosity *checker.VerbosityContext
}

func nodeBuilder_impl(value *checker.NodeBuilder) *checker.NodeBuilderImpl {
  return ((*extra_NodeBuilder)(unsafe.Pointer(value))).impl
}
