// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package bundled is the documented github.com/microsoft/typescript-go/shim/bundled plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/bundled, the
// bridge that reaches the compiler's internal packages.
package bundled

import (
  tscbundled "github.com/microsoft/TypeScript/tsc/shim/bundled"
  tsctspath "github.com/microsoft/TypeScript/tsc/shim/tspath"
  tscvfs "github.com/microsoft/TypeScript/tsc/shim/vfs"
)

const Embedded = tscbundled.Embedded

func IsBundled(p0 string) bool {
  return tscbundled.IsBundled(p0)
}

var LibNames = tscbundled.LibNames

func LibPath() tsctspath.RootedDirectoryPath {
  return tscbundled.LibPath()
}

func TestingLibPath() string {
  return tscbundled.TestingLibPath()
}

func WrapFS(p0 tscvfs.FS) tscvfs.FS {
  return tscbundled.WrapFS(p0)
}
