// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package parser is the documented github.com/microsoft/typescript-go/shim/parser plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/parser, the
// bridge that reaches the compiler's internal packages.
package parser

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tsccore "github.com/microsoft/TypeScript/tsc/shim/core"
  tscparser "github.com/microsoft/TypeScript/tsc/shim/parser"
)

func GetJSDocCommentRanges(p0 *tscast.NodeFactory, p1 []tscast.CommentRange, p2 *tscast.Node, p3 string) []tscast.CommentRange {
  return tscparser.GetJSDocCommentRanges(p0, p1, p2, p3)
}

type JSDocInfo = tscparser.JSDocInfo

const PCArgumentExpressions = tscparser.PCArgumentExpressions

const PCArrayBindingElements = tscparser.PCArrayBindingElements

const PCArrayLiteralMembers = tscparser.PCArrayLiteralMembers

const PCBlockStatements = tscparser.PCBlockStatements

const PCClassMembers = tscparser.PCClassMembers

const PCCount = tscparser.PCCount

const PCEnumMembers = tscparser.PCEnumMembers

const PCHeritageClauseElement = tscparser.PCHeritageClauseElement

const PCHeritageClauses = tscparser.PCHeritageClauses

const PCImportAttributes = tscparser.PCImportAttributes

const PCImportOrExportSpecifiers = tscparser.PCImportOrExportSpecifiers

const PCJSDocComment = tscparser.PCJSDocComment

const PCJSDocParameters = tscparser.PCJSDocParameters

const PCJsxAttributes = tscparser.PCJsxAttributes

const PCJsxChildren = tscparser.PCJsxChildren

const PCObjectBindingElements = tscparser.PCObjectBindingElements

const PCObjectLiteralMembers = tscparser.PCObjectLiteralMembers

const PCParameters = tscparser.PCParameters

const PCRestProperties = tscparser.PCRestProperties

const PCSourceElements = tscparser.PCSourceElements

const PCSwitchClauseStatements = tscparser.PCSwitchClauseStatements

const PCSwitchClauses = tscparser.PCSwitchClauses

const PCTupleElementTypes = tscparser.PCTupleElementTypes

const PCTypeArguments = tscparser.PCTypeArguments

const PCTypeMembers = tscparser.PCTypeMembers

const PCTypeParameters = tscparser.PCTypeParameters

const PCVariableDeclarations = tscparser.PCVariableDeclarations

type ParseFlags = tscparser.ParseFlags

const ParseFlagsAwait = tscparser.ParseFlagsAwait

const ParseFlagsIgnoreMissingOpenBrace = tscparser.ParseFlagsIgnoreMissingOpenBrace

const ParseFlagsJSDoc = tscparser.ParseFlagsJSDoc

const ParseFlagsNone = tscparser.ParseFlagsNone

const ParseFlagsType = tscparser.ParseFlagsType

const ParseFlagsYield = tscparser.ParseFlagsYield

func ParseIsolatedEntityName(p0 string) *tscast.EntityName {
  return tscparser.ParseIsolatedEntityName(p0)
}

func ParseSourceFile(p0 tscast.SourceFileParseOptions, p1 string, p2 tsccore.ScriptKind) *tscast.SourceFile {
  return tscparser.ParseSourceFile(p0, p1, p2)
}

type Parser = tscparser.Parser

type ParserState = tscparser.ParserState

type ParsingContext = tscparser.ParsingContext

type ParsingContexts = tscparser.ParsingContexts
