// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package stringutil is the documented github.com/microsoft/typescript-go/shim/stringutil plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/stringutil, the
// bridge that reaches the compiler's internal packages.
package stringutil

import (
  tscstringutil "github.com/microsoft/TypeScript/tsc/shim/stringutil"
)

func AddUTF8ByteOrderMark(p0 string) string {
  return tscstringutil.AddUTF8ByteOrderMark(p0)
}

func CodePointToSurrogatePair(p0 rune) (rune, rune) {
  return tscstringutil.CodePointToSurrogatePair(p0)
}

func CombineSurrogatePairs(p0 string) string {
  return tscstringutil.CombineSurrogatePairs(p0)
}

func CompareStringsCaseInsensitive(p0 string, p1 string) tscstringutil.Comparison {
  return tscstringutil.CompareStringsCaseInsensitive(p0, p1)
}

func CompareStringsCaseInsensitiveEslintCompatible(p0 string, p1 string) tscstringutil.Comparison {
  return tscstringutil.CompareStringsCaseInsensitiveEslintCompatible(p0, p1)
}

func CompareStringsCaseInsensitiveThenSensitive(p0 string, p1 string) tscstringutil.Comparison {
  return tscstringutil.CompareStringsCaseInsensitiveThenSensitive(p0, p1)
}

func CompareStringsCaseSensitive(p0 string, p1 string) tscstringutil.Comparison {
  return tscstringutil.CompareStringsCaseSensitive(p0, p1)
}

type Comparison = tscstringutil.Comparison

const ComparisonEqual = tscstringutil.ComparisonEqual

const ComparisonGreaterThan = tscstringutil.ComparisonGreaterThan

const ComparisonLessThan = tscstringutil.ComparisonLessThan

func DecodeJSStringRune(p0 string) (rune, int) {
  return tscstringutil.DecodeJSStringRune(p0)
}

func EncodeJSStringRune(p0 rune) string {
  return tscstringutil.EncodeJSStringRune(p0)
}

func EncodeURI(p0 string) string {
  return tscstringutil.EncodeURI(p0)
}

func EquateStringCaseInsensitive(p0 string, p1 string) bool {
  return tscstringutil.EquateStringCaseInsensitive(p0, p1)
}

func EquateStringCaseSensitive(p0 string, p1 string) bool {
  return tscstringutil.EquateStringCaseSensitive(p0, p1)
}

func GetStringComparer(p0 bool) func(string, string) tscstringutil.Comparison {
  return tscstringutil.GetStringComparer(p0)
}

func GetStringEqualityComparer(p0 bool) func(string, string) bool {
  return tscstringutil.GetStringEqualityComparer(p0)
}

func GuessIndentation(p0 []string) int {
  return tscstringutil.GuessIndentation(p0)
}

func HasPrefix(p0 string, p1 string, p2 bool) bool {
  return tscstringutil.HasPrefix(p0, p1, p2)
}

func HasPrefixAndSuffixWithoutOverlap(p0 string, p1 string, p2 string, p3 bool) bool {
  return tscstringutil.HasPrefixAndSuffixWithoutOverlap(p0, p1, p2, p3)
}

func HasSuffix(p0 string, p1 string, p2 bool) bool {
  return tscstringutil.HasSuffix(p0, p1, p2)
}

func IsASCIILetter(p0 rune) bool {
  return tscstringutil.IsASCIILetter(p0)
}

func IsDigit(p0 rune) bool {
  return tscstringutil.IsDigit(p0)
}

func IsHexDigit(p0 rune) bool {
  return tscstringutil.IsHexDigit(p0)
}

func IsHighSurrogate(p0 rune) bool {
  return tscstringutil.IsHighSurrogate(p0)
}

func IsLineBreak(p0 rune) bool {
  return tscstringutil.IsLineBreak(p0)
}

func IsLowSurrogate(p0 rune) bool {
  return tscstringutil.IsLowSurrogate(p0)
}

func IsOctalDigit(p0 rune) bool {
  return tscstringutil.IsOctalDigit(p0)
}

func IsSurrogate(p0 rune) bool {
  return tscstringutil.IsSurrogate(p0)
}

func IsUnicodeIdentifierPart(p0 rune) bool {
  return tscstringutil.IsUnicodeIdentifierPart(p0)
}

func IsUnicodeIdentifierStart(p0 rune) bool {
  return tscstringutil.IsUnicodeIdentifierStart(p0)
}

func IsWhiteSpaceLike(p0 rune) bool {
  return tscstringutil.IsWhiteSpaceLike(p0)
}

func IsWhiteSpaceSingleLine(p0 rune) bool {
  return tscstringutil.IsWhiteSpaceSingleLine(p0)
}

func LowerFirstChar(p0 string) string {
  return tscstringutil.LowerFirstChar(p0)
}

func RemoveByteOrderMark(p0 string) string {
  return tscstringutil.RemoveByteOrderMark(p0)
}

func SplitLines(p0 string) []string {
  return tscstringutil.SplitLines(p0)
}

func StripQuotes(p0 string) string {
  return tscstringutil.StripQuotes(p0)
}

const SurrogateLowStart = tscstringutil.SurrogateLowStart

func SurrogatePairToCodePoint(p0 rune, p1 rune) rune {
  return tscstringutil.SurrogatePairToCodePoint(p0, p1)
}

func ToLowerJS(p0 string) string {
  return tscstringutil.ToLowerJS(p0)
}

func ToUpperJS(p0 string) string {
  return tscstringutil.ToUpperJS(p0)
}

func TruncateByRunes(p0 string, p1 int) string {
  return tscstringutil.TruncateByRunes(p0, p1)
}

func UnquoteString(p0 string) string {
  return tscstringutil.UnquoteString(p0)
}
