// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package cachedvfs is the documented github.com/microsoft/typescript-go/shim/vfs/cachedvfs plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/vfs/cachedvfs, the
// bridge that reaches the compiler's internal packages.
package cachedvfs

import (
  tscvfs "github.com/microsoft/TypeScript/tsc/shim/vfs"
  tsccachedvfs "github.com/microsoft/TypeScript/tsc/shim/vfs/cachedvfs"
)

type FS = tsccachedvfs.FS

func From(p0 tscvfs.FS) *tsccachedvfs.FS {
  return tsccachedvfs.From(p0)
}
