// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package tsoptions is the documented github.com/microsoft/typescript-go/shim/tsoptions plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/tsoptions, the
// bridge that reaches the compiler's internal packages.
package tsoptions

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tsccore "github.com/microsoft/TypeScript/tsc/shim/core"
  tsctsoptions "github.com/microsoft/TypeScript/tsc/shim/tsoptions"
  tsctspath "github.com/microsoft/TypeScript/tsc/shim/tspath"
  tscvfs "github.com/microsoft/TypeScript/tsc/shim/vfs"
)

type AlternateModeDiagnostics = tsctsoptions.AlternateModeDiagnostics

var BuildNameMap = tsctsoptions.BuildNameMap

var BuildOpts = tsctsoptions.BuildOpts

var CommandLineCompilerOptionsMap = tsctsoptions.CommandLineCompilerOptionsMap

type CommandLineOption = tsctsoptions.CommandLineOption

type CommandLineOptionKind = tsctsoptions.CommandLineOptionKind

type CommandLineOptionNameMap = tsctsoptions.CommandLineOptionNameMap

type CommandLineOptionPathKind = tsctsoptions.CommandLineOptionPathKind

const CommandLineOptionPathKindConfigLocator = tsctsoptions.CommandLineOptionPathKindConfigLocator

const CommandLineOptionPathKindDirectory = tsctsoptions.CommandLineOptionPathKindDirectory

const CommandLineOptionPathKindFile = tsctsoptions.CommandLineOptionPathKindFile

const CommandLineOptionPathKindFileOrDirectory = tsctsoptions.CommandLineOptionPathKindFileOrDirectory

const CommandLineOptionPathKindFileSpec = tsctsoptions.CommandLineOptionPathKindFileSpec

const CommandLineOptionPathKindNone = tsctsoptions.CommandLineOptionPathKindNone

const CommandLineOptionPathKindPathPattern = tsctsoptions.CommandLineOptionPathKindPathPattern

const CommandLineOptionPathKindResolvedPathPattern = tsctsoptions.CommandLineOptionPathKindResolvedPathPattern

const CommandLineOptionPathKindSourceMapLocation = tsctsoptions.CommandLineOptionPathKindSourceMapLocation

const CommandLineOptionTypeBoolean = tsctsoptions.CommandLineOptionTypeBoolean

const CommandLineOptionTypeEnum = tsctsoptions.CommandLineOptionTypeEnum

const CommandLineOptionTypeList = tsctsoptions.CommandLineOptionTypeList

const CommandLineOptionTypeListOrElement = tsctsoptions.CommandLineOptionTypeListOrElement

const CommandLineOptionTypeNumber = tsctsoptions.CommandLineOptionTypeNumber

const CommandLineOptionTypeObject = tsctsoptions.CommandLineOptionTypeObject

const CommandLineOptionTypeString = tsctsoptions.CommandLineOptionTypeString

// CommandLineRawOptions holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/collections.OrderedMap).
var CommandLineRawOptions = tsctsoptions.CommandLineRawOptions

var CompilerNameMap = tsctsoptions.CompilerNameMap

func CompilerOptionsAffectDeclarationPath(p0 *tsccore.CompilerOptions, p1 *tsccore.CompilerOptions) bool {
  return tsctsoptions.CompilerOptionsAffectDeclarationPath(p0, p1)
}

func CompilerOptionsAffectEmit(p0 *tsccore.CompilerOptions, p1 *tsccore.CompilerOptions) bool {
  return tsctsoptions.CompilerOptionsAffectEmit(p0, p1)
}

func CompilerOptionsAffectSemanticDiagnostics(p0 *tsccore.CompilerOptions, p1 *tsccore.CompilerOptions) bool {
  return tsctsoptions.CompilerOptionsAffectSemanticDiagnostics(p0, p1)
}

var CompilerOptionsDidYouMeanDiagnostics = tsctsoptions.CompilerOptionsDidYouMeanDiagnostics

type CompilerOptionsValue = tsctsoptions.CompilerOptionsValue

func ConvertOptionToAbsolutePath(p0 string, p1 any, p2 tsctsoptions.CommandLineOptionNameMap, p3 tsctspath.RootedDirectoryPath) (any, bool) {
  return tsctsoptions.ConvertOptionToAbsolutePath(p0, p1, p2, p3)
}

func ConvertToTSConfig(p0 *tsctsoptions.ParsedCommandLine, p1 tsctspath.RootedFilePath) *tsctsoptions.TSConfig {
  return tsctsoptions.ConvertToTSConfig(p0, p1)
}

// CreateDiagnosticAtReferenceSyntax holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/diagnostics.Message).
var CreateDiagnosticAtReferenceSyntax = tsctsoptions.CreateDiagnosticAtReferenceSyntax

// CreateDiagnosticForNodeInSourceFile holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/diagnostics.Message).
var CreateDiagnosticForNodeInSourceFile = tsctsoptions.CreateDiagnosticForNodeInSourceFile

// CreateDiagnosticForNodeInSourceFileOrCompilerDiagnostic holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/diagnostics.Message).
var CreateDiagnosticForNodeInSourceFileOrCompilerDiagnostic = tsctsoptions.CreateDiagnosticForNodeInSourceFileOrCompilerDiagnostic

type DidYouMeanOptionsDiagnostics = tsctsoptions.DidYouMeanOptionsDiagnostics

type ExtendedConfigCache = tsctsoptions.ExtendedConfigCache

type ExtendedConfigCacheEntry = tsctsoptions.ExtendedConfigCacheEntry

func ForEachCompilerOptionAffectingBuildInfo(p0 *tsccore.CompilerOptions, p1 func(*tsctsoptions.CommandLineOption, any)) {
  tsctsoptions.ForEachCompilerOptionAffectingBuildInfo(p0, p1)
}

func GetCallbackForFindingPropertyAssignmentByValue(p0 string) func(*tscast.PropertyAssignment) *tscast.Node {
  return tsctsoptions.GetCallbackForFindingPropertyAssignmentByValue(p0)
}

// GetContentMapperOptionDiagnosticLocation holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/contentmapper.Mapper).
var GetContentMapperOptionDiagnosticLocation = tsctsoptions.GetContentMapperOptionDiagnosticLocation

func GetDefaultLibFileName(p0 *tsccore.CompilerOptions) string {
  return tsctsoptions.GetDefaultLibFileName(p0)
}

func GetLibFileName(p0 string) (string, bool) {
  return tsctsoptions.GetLibFileName(p0)
}

func GetNameMapFromList(p0 []*tsctsoptions.CommandLineOption) *tsctsoptions.NameMap {
  return tsctsoptions.GetNameMapFromList(p0)
}

func GetOptionsSyntaxByArrayElementValue(p0 *tscast.ObjectLiteralExpression, p1 string, p2 string) *tscast.Node {
  return tsctsoptions.GetOptionsSyntaxByArrayElementValue(p0, p1, p2)
}

// GetParsedCommandLineOfConfigFile holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/collections.OrderedMap).
var GetParsedCommandLineOfConfigFile = tsctsoptions.GetParsedCommandLineOfConfigFile

// GetParsedCommandLineOfConfigFilePath holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/collections.OrderedMap).
var GetParsedCommandLineOfConfigFilePath = tsctsoptions.GetParsedCommandLineOfConfigFilePath

func GetSupportedExtensions(p0 *tsccore.CompilerOptions, p1 []string) [][]string {
  return tsctsoptions.GetSupportedExtensions(p0, p1)
}

func GetSupportedExtensionsWithJsonIfResolveJsonModule(p0 *tsccore.CompilerOptions, p1 [][]string) [][]string {
  return tsctsoptions.GetSupportedExtensionsWithJsonIfResolveJsonModule(p0, p1)
}

func GetTsConfigPropArrayElementValue(p0 *tscast.SourceFile, p1 string, p2 string) *tscast.StringLiteral {
  return tsctsoptions.GetTsConfigPropArrayElementValue(p0, p1, p2)
}

var LibFilesSet = tsctsoptions.LibFilesSet

var LibMap = tsctsoptions.LibMap

var Libs = tsctsoptions.Libs

type NameMap = tsctsoptions.NameMap

// NewParsedCommandLine holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.ProjectReference).
var NewParsedCommandLine = tsctsoptions.NewParsedCommandLine

func NewTsconfigSourceFileFromFilePath(p0 tsctspath.RootedFilePath, p1 tsctspath.PathKey, p2 string) *tsctsoptions.TsConfigSourceFile {
  return tsctsoptions.NewTsconfigSourceFileFromFilePath(p0, p1, p2)
}

var OptionsDeclarations = tsctsoptions.OptionsDeclarations

var OptionsForBuild = tsctsoptions.OptionsForBuild

func ParseBuildCommandLine(p0 []string, p1 tscvfs.FS, p2 tsctspath.RootedDirectoryPath) *tsctsoptions.ParsedBuildCommandLine {
  return tsctsoptions.ParseBuildCommandLine(p0, p1, p2)
}

// ParseBuildOptions holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.BuildOptions).
var ParseBuildOptions = tsctsoptions.ParseBuildOptions

func ParseCommandLine(p0 []string, p1 tscvfs.FS, p2 tsctspath.RootedDirectoryPath) *tsctsoptions.ParsedCommandLine {
  return tsctsoptions.ParseCommandLine(p0, p1, p2)
}

type ParseCommandLineWorkerDiagnostics = tsctsoptions.ParseCommandLineWorkerDiagnostics

func ParseCompilerOptions(p0 string, p1 any, p2 *tsccore.CompilerOptions) {
  tsctsoptions.ParseCompilerOptions(p0, p1, p2)
}

func ParseConfigFileTextToJson(p0 tsctspath.RootedFilePath, p1 tsctspath.PathKey, p2 string) (any, []*tscast.Diagnostic) {
  return tsctsoptions.ParseConfigFileTextToJson(p0, p1, p2)
}

func ParseExtendedConfig(p0 tsctspath.RootedFilePath, p1 tsctspath.PathKey, p2 []tsctspath.PathKey, p3 tscvfs.FS, p4 tsctsoptions.ExtendedConfigCache) *tsctsoptions.ExtendedConfigCacheEntry {
  return tsctsoptions.ParseExtendedConfig(p0, p1, p2, p3, p4)
}

func ParseJsonConfigFileContent(p0 any, p1 tscvfs.FS, p2 tsctspath.RootedDirectoryPath, p3 *tsccore.CompilerOptions, p4 tsctspath.RootedFilePath, p5 []tsctspath.PathKey, p6 tsctsoptions.ExtendedConfigCache) *tsctsoptions.ParsedCommandLine {
  return tsctsoptions.ParseJsonConfigFileContent(p0, p1, p2, p3, p4, p5, p6)
}

// ParseJsonSourceFileConfigFileContent holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/collections.OrderedMap).
var ParseJsonSourceFileConfigFileContent = tsctsoptions.ParseJsonSourceFileConfigFileContent

func ParseListTypeOption(p0 *tsctsoptions.CommandLineOption, p1 string) ([]any, []*tscast.Diagnostic) {
  return tsctsoptions.ParseListTypeOption(p0, p1)
}

func ParseString(p0 any) string {
  return tsctsoptions.ParseString(p0)
}

func ParseStringArray(p0 any) []string {
  return tsctsoptions.ParseStringArray(p0)
}

func ParseTristate(p0 any) tsccore.Tristate {
  return tsctsoptions.ParseTristate(p0)
}

// ParseTypeAcquisition holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.TypeAcquisition).
var ParseTypeAcquisition = tsctsoptions.ParseTypeAcquisition

type ParsedBuildCommandLine = tsctsoptions.ParsedBuildCommandLine

type ParsedCommandLine = tsctsoptions.ParsedCommandLine

type ParsedOptions = tsctsoptions.ParsedOptions

func PathValueAsString(p0 any) (string, bool) {
  return tsctsoptions.PathValueAsString(p0)
}

func PathValuesAsStrings(p0 any) ([]string, bool) {
  return tsctsoptions.PathValuesAsStrings(p0)
}

type RawCompilerOptions = tsctsoptions.RawCompilerOptions

type SourceOutputAndProjectReference = tsctsoptions.SourceOutputAndProjectReference

type TSConfig = tsctsoptions.TSConfig

// TargetToLibMap holds the bridge function: its signature uses a type no bridge
// exposes (github.com/microsoft/TypeScript/tsc/internal/core.ScriptTarget).
var TargetToLibMap = tsctsoptions.TargetToLibMap

type TsConfigSourceFile = tsctsoptions.TsConfigSourceFile

var TscBuildOption = tsctsoptions.TscBuildOption
