// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package core is the documented github.com/microsoft/typescript-go/shim/core plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/core, the
// bridge that reaches the compiler's internal packages.
package core

import (
  tsccore "github.com/microsoft/TypeScript/tsc/shim/core"
)

func ApplyDebugStackLimit() {
  tsccore.ApplyDebugStackLimit()
}

type CompilerOptions = tsccore.CompilerOptions

func ComputeECMALineStarts(p0 string) tsccore.ECMALineStarts {
  return tsccore.ComputeECMALineStarts(p0)
}

type ECMALineStarts = tsccore.ECMALineStarts

type JsxEmit = tsccore.JsxEmit

const JsxEmitNone = tsccore.JsxEmitNone

const JsxEmitPreserve = tsccore.JsxEmitPreserve

const JsxEmitReact = tsccore.JsxEmitReact

const JsxEmitReactJSX = tsccore.JsxEmitReactJSX

const JsxEmitReactJSXDev = tsccore.JsxEmitReactJSXDev

const JsxEmitReactNative = tsccore.JsxEmitReactNative

type ModuleKind = tsccore.ModuleKind

const ModuleKindAMD = tsccore.ModuleKindAMD

const ModuleKindCommonJS = tsccore.ModuleKindCommonJS

const ModuleKindES2015 = tsccore.ModuleKindES2015

const ModuleKindES2020 = tsccore.ModuleKindES2020

const ModuleKindES2022 = tsccore.ModuleKindES2022

const ModuleKindESNext = tsccore.ModuleKindESNext

const ModuleKindNode16 = tsccore.ModuleKindNode16

const ModuleKindNode18 = tsccore.ModuleKindNode18

const ModuleKindNode20 = tsccore.ModuleKindNode20

const ModuleKindNodeNext = tsccore.ModuleKindNodeNext

const ModuleKindNone = tsccore.ModuleKindNone

const ModuleKindPreserve = tsccore.ModuleKindPreserve

const ModuleKindSystem = tsccore.ModuleKindSystem

const ModuleKindUMD = tsccore.ModuleKindUMD

type ModuleResolutionKind = tsccore.ModuleResolutionKind

const ModuleResolutionKindBundler = tsccore.ModuleResolutionKindBundler

const ModuleResolutionKindClassic = tsccore.ModuleResolutionKindClassic

const ModuleResolutionKindNode10 = tsccore.ModuleResolutionKindNode10

const ModuleResolutionKindNode16 = tsccore.ModuleResolutionKindNode16

const ModuleResolutionKindNodeNext = tsccore.ModuleResolutionKindNodeNext

const ModuleResolutionKindUnknown = tsccore.ModuleResolutionKindUnknown

func NewTextRange(p0 int, p1 int) tsccore.TextRange {
  return tsccore.NewTextRange(p0, p1)
}

type ResolutionMode = tsccore.ResolutionMode

const ResolutionModeCommonJS = tsccore.ResolutionModeCommonJS

const ResolutionModeESM = tsccore.ResolutionModeESM

const ResolutionModeNone = tsccore.ResolutionModeNone

type ScriptKind = tsccore.ScriptKind

const ScriptKindJS = tsccore.ScriptKindJS

const ScriptKindJSON = tsccore.ScriptKindJSON

const ScriptKindJSX = tsccore.ScriptKindJSX

const ScriptKindTS = tsccore.ScriptKindTS

const ScriptKindTSX = tsccore.ScriptKindTSX

const ScriptKindUnknown = tsccore.ScriptKindUnknown

const TSFalse = tsccore.TSFalse

const TSTrue = tsccore.TSTrue

const TSUnknown = tsccore.TSUnknown

type TextPos = tsccore.TextPos

type TextRange = tsccore.TextRange

type Tristate = tsccore.Tristate

func TypeScriptVersionSatisfiesRange(p0 string) bool {
  return tsccore.TypeScriptVersionSatisfiesRange(p0)
}

func UndefinedTextRange() tsccore.TextRange {
  return tsccore.UndefinedTextRange()
}

func Version() string {
  return tsccore.Version()
}
