/**
 * The ESM source that stands in for a CommonJS module an ESM `import` reaches.
 *
 * The caller selects this adaptation when hook-served CommonJS source needs the
 * ordinary CommonJS loading lane rather than an ESM loader's narrower
 * module-local require. The generated source uses public `createRequire` and
 * the caller's source-aware load boundary, sharing Node's CommonJS cache.
 * Evaluation occurs with the importer; native load failures still propagate.
 *
 * `default` captures `module.exports`. Detected named exports read only own
 * properties, once after loading; missing/inherited properties and throwing
 * getters yield undefined, as Node's translator does. Own-property inspection
 * errors propagate. The supplied marker capability selects either a namespace
 * `module.exports` alias or the older ordinary named-property behavior,
 * including its own-property check for a detected `default` name.
 *
 * @param url The module's URL, which its `require` resolves from.
 * @param filename The module's path, which the CommonJS loader loads.
 * @param names The names Node's static export detection finds for it.
 * @param moduleExportsKey Whether the runtime's namespace carries
 *   `module.exports`.
 * @evidence contracts/common.md#principled-implementation Public createRequire routes loading through the shared CommonJS cache; deduplicated detected names preserve Node's own-only projection, getter-error suppression and capability-selected marker behavior without guessing dynamic exports.
 * @evidence contracts/common.md#clear-and-simple-design One source builder isolates the ESM-to-CommonJS adaptation; callers supply actual detected names and loader capability rather than embedding another compatibility policy.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts Supported createRequire and generated ESM adapt the selected public loader lane. JSON quoting protects caller text; only named-property getter errors are suppressed by the specified Node policy, while native load and own-inspection failures propagate.
 * @evidence contracts/common.md#meaningful-documentation Native paragraphs distinguish caller-selected loader adaptation, captured default, own-only names, getter errors and marker/version behavior; parameters identify URL, native filename and supplied capability.
 * @evidence contracts/performance.md#efficient-algorithms Set deduplication processes N names and their text; temporary arrays/lines and joining scale with generated bytes. Execution separately delegates native module resolution/evaluation/cache work and own-property/getter observations whose cost is not bounded by generation size.
 * @evidence contracts/performance.md#reuse-equivalent-work The generated facade invokes createRequire so imports and ordinary require share Node's CommonJS evaluation cache; source generation itself remains caller-owned and does not cache mutable name inputs.
 *
 * @evidenceExclude contracts/performance.md#bound-retention-and-release-resources Temporary names and source lines end with the call; the returned source and Node's module cache belong to the runtime loader.
 * @evidence contracts/portability.md#os-neutral-implementation Generated public createRequire receives the caller's module URL and native filename as independently JSON-quoted values, leaving native resolution and filesystem spelling to Node and the caller's source boundary. Supplied marker capability selects namespace representation without OS-name guessing or path rewriting.
 */
export function commonJsImportFacade(
  url: string,
  filename: string,
  names: readonly string[],
  moduleExportsKey: boolean,
): string {
  const lines = [
    `import { createRequire as __ttscCreateRequire } from "node:module";`,
    `const __ttscHasOwn = Object.hasOwn;`,
    `const __ttscModule = __ttscCreateRequire(${JSON.stringify(url)})(${JSON.stringify(filename)});`,
    `export default __ttscModule;`,
  ];
  if (moduleExportsKey)
    lines.push(`export { __ttscModule as "module.exports" };`);
  [...new Set(names)].forEach((name, index) => {
    if (name === "default") {
      if (!moduleExportsKey)
        lines.push(`__ttscHasOwn(__ttscModule, "default");`);
      return;
    }
    if (name === "module.exports" && moduleExportsKey) return;
    lines.push(
      `let __ttscExport${index};`,
      `if (__ttscHasOwn(__ttscModule, ${JSON.stringify(name)})) {`,
      `  try { __ttscExport${index} = __ttscModule[${JSON.stringify(name)}]; } catch {}`,
      `}`,
      `export { __ttscExport${index} as ${JSON.stringify(name)} };`,
    );
  });
  return `${lines.join("\n")}\n`;
}
