/**
 * The ESM source that stands in for a CommonJS module an ESM `import` reaches.
 *
 * Node evaluates a CommonJS module handed to its ESM loader with source on a
 * path where the module's own `require()` does not reach `module.registerHooks`
 * on every supported release, so a nested `require("./x.js")` backed only by
 * `x.ts` failed there. The facade loads
 * the module through the CommonJS loader instead, with a `require` from
 * `createRequire`, whose resolution and loading the hooks serve on every
 * release, and gives the importer the namespace Node would have: `default` as
 * `module.exports`, `module.exports` itself where the runtime exports it, and
 * each statically detected name read from `module.exports` once the module has
 * run. The module is evaluated where the importer's graph evaluates it, and
 * once, in the same module cache a `require()` of it uses.
 *
 * @param url The module's URL, which its `require` resolves from.
 * @param filename The module's path, which the CommonJS loader loads.
 * @param names The names Node's static export detection finds for it.
 * @param moduleExportsKey Whether the runtime's namespace carries
 *   `module.exports`.
 *
 * @evidence contracts/common.md#principled-implementation createRequire routes the CommonJS body through Node's ordinary shared module cache, then the facade exposes default and deduplicated static names with the runtime's supported namespace marker, preserving checked nested require behavior.
 * @evidence contracts/common.md#clear-and-simple-design One source builder isolates the ESM-to-CommonJS adaptation; callers supply actual detected names and loader capability rather than embedding another compatibility policy.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts The facade uses supported createRequire and emitted ESM syntax for an actual Node loader difference; JSON quoting prevents caller paths or names from becoming unescaped executable fragments.
 * @evidence contracts/common.md#meaningful-documentation Native paragraphs explain the loader difference, evaluation/cache ownership and namespace shape; parameters distinguish URL, native filename and capability-derived marker.
 * @evidence contracts/performance.md#efficient-algorithms A Set deduplicates N detected names in O(N) expected operations; line construction and joining cost total generated bytes, without repeated whole-source concatenation.
 * @evidence contracts/performance.md#reuse-equivalent-work The generated facade invokes createRequire so imports and ordinary require share Node's CommonJS evaluation cache; source generation itself remains caller-owned and does not cache mutable name inputs.
 *
 * @evidenceExclude contracts/performance.md#bound-retention-and-release-resources Temporary names and source lines end with the call; the returned source and Node's module cache belong to the runtime loader.
 * @evidenceExclude contracts/portability.md#os-neutral-implementation Embeds the module URL and filename as JSON strings in generated source; it interprets neither and calls no path API.
 */
export function commonJsImportFacade(
  url: string,
  filename: string,
  names: readonly string[],
  moduleExportsKey: boolean,
): string {
  const lines = [
    `import { createRequire as __ttscCreateRequire } from "node:module";`,
    `const __ttscModule = __ttscCreateRequire(${JSON.stringify(url)})(${JSON.stringify(filename)});`,
    `export default __ttscModule;`,
  ];
  if (moduleExportsKey)
    lines.push(`export { __ttscModule as "module.exports" };`);
  [...new Set(names)]
    .filter((name) => name !== "default" && name !== "module.exports")
    .forEach((name, index) => {
      lines.push(
        `const __ttscExport${index} = __ttscModule[${JSON.stringify(name)}];`,
        `export { __ttscExport${index} as ${JSON.stringify(name)} };`,
      );
    });
  return `${lines.join("\n")}\n`;
}
