package linthost

import (
  "os"
  "path/filepath"
  "testing"
)

// TestCommandFormatStructuralRulesAreIdempotentOnTheirOwnOutput verifies
// the `ttsc format` cascade preserves an independently authored four-statement
// fixed point. The input is not generated by a preceding formatter invocation.
//
// Whole-file equality preserves the declaration kinds, types, literal values
// and call operands. Command success and unchanged bytes do not count transient
// edits or cover nested class-body depth.
//
//  1. Seed a project with the authored four-statement expectation.
//  2. Run `ttsc format`.
//  3. Assert the file is unchanged and the subcommand exits cleanly.
//
// @evidence contracts/testing.md#behavioral-verification Runs the in-process `format` command with an empty format block on a four-statement file that is already one statement per line with semicolons, and requires exit 0, empty output and the file byte-identical.
// @evidence contracts/testing.md#independent-expectations The canonical source is an authored literal that serves as its own expected output; it is not derived from the formatter.
// @evidence contracts/testing.md#distinguishing-cases One independently authored fixed point with three typed declarations and a call, all already on separate semicolon-terminated lines. It rejects a final byte change but does not measure transient edits, use actual prior formatter output, or establish class-body and nested-block behavior.
// @evidence contracts/testing.md#execution-ownership In-process Go unit: calls run with the format subcommand on a temp-dir project and JSON config; no child process, built binary or installed consumer.
func TestCommandFormatStructuralRulesAreIdempotentOnTheirOwnOutput(t *testing.T) {
  canonical := "const a: string = \"Hello, World!\";\n" +
    "let b: number = 42;\n" +
    "var c: boolean = true;\n" +
    "console.log(a, b, c);\n"
  root := seedLintProject(t, canonical)
  seedLintConfig(t, root, map[string]any{
    "format": map[string]any{},
  })
  code, stdout, stderr := captureCommandOutput(t, func() int {
    return run([]string{
      "format",
      "--cwd", root,
      "--plugins-json", lintManifest(t),
    })
  })
  if code != 0 || stdout != "" || stderr != "" {
    t.Fatalf("format command mismatch: code=%d stdout=%q stderr=%q", code, stdout, stderr)
  }
  got, err := os.ReadFile(filepath.Join(root, "src", "main.ts"))
  if err != nil {
    t.Fatalf("ReadFile: %v", err)
  }
  if string(got) != canonical {
    t.Fatalf("format is not idempotent:\nwant %q\ngot  %q", canonical, string(got))
  }
}
