package linthost

import "testing"

// TestEngineCRLFTerminatorEmitsCarriageReturns verifies the EndOfLine
// option threads a CRLF terminator into the newline a Hardline emits.
//
// The explicit option controls generated bytes regardless of the running OS.
// A Hardline-bearing Group between literal a and b must contain the authored
// CRLF boundary, rather than an LF or missing separator.
//
// @evidence contracts/testing.md#behavioral-verification Print must join a and b with CRLF when EndOfLine is crlf.
// @evidence contracts/testing.md#independent-expectations The explicit line-ending option requires the literal a\r\nb; no expected string is rendered by Print.
// @evidence contracts/testing.md#distinguishing-cases This Hardline CRLF case complements the empty-option LF default case.
// @evidence contracts/testing.md#execution-ownership TestEngineCRLFTerminatorEmitsCarriageReturns is one Go unit entry that renders a Hardline-bearing Group with Print and EndOfLine crlf in-process; it parses no source and installs, builds and launches nothing.
func TestEngineCRLFTerminatorEmitsCarriageReturns(t *testing.T) {
  doc := Group(Text("a"), Hardline(), Text("b"))
  opts := DefaultPrintOptions()
  opts.EndOfLine = "crlf"
  got := Print(doc, opts)
  if got != "a\r\nb" {
    t.Fatalf("crlf mismatch: %q", got)
  }
}
