package linthost

import (
  "reflect"
  "testing"
)

// TestProjectInputSnapshotNormalizesWindowsSeparatorsWithoutFoldingCase
// verifies a producer does not erase a declaration before a filesystem-aware
// consumer can determine its identity.
//
// Windows directories may opt into case-sensitive lookup, so paths differing
// only by case can name different files. The producer normalizes separators and
// glob shape but preserves exact case; the consumer later converges aliases on
// ordinary case-insensitive directories.
//
//  1. Supply exact paths and globs with mixed case and separators.
//  2. Normalize them under Windows path rules.
//  3. Assert every case spelling survives in stable slash form.
//
// @evidence contracts/testing.md#behavioral-verification uniqueProjectInputPatternsForFilesystem normalizes authored mixed-separator path and wildcard inputs under Windows rules; exact slice equality detects premature case folding that would erase a distinct declaration.
// @evidence contracts/testing.md#independent-expectations Literal slash-normalized paths retain each input's exact case according to the producer contract; the expected four distinct sorted strings are not generated by the normalizer.
// @evidence contracts/testing.md#distinguishing-cases Exact files and recursive JSON globs each have adjacent upper/lower case spellings and backslash/slash inputs. This case pins preservation before filesystem identity lookup; alias convergence on an actual filesystem belongs to consumer boundary tests.
// @evidence contracts/testing.md#execution-ownership This single named Go unit invokes the package's pattern normalizer in the shared linthost test process using strings only, with no native binary, consumer installation, filesystem lookup or product host.
func TestProjectInputSnapshotNormalizesWindowsSeparatorsWithoutFoldingCase(
  t *testing.T,
) {
  got := uniqueProjectInputPatternsForFilesystem([]string{
    `C:\Repo\Docs\Spec.md`,
    `c:/repo/docs/spec.md`,
    `C:\Repo\Api\**\*.JSON`,
    `c:/repo/api/**/*.json`,
  }, true)
  want := []string{
    "C:/Repo/Api/**/*.JSON",
    "C:/Repo/Docs/Spec.md",
    "c:/repo/api/**/*.json",
    "c:/repo/docs/spec.md",
  }
  if !reflect.DeepEqual(got, want) {
    t.Fatalf("Windows-normalized inputs = %#v, want %#v", got, want)
  }
}
