package linthost

import "strings"

var legacyBuiltinRuleNames = map[string]string{
  "adjacent-overload-signatures": "adjacentOverloadSignatures",
  "array-type": "arrayType",
  "await-thenable": "awaitThenable",
  "ban-ts-comment": "banTsComment",
  "ban-tslint-comment": "banTslintComment",
  "consistent-indexed-object-style": "consistentIndexedObjectStyle",
  "consistent-type-assertions": "consistentTypeAssertions",
  "consistent-type-definitions": "consistentTypeDefinitions",
  "consistent-type-imports": "consistentTypeImports",
  "default-param-last": "defaultParamLast",
  "dot-notation": "dotNotation",
  "for-direction": "forDirection",
  "no-alert": "noAlert",
  "no-array-constructor": "noArrayConstructor",
  "no-array-delete": "noArrayDelete",
  "no-async-promise-executor": "noAsyncPromiseExecutor",
  "no-bitwise": "noBitwise",
  "no-caller": "noCaller",
  "no-case-declarations": "noCaseDeclarations",
  "no-class-assign": "noClassAssign",
  "no-compare-neg-zero": "noCompareNegZero",
  "no-cond-assign": "noCondAssign",
  "no-confusing-non-null-assertion": "noConfusingNonNullAssertion",
  "no-console": "noConsole",
  "no-constant-condition": "noConstantCondition",
  "no-continue": "noContinue",
  "no-control-regex": "noControlRegex",
  "no-debugger": "noDebugger",
  "no-delete-var": "noDeleteVar",
  "no-dupe-args": "noDupeArgs",
  "no-dupe-else-if": "noDupeElseIf",
  "no-dupe-keys": "noDupeKeys",
  "no-duplicate-case": "noDuplicateCase",
  "no-duplicate-enum-values": "noDuplicateEnumValues",
  "no-dynamic-delete": "noDynamicDelete",
  "no-empty": "noEmpty",
  "no-empty-character-class": "noEmptyCharacterClass",
  "no-empty-function": "noEmptyFunction",
  "no-empty-interface": "noEmptyInterface",
  "no-empty-object-type": "noEmptyObjectType",
  "no-empty-pattern": "noEmptyPattern",
  "no-empty-static-block": "noEmptyStaticBlock",
  "no-eq-null": "noEqNull",
  "no-eval": "noEval",
  "no-ex-assign": "noExAssign",
  "no-explicit-any": "noExplicitAny",
  "no-extra-bind": "noExtraBind",
  "no-extra-boolean-cast": "noExtraBooleanCast",
  "no-extra-non-null-assertion": "noExtraNonNullAssertion",
  "no-fallthrough": "noFallthrough",
  "no-func-assign": "noFuncAssign",
  "no-import-type-side-effects": "noImportTypeSideEffects",
  "no-inferrable-types": "noInferrableTypes",
  "no-inner-declarations": "noInnerDeclarations",
  "no-irregular-whitespace": "noIrregularWhitespace",
  "no-iterator": "noIterator",
  "no-labels": "noLabels",
  "no-lone-blocks": "noLoneBlocks",
  "no-lonely-if": "noLonelyIf",
  "no-loss-of-precision": "noLossOfPrecision",
  "no-misleading-character-class": "noMisleadingCharacterClass",
  "no-misused-new": "noMisusedNew",
  "no-mixed-enums": "noMixedEnums",
  "no-multi-assign": "noMultiAssign",
  "no-multi-str": "noMultiStr",
  "no-namespace": "noNamespace",
  "no-negated-condition": "noNegatedCondition",
  "no-nested-ternary": "noNestedTernary",
  "no-new": "noNew",
  "no-new-func": "noNewFunc",
  "no-new-wrappers": "noNewWrappers",
  "no-non-null-asserted-nullish-coalescing": "noNonNullAssertedNullishCoalescing",
  "no-non-null-asserted-optional-chain": "noNonNullAssertedOptionalChain",
  "no-non-null-assertion": "noNonNullAssertion",
  "no-obj-calls": "noObjCalls",
  "no-object-constructor": "noObjectConstructor",
  "no-octal": "noOctal",
  "no-octal-escape": "noOctalEscape",
  "no-plusplus": "noPlusplus",
  "no-promise-executor-return": "noPromiseExecutorReturn",
  "no-proto": "noProto",
  "no-prototype-builtins": "noPrototypeBuiltins",
  "no-regex-spaces": "noRegexSpaces",
  "no-require-imports": "noRequireImports",
  "no-return-assign": "noReturnAssign",
  "no-script-url": "noScriptUrl",
  "no-self-assign": "noSelfAssign",
  "no-self-compare": "noSelfCompare",
  "no-sequences": "noSequences",
  "no-setter-return": "noSetterReturn",
  "no-shadow-restricted-names": "noShadowRestrictedNames",
  "no-sparse-arrays": "noSparseArrays",
  "no-template-curly-in-string": "noTemplateCurlyInString",
  "no-this-alias": "noThisAlias",
  "no-throw-literal": "noThrowLiteral",
  "no-undef-init": "noUndefInit",
  "no-unnecessary-parameter-property-assignment": "noUnnecessaryParameterPropertyAssignment",
  "no-undefined": "noUndefined",
  "no-unnecessary-type-constraint": "noUnnecessaryTypeConstraint",
  "no-unneeded-ternary": "noUnneededTernary",
  "no-unsafe-declaration-merging": "noUnsafeDeclarationMerging",
  "no-unsafe-finally": "noUnsafeFinally",
  "no-unsafe-function-type": "noUnsafeFunctionType",
  "no-unsafe-negation": "noUnsafeNegation",
  "no-unused-expressions": "noUnusedExpressions",
  "no-unused-labels": "noUnusedLabels",
  "no-useless-call": "noUselessCall",
  "no-useless-catch": "noUselessCatch",
  "no-useless-computed-key": "noUselessComputedKey",
  "no-useless-concat": "noUselessConcat",
  "no-useless-constructor": "noUselessConstructor",
  "no-useless-empty-export": "noUselessEmptyExport",
  "no-useless-escape": "noUselessEscape",
  "no-useless-rename": "noUselessRename",
  "no-var": "noVar",
  "no-with": "noWith",
  "no-wrapper-object-types": "noWrapperObjectTypes",
  "object-shorthand": "objectShorthand",
  "operator-assignment": "operatorAssignment",
  "method-signature-style": "methodSignatureStyle",
  "prefer-as-const": "preferAsConst",
  "prefer-const": "preferConst",
  "prefer-enum-initializers": "preferEnumInitializers",
  "prefer-exponentiation-operator": "preferExponentiationOperator",
  "prefer-for-of": "preferForOf",
  "prefer-function-type": "preferFunctionType",
  "prefer-literal-enum-member": "preferLiteralEnumMember",
  "prefer-namespace-keyword": "preferNamespaceKeyword",
  "prefer-spread": "preferSpread",
  "prefer-template": "preferTemplate",
  "require-yield": "requireYield",
  "triple-slash-reference": "tripleSlashReference",
  "use-isnan": "useIsNaN",
  "valid-typeof": "validTypeof",
  "vars-on-top": "varsOnTop",
  "format/semi": "formatSemi",
  "format/quotes": "formatQuotes",
  "format/trailing-comma": "formatTrailingComma",
  "format/sort-imports": "formatSortImports",
  "format/jsdoc": "formatJsdoc",
  "format/print-width": "formatPrintWidth",
}

// normalizeBuiltinRuleName maps legacy ESLint/kebab spellings onto the
// camelCase rule IDs used by @ttsc/lint diagnostics and config typing.
func normalizeBuiltinRuleName(name string) string {
  name = strings.TrimSpace(name)
  name = strings.TrimPrefix(name, "@typescript-eslint/")
  name = strings.TrimPrefix(name, "typescript-eslint/")
  name = strings.TrimPrefix(name, "eslint/")
  if canonical, ok := legacyBuiltinRuleNames[name]; ok {
    return canonical
  }
  return name
}

func legacyRuleAlias(name string) string {
  for legacy, canonical := range legacyBuiltinRuleNames {
    if canonical == name {
      return legacy
    }
  }
  return ""
}
