// CLI flag codegen.
//
// Reads `src/flags/FLAG_SCHEMA.ts` and writes the layer-specific artifacts
// derived from it:
//
//   * `cmd/ttsc/flags_gen.go`            — host allow-list (cmd/ttsc + utility)
//   * `../lint/linthost/flags_gen.go`    — lint allow-list (linthost subcommands)
//   * `../../website/src/content/docs/ttsc/flags.mdx` — docs reference table
//   * `src/flags/COMPILER_*.ts` — four single-export native grammar tables
//
// The schema owns launcher allow-lists and documentation. Pinned native Go
// declarations own compiler kinds, operand grammar, name folds and enum whitespace.
// Generation/checks require Go; CLI runtime consumes only the generated tables.
// `pnpm format` uses `--skip-website` to preserve website files while generating
// all compiler and Go tables. `--compiler-options-only` leaves the Go
// allow-lists and website untouched. CI checks all generated targets by default.
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { FLAG_SCHEMA } from "../src/flags/FLAG_SCHEMA.ts";
import type { FlagLayer } from "../src/flags/FlagLayer.ts";
import type { FlagSpec } from "../src/flags/FlagSpec.ts";
import { buildGoAllowList } from "../src/flags/buildGoAllowList.ts";
import { readCompilerOptionTable } from "./readCompilerOptionTable.mts";

const here = path.dirname(fileURLToPath(import.meta.url));
const ttscRoot = path.resolve(here, "..");
const repoRoot = path.resolve(ttscRoot, "../..");
const compilerOptionsOnly = process.argv.includes("--compiler-options-only");
const skipWebsite = process.argv.includes("--skip-website");
const compilerOptions = readCompilerOptionTable();
if (FLAG_SCHEMA.some((flag) =>
  [flag.name, ...(flag.aliases ?? [])].some((name) => !/^[\x00-\x7f]+$/.test(name)),
)) throw new Error("Launcher option names exceeded the ASCII case domain.");

const HEADER = `// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.
//
// Source of truth: packages/ttsc/src/flags/FLAG_SCHEMA.ts.
// Regenerate with:    pnpm format
// Verify in CI with:  node packages/ttsc/scripts/check-flags.cjs

`;

if (!compilerOptionsOnly) {
writeFile(
  path.join(ttscRoot, "cmd/ttsc/flags_gen.go"),
  renderGoMap("main", "HostFlagAllowList", buildGoAllowList("host")),
);

writeFile(
  path.join(ttscRoot, "utility/flags_gen.go"),
  renderGoMap("utility", "HostFlagAllowList", buildGoAllowList("host")),
);

writeFile(
  path.join(repoRoot, "packages/lint/linthost/flags_gen.go"),
  renderGoMap("linthost", "LintFlagAllowList", buildGoAllowList("lint")),
);

if (!skipWebsite) {
  writeFile(
    path.join(repoRoot, "website/src/content/docs/ttsc/flags.mdx"),
    renderDocsTable(FLAG_SCHEMA),
  );
}
}

// Format these generated artifacts with the same formatter as pnpm format, so
// the generator and the drift gate compare its final committed representation.
{
  const { format } = await import("prettier");
  for (const [name, contents] of Object.entries(renderCompilerOptionKinds(compilerOptions))) {
    writeFile(path.join(ttscRoot, `src/flags/${name}.ts`),
      await format(contents, { parser: "typescript" }));
  }
}

/**
 * Render the pinned native parser's full value grammar by normalized identity,
 * preserving list element and configuration-only admission distinctions.
 */
function renderCompilerOptionKinds(
  table: ReturnType<typeof readCompilerOptionTable>,
): Record<string, string> {
  const header = [
    "// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.",
    "// Source of truth: pinned native OptionsDeclarations and OptionsForWatch.",
    "// Regenerate with: pnpm format",
    "// Verify in CI with: node packages/ttsc/scripts/check-flags.cjs",
    "",
  ];
  const rows = [...table.options].map(([name, option]) =>
    `  [${JSON.stringify(name)}, ${JSON.stringify(option)}],`).sort();
  return {
    COMPILER_OPTIONS: [...header,
      'import type { CompilerOptionSpec } from "./CompilerOptionSpec";', "",
      "/** Pinned native option grammar, including alias, list and config-only boundaries. */",
      "export const COMPILER_OPTIONS: ReadonlyMap<string, CompilerOptionSpec> =",
      "  new Map<string, CompilerOptionSpec>([", ...rows, "  ]);", "",
    ].join("\n"),
    COMPILER_OPTION_KINDS: [...header,
      'import { COMPILER_OPTIONS } from "./COMPILER_OPTIONS";', "",
      "/** Compatibility projection for callers that only need nominal kind. */",
      'export const COMPILER_OPTION_KINDS: ReadonlyMap<string, "boolean" | "value"> =',
      '  new Map([...COMPILER_OPTIONS].map(([name, option]) => [name, option.kind === "boolean" ? "boolean" : "value"]));', "",
    ].join("\n"),
    COMPILER_ENUM_WHITESPACE: [...header,
      "/** Native enum-item trimming; distinct from Go list-level TrimSpace. */",
      "export const COMPILER_ENUM_WHITESPACE: ReadonlySet<string> = new Set<string>([",
      ...[...table.enumWhitespace].map(character => `  ${JSON.stringify(character)},`),
      "]);", "",
    ].join("\n"),
    COMPILER_OPTION_ASCII_FOLDS: [...header,
      "/** Native Unicode simple-case folds into the ASCII option-name domain. */",
      "export const COMPILER_OPTION_ASCII_FOLDS: ReadonlyMap<string, string> =",
      "  new Map<string, string>([",
      ...[...table.asciiFolds].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)
        .map(([input, output]) => `    [${JSON.stringify(input)}, ${JSON.stringify(output)}],`),
      "  ]);", "",
    ].join("\n"),
  };
}

/**
 * Render a Go file declaring the named string→bool map that the Go layers'
 * argument filters consult.
 */
function renderGoMap(
  pkg: string,
  name: string,
  entries: Map<string, boolean>,
): string {
  // Deterministic byte-order sort. `localeCompare` is locale-sensitive and
  // could reorder entries differently on a non-en host — generated files
  // live in version control so the comparator must be reproducible.
  const sorted = [...entries.entries()].sort((a, b) =>
    a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0,
  );
  // Emit raw entries; gofmt aligns the `:` and value columns when the file
  // passes through `pnpm format:go`. The schema check script runs gofmt
  // before comparing so a stale alignment is not a drift signal.
  const body = sorted
    .map(([key, takesValue]) => {
      return `  ${JSON.stringify(key)}: ${takesValue ? "true" : "false"},`;
    })
    .join("\n");
  return `${HEADER}package ${pkg}

// ${name} is the allow-list of CLI flags this Go layer accepts. The map's
// value is true when the flag carries a separate value token (--flag VALUE
// or --flag=VALUE) and false when the flag is boolean (--flag).
//
// Generated from packages/ttsc/src/flags/FLAG_SCHEMA.ts. Edit the schema, not
// this file.
var ${name} = map[string]bool{
${body}
}
`;
}

/**
 * Render the Nextra reference table. Lives at website/src/content/docs/
 * ttsc/flags.mdx and is linked from the compile / execute guides.
 */
function renderDocsTable(schema: readonly FlagSpec[]): string {
  const rows = schema
    .map((flag) => {
      const aliases =
        flag.aliases !== undefined && flag.aliases.length > 0
          ? flag.aliases.map((a) => `\`${a}\``).join(", ")
          : "-";
      const subs = flag.subcommands.join(", ");
      const layers = flag.consumedBy
        .map((layer) => layerLabel(layer))
        .join(", ");
      const notes = renderNotes(flag);
      const description = flag.description.replace(/\|/g, "\\|");
      return `| \`${flag.name}\` | ${aliases} | ${flag.kind} | ${subs} | ${layers} | ${notes} | ${description} |`;
    })
    .join("\n");

  // Single MDX comment block so it parses cleanly under MDX2 / Nextra; a
  // line-per-line `{/* … */}` rewrite would produce several openers with one
  // closer and trip strict MDX linters.
  return `{/*
${HEADER.trimEnd()
  .split("\n")
  .map((line) => line.replace(/^\/\/ ?/, ""))
  .join("\n")}
*/}

# ttsc & ttsx CLI flags

For ttsc and ttsx CLI users (command-line, build scripts, CI runners). Plugin
authors should also skim the **Consumed by** column to see which layer reads
each flag.

Single source of truth: \`packages/ttsc/src/flags/FLAG_SCHEMA.ts\`. Each row is one
entry in \`FLAG_SCHEMA\`; the parsing engine, the docs table, and the Go
allow-lists are generated from the same array so a new flag never lands in
one layer and silently disappears at the next boundary.

| Flag | Aliases | Kind | Subcommands | Consumed by | Notes | Description |
| --- | --- | --- | --- | --- | --- | --- |
${rows}

### Reading this table

- **Kind** \`boolean\` flags take no required value; \`value\` flags consume the
  next argv token; \`valueOptional\` keeps a value optional. Launcher-owned
  flags also accept \`--flag=VALUE\`. Flags forwarded to tsgo preserve their
  original spelling, and the pinned tsgo CLI does not support inline
  \`=VALUE\`.
- **Consumed by** lists every layer that reads the flag into its own option
  struct. A flag without a Consumed-by entry is forwarded verbatim to tsgo.
- **Notes** marks structural attributes: \`terminal\` (the flag asks tsgo
  to print and exit), \`project-free\` (a terminal flag ttsc answers without
  resolving a project, so it works in a directory that has no tsconfig yet),
  \`repeatable\` (every occurrence counts, not just the last),
  \`shadow\` (ttsc adds the flag internally; post-processing must not eat a
  user-forwarded copy), and \`capability: ...\` (the flag is delivered to
  native check-stage hosts that opt in via the matching
  \`ITtscPluginCapabilities\` field).

Flag names are matched the way the compiler matches them: case-insensitively,
with one or two leading dashes. \`--noemit\`, \`--NoEmit\`, and \`-noEmit\` are
the same flag to ttsc because they are the same option to tsgo.

Unknown \`-\`-prefixed flags are forwarded to tsgo without registration in
the schema, so adding a flag is only needed for flags ttsc itself consumes,
mutates, or shadows.
`;
}

function layerLabel(layer: FlagLayer): string {
  switch (layer) {
    case "launcher":
      return "launcher";
    case "runBuild":
      return "runBuild";
    case "tsgo":
      return "tsgo";
    case "host":
      return "host";
    case "lint":
      return "lint";
  }
}

function renderNotes(flag: FlagSpec): string {
  const tags: string[] = [];
  if (flag.terminal === true) tags.push("terminal");
  if (flag.projectFree === true) tags.push("project-free");
  if (flag.repeatable === true) tags.push("repeatable");
  if (flag.internalShadow === true) tags.push("shadow");
  if (flag.tsconfigOnly === true) tags.push("tsconfig-only");
  if (flag.nativeCapability !== undefined) {
    tags.push(`capability: ${flag.nativeCapability}`);
  }
  if (
    flag.consumedBy.includes("launcher") &&
    flag.forwardTo === undefined &&
    !flag.consumedBy.includes("tsgo") &&
    !flag.consumedBy.includes("host") &&
    !flag.consumedBy.includes("lint") &&
    !flag.consumedBy.includes("runBuild")
  ) {
    tags.push("consumed-not-forwarded");
  }
  return tags.length === 0 ? "-" : tags.join(", ");
}

function writeFile(target: string, contents: string): void {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents, "utf8");
  // Self-format `.go` outputs so running `node gen-flags.mts` alone is
  // drift-free against the committed copy (which always passes through
  // `pnpm format:go`). Without this, anyone who regenerates outside the
  // `pnpm format` chain sees a noisy whitespace diff. The gofmt wrapper
  // lives at the repo root — fall back silently if it is unavailable.
  if (target.endsWith(".go")) {
    const formatter = path.join(repoRoot, ".vscode", "gofmt-2spaces.sh");
    if (fs.existsSync(formatter)) {
      spawnSync(...shellScriptCommand(formatter, ["-w", target]), {
        stdio: "ignore",
      });
    }
  }
  process.stdout.write(`generated ${path.relative(repoRoot, target)}\n`);
}

function shellScriptCommand(
  script: string,
  args: string[],
): [string, string[]] {
  if (process.platform === "win32") {
    return ["bash", [script, ...args]];
  }
  return [script, args];
}
