// CLI flag codegen.
//
// Reads `src/flags/schema.ts` and writes the layer-specific artifacts that
// were previously hand-maintained:
//
//   * `cmd/ttsc/flags_gen.go`            — host allow-list (cmd/ttsc + utility)
//   * `../lint/linthost/flags_gen.go`    — lint allow-list (linthost subcommands)
//   * `../../website/src/content/docs/ttsc/flags.mdx` — docs reference table
//
// Invoked from `pnpm format` (root `package.json`). Run by Node directly via
// `node --experimental-strip-types`; no separate build step is needed because
// the schema is a plain TypeScript module without runtime dependencies.
//
// Regenerating: the script is idempotent. CI fails when committed output drifts
// from `schema.ts` — see `scripts/check-flags.cjs`.

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import {
  FLAG_SCHEMA,
  buildGoAllowList,
  type FlagLayer,
  type FlagSpec,
} from "../src/flags/schema.ts";

const here = path.dirname(fileURLToPath(import.meta.url));
const ttscRoot = path.resolve(here, "..");
const repoRoot = path.resolve(ttscRoot, "../..");

const HEADER = `// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.
//
// Source of truth: packages/ttsc/src/flags/schema.ts.
// Regenerate with:    pnpm format
// Verify in CI with:  node packages/ttsc/scripts/check-flags.cjs

`;

writeFile(
  path.join(ttscRoot, "cmd/ttsc/flags_gen.go"),
  renderGoMap("main", "HostFlagAllowList", buildGoAllowList("host")),
);

writeFile(
  path.join(ttscRoot, "utility/flags_gen.go"),
  renderGoMap("utility", "HostFlagAllowList", buildGoAllowList("host")),
);

writeFile(
  path.join(repoRoot, "packages/lint/linthost/flags_gen.go"),
  renderGoMap("linthost", "LintFlagAllowList", buildGoAllowList("lint")),
);

writeFile(
  path.join(repoRoot, "website/src/content/docs/ttsc/flags.mdx"),
  renderDocsTable(FLAG_SCHEMA),
);

/**
 * Render a Go file declaring the named string→bool map. The shape is the same
 * the legacy `filterHostArgs` / `filterKnownFlags` literal maps used.
 */
function renderGoMap(
  pkg: string,
  name: string,
  entries: Map<string, boolean>,
): string {
  const sorted = [...entries.entries()].sort((a, b) =>
    a[0].localeCompare(b[0]),
  );
  // Emit raw entries; gofmt aligns the `:` and value columns when the file
  // passes through `pnpm format:go`. The schema check script runs gofmt
  // before comparing so a stale alignment is not a drift signal.
  const body = sorted
    .map(([key, takesValue]) => {
      return `  ${JSON.stringify(key)}: ${takesValue ? "true" : "false"},`;
    })
    .join("\n");
  return `${HEADER}package ${pkg}

// ${name} is the allow-list of CLI flags this Go layer accepts. The map's
// value is true when the flag carries a separate value token (--flag VALUE
// or --flag=VALUE) and false when the flag is boolean (--flag).
//
// Generated from packages/ttsc/src/flags/schema.ts. Edit the schema, not
// this file.
var ${name} = map[string]bool{
${body}
}
`;
}

/**
 * Render the Nextra reference table. Lives at website/src/content/docs/
 * ttsc/flags.mdx and is linked from the compile / execute guides.
 */
function renderDocsTable(schema: readonly FlagSpec[]): string {
  const rows = schema
    .map((flag) => {
      const aliases =
        flag.aliases !== undefined && flag.aliases.length > 0
          ? flag.aliases.map((a) => `\`${a}\``).join(", ")
          : "—";
      const subs = flag.subcommands.join(", ");
      const layers = flag.consumedBy
        .map((layer) => layerLabel(layer))
        .join(", ");
      const notes = renderNotes(flag);
      const description = flag.description.replace(/\|/g, "\\|");
      return `| \`${flag.name}\` | ${aliases} | ${flag.kind} | ${subs} | ${layers} | ${notes} | ${description} |`;
    })
    .join("\n");

  return `${HEADER.replace(/^\/\//gm, "{/*").trimEnd()} */}

# ttsc & ttsx CLI flags

Single source of truth: \`packages/ttsc/src/flags/schema.ts\`. Each row is one
entry in \`FLAG_SCHEMA\`; the parsing engine, the docs table, and the Go
allow-lists are generated from the same array so a new flag never lands in
one layer and silently disappears at the next boundary.

| Flag | Aliases | Kind | Subcommands | Consumed by | Notes | Description |
| --- | --- | --- | --- | --- | --- | --- |
${rows}

### Reading this table

- **Kind** \`boolean\` flags take no value; \`value\` flags consume the next
  argv token (or accept \`--flag=VALUE\`); \`valueOptional\` keeps a value
  optional.
- **Consumed by** lists every layer that reads the flag into its own option
  struct. A flag without a Consumed-by entry is forwarded verbatim to tsgo.
- **Notes** marks structural attributes — \`terminal\` (the flag asks tsgo
  to print and exit), \`shadow\` (ttsc adds the flag internally; post-
  processing must not eat a user-forwarded copy), and
  \`capability: threadingArgs\` (the flag is delivered to native check-stage
  hosts that opt in via \`ITtscPluginCapabilities.threadingArgs\`).

Unknown \`-\`-prefixed flags are forwarded to tsgo without registration in
the schema, so adding a flag is only needed for flags ttsc itself consumes,
mutates, or shadows.
`;
}

function layerLabel(layer: FlagLayer): string {
  switch (layer) {
    case "launcher":
      return "launcher";
    case "runBuild":
      return "runBuild";
    case "tsgo":
      return "tsgo";
    case "host":
      return "host";
    case "lint":
      return "lint";
  }
}

function renderNotes(flag: FlagSpec): string {
  const tags: string[] = [];
  if (flag.terminal === true) tags.push("terminal");
  if (flag.internalShadow === true) tags.push("shadow");
  if (flag.nativeCapability !== undefined) {
    tags.push(`capability: ${flag.nativeCapability}`);
  }
  if (
    flag.consumedBy.includes("launcher") &&
    flag.forwardTo === undefined &&
    !flag.consumedBy.includes("tsgo") &&
    !flag.consumedBy.includes("host") &&
    !flag.consumedBy.includes("lint") &&
    !flag.consumedBy.includes("runBuild")
  ) {
    tags.push("consumed-not-forwarded");
  }
  return tags.length === 0 ? "—" : tags.join(", ");
}

function writeFile(target: string, contents: string): void {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents, "utf8");
  process.stdout.write(`generated ${path.relative(repoRoot, target)}\n`);
}
