import { RESOLUTION_INPUT_RECORDER_PATH } from "./RESOLUTION_INPUT_RECORDER_PATH";

/**
 * CommonJS evaluator emitted into a clean Node process for every load.
 *
 * What the descriptor's resolutions read is recorded by the resolution input
 * recorder (`RESOLUTION_INPUT_RECORDER_PATH`), required before any hook is
 * installed so the recorder itself is no input, and bracketing every resolution
 * the hooks see (samchon/ttsc#1501).
 */
export const COMMONJS_PLUGIN_DESCRIPTOR_SHIM_SOURCE = [
  `const fs = require("node:fs");`,
  `const Module = require("node:module");`,
  `const path = require("node:path");`,
  `const { fileURLToPath } = require("node:url");`,
  `const { createResolutionInputRecorder } = require(${JSON.stringify(RESOLUTION_INPUT_RECORDER_PATH)});`,
  `const out = process.env.TTSC_PLUGIN_DESCRIPTOR_OUT;`,
  `let retryWithTtsx = false;`,
  `const moduleLoadFailures = new WeakMap();`,
  `const moduleResolutionFailures = new WeakMap();`,
  `function existingFile(file) { try { return fs.statSync(file).isFile(); } catch { return false; } }`,
  `function shouldRetryWithTtsx(error) {`,
  `  const loadFailure = error && (typeof error === "object" || typeof error === "function") ? moduleLoadFailures.get(error) : undefined;`,
  `  if (loadFailure?.retryWithTtsx === true) return true;`,
  `  const failure = error && (typeof error === "object" || typeof error === "function") ? moduleResolutionFailures.get(error) : undefined;`,
  `  return failure?.retryWithTtsx === true;`,
  `}`,
  `try {`,
  `  const request = process.env.TTSC_PLUGIN_ENTRY;`,
  `  const context = JSON.parse(process.env.TTSC_PLUGIN_CONTEXT);`,
  `  const recorder = createResolutionInputRecorder({ extensions: typeof globalThis.Bun === "object" ? [".tsx", ".jsx", ".ts", ".mjs", ".js", ".cjs", ".json"] : [".ts", ".tsx", ".mts", ".cts", ".js", ".mjs", ".cjs", ".json", ".node"] });`,
  `  function asFile(resolved) {`,
  `    if (typeof resolved !== "string") return undefined;`,
  `    if (!resolved.startsWith("file:")) return path.isAbsolute(resolved) ? path.resolve(resolved) : undefined;`,
  `    try { return path.resolve(fileURLToPath(resolved)); } catch { return undefined; }`,
  `  }`,
  `  recorder.recordFile(request);`,
  `  function scanBunModuleGraph(entry) {`,
  `    if (typeof globalThis.Bun !== "object" || typeof globalThis.Bun.Transpiler !== "function") return;`,
  `    const scanned = new Set();`,
  `    function scan(file) {`,
  `      file = asFile(file);`,
  `      if (file === undefined) return;`,
  `      let canonical;`,
  `      try { canonical = fs.realpathSync.native(file); } catch { return; }`,
  `      if (scanned.has(canonical)) return;`,
  `      scanned.add(canonical);`,
  `      const extension = path.extname(canonical).toLowerCase();`,
  `      if (![".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts"].includes(extension)) return;`,
  `      const loader = extension === ".tsx" ? "tsx" : extension === ".jsx" ? "jsx" : [".ts", ".mts", ".cts"].includes(extension) ? "ts" : "js";`,
  `      let imports;`,
  `      try {`,
  `        const source = fs.readFileSync(canonical, "utf8");`,
  `        imports = new globalThis.Bun.Transpiler({ loader }).scan(source).imports;`,
  `      } catch { return; }`,
  `      for (const imported of imports) {`,
  `        const specifier = imported && imported.path;`,
  `        if (typeof specifier !== "string" || specifier.startsWith("node:") || Module.isBuiltin(specifier)) continue;`,
  `        const resolution = recorder.beginResolution(specifier, canonical);`,
  `        let resolved;`,
  `        try {`,
  `          resolved = globalThis.Bun.resolveSync(specifier, path.dirname(canonical));`,
  `        } catch {`,
  `          // The real descriptor load below owns user-facing resolution errors.`,
  `        }`,
  `        recorder.endResolution(resolution, resolved);`,
  `        if (resolved !== undefined) scan(resolved);`,
  `      }`,
  `    }`,
  `    scan(entry);`,
  `  }`,
  `  if (typeof Module.registerHooks === "function") {`,
  `    Module.registerHooks({`,
  `      load(url, loadContext, nextLoad) {`,
  `        try { return nextLoad(url, loadContext); }`,
  `        catch (error) {`,
  `          if (error && (typeof error === "object" || typeof error === "function")) moduleLoadFailures.set(error, { retryWithTtsx: error.code === "ERR_UNKNOWN_FILE_EXTENSION" });`,
  `          throw error;`,
  `        }`,
  `      },`,
  `      resolve(specifier, resolveContext, nextResolve) {`,
  `        const resolution = recorder.beginResolution(specifier, resolveContext.parentURL);`,
  `        let resolved;`,
  `        try {`,
  `          resolved = nextResolve(specifier, resolveContext);`,
  `        } catch (error) {`,
  `          recorder.endResolution(resolution, undefined);`,
  `          if (error && (typeof error === "object" || typeof error === "function")) {`,
  `            const parent = asFile(resolveContext.parentURL);`,
  `            const anchor = typeof parent === "string" ? parent : request;`,
  `            const candidate = specifier.startsWith(".") && path.extname(specifier) === "" ? path.resolve(path.dirname(anchor), specifier) : undefined;`,
  `            const retryWithTtsx = candidate !== undefined && [".ts", ".cts", ".mts", ".tsx"].some((extension) => existingFile(candidate + extension) || existingFile(path.join(candidate, "index" + extension)));`,
  `            moduleResolutionFailures.set(error, { retryWithTtsx });`,
  `          }`,
  `          throw error;`,
  `        }`,
  `        recorder.endResolution(resolution, typeof resolved === "string" ? resolved : resolved && resolved.url);`,
  `        return resolved;`,
  `      },`,
  `    });`,
  `  }`,
  `  if (typeof globalThis.Bun === "object" && typeof globalThis.Bun.plugin === "function") {`,
  `    let insideBunResolve = false;`,
  `    globalThis.Bun.plugin({`,
  `      name: "ttsc-plugin-descriptor-inputs",`,
  `      setup(build) {`,
  `        build.onResolve({ filter: /.*/ }, (args) => {`,
  `          if (insideBunResolve || args.path.startsWith("node:")) return;`,
  `          try {`,
  `            insideBunResolve = true;`,
  `            const importer = args.importer && args.importer.startsWith("file:") ? fileURLToPath(args.importer) : args.importer;`,
  `            const from = importer ? path.dirname(importer) : process.cwd();`,
  `            const resolution = recorder.beginResolution(args.path, importer);`,
  `            let resolved;`,
  `            try {`,
  `              resolved = globalThis.Bun.resolveSync(args.path, from);`,
  `            } finally {`,
  `              recorder.endResolution(resolution, resolved);`,
  `            }`,
  `          } catch {`,
  `            // The real resolver below owns user-facing resolution errors.`,
  `          } finally {`,
  `            insideBunResolve = false;`,
  `          }`,
  `        });`,
  `      },`,
  `    });`,
  `  }`,
  `  scanBunModuleGraph(request);`,
  `  let mod;`,
  `  try {`,
  `    mod = require(request);`,
  `  } catch (error) {`,
  `    retryWithTtsx = shouldRetryWithTtsx(error);`,
  `    throw error;`,
  `  }`,
  `  const candidate = mod.createTtscPlugin ?? mod.default ?? mod.plugin ?? mod;`,
  `  const descriptor = typeof candidate === "function" ? candidate(context) : candidate;`,
  `  if (descriptor && typeof descriptor === "object" && ("transformSource" in descriptor || "transformOutput" in descriptor)) {`,
  `    throw new Error("ttsc: plugin descriptor declares unsupported JS transform functions; declare a native backend instead");`,
  `  }`,
  // Serialize the descriptor while the module-resolution hooks are still
  // collecting. Getters are allowed by JavaScript's object model and can
  // lazily require a config; snapshotting inputs first would silently omit
  // that influence.
  `  const serializedDescriptor = JSON.stringify(descriptor);`,
  `  const recorded = recorder.finish();`,
  `  const payload = { inputHashes: recorded.hashes, inputRealpaths: recorded.realpaths, inputs: recorded.inputs };`,
  `  if (serializedDescriptor !== undefined) payload.descriptor = JSON.parse(serializedDescriptor);`,
  `  fs.writeFileSync(out, JSON.stringify(payload));`,
  `} catch (error) {`,
  `  const message = error instanceof Error ? error.message : String(error);`,
  `  const stack = error instanceof Error && error.stack ? error.stack : String(error);`,
  `  try {`,
  `    fs.writeFileSync(out, JSON.stringify({ __ttscLoaderError: message, __ttscRetryWithTtsx: retryWithTtsx }));`,
  `  } catch {}`,
  `  try { process.stderr.write(stack + "\\n"); } catch {}`,
  `  process.exit(1);`,
  `}`,
  ``,
].join("\n");
