/** CommonJS evaluator emitted into a clean Node process for every load. */
export const COMMONJS_PLUGIN_DESCRIPTOR_SHIM_SOURCE = [
  `const crypto = require("node:crypto");`,
  `const fs = require("node:fs");`,
  `const Module = require("node:module");`,
  `const path = require("node:path");`,
  `const { fileURLToPath } = require("node:url");`,
  `const out = process.env.TTSC_PLUGIN_DESCRIPTOR_OUT;`,
  `let retryWithTtsx = false;`,
  `const moduleLoadFailures = new WeakMap();`,
  `const moduleResolutionFailures = new WeakMap();`,
  `function existingFile(file) { try { return fs.statSync(file).isFile(); } catch { return false; } }`,
  `function shouldRetryWithTtsx(error) {`,
  `  const loadFailure = error && (typeof error === "object" || typeof error === "function") ? moduleLoadFailures.get(error) : undefined;`,
  `  if (loadFailure?.retryWithTtsx === true) return true;`,
  `  const failure = error && (typeof error === "object" || typeof error === "function") ? moduleResolutionFailures.get(error) : undefined;`,
  `  return failure?.retryWithTtsx === true;`,
  `}`,
  `try {`,
  `  const request = process.env.TTSC_PLUGIN_ENTRY;`,
  `  const context = JSON.parse(process.env.TTSC_PLUGIN_CONTEXT);`,
  `  const inputs = new Set();`,
  `  const inputHashes = new Map();`,
  `  const inputRealpaths = new Map();`,
  `  const inputSignatures = new Map();`,
  `  const unstableInputHashes = new Set();`,
  `  function missingPathError(error) { return error && (error.code === "ENOENT" || error.code === "ENOTDIR"); }`,
  `  function inputMetadataSignature(file) {`,
  `    const requested = path.resolve(file);`,
  `    let current = requested;`,
  `    for (;;) {`,
  `      try {`,
  `        const link = fs.lstatSync(current, { bigint: true });`,
  `        let target = link;`,
  `        if (link.isSymbolicLink()) {`,
  `          try { target = fs.statSync(current, { bigint: true }); }`,
  `          catch { return undefined; }`,
  `        }`,
  `        return [path.relative(current, requested), link.dev, link.ino, link.mode, link.size, link.mtimeNs, link.ctimeNs, target.dev, target.ino, target.mode, target.size, target.mtimeNs, target.ctimeNs].join(":");`,
  `      } catch (error) {`,
  `        if (!missingPathError(error)) return undefined;`,
  `        const parent = path.dirname(current);`,
  `        if (parent === current) return undefined;`,
  `        current = parent;`,
  `      }`,
  `    }`,
  `  }`,
  `  function recordOneInput(file) {`,
  `    file = path.resolve(file);`,
  `    inputs.add(file);`,
  `    if (unstableInputHashes.has(file)) return;`,
  `    const beforeSignature = inputMetadataSignature(file);`,
  `    let observedRealpath;`,
  `    try { observedRealpath = fs.realpathSync.native(file); } catch { observedRealpath = null; }`,
  `    let observed;`,
  `    try { observed = fs.statSync(file).isDirectory() ? crypto.createHash("sha256").update("ttsc:host-input:directory\\0").digest("hex") : crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); } catch { observed = null; }`,
  `    const afterSignature = inputMetadataSignature(file);`,
  `    if (beforeSignature === undefined || afterSignature === undefined || beforeSignature !== afterSignature || (inputSignatures.has(file) && inputSignatures.get(file) !== afterSignature) || (inputRealpaths.has(file) && inputRealpaths.get(file) !== observedRealpath) || (inputHashes.has(file) && inputHashes.get(file) !== observed)) { inputHashes.delete(file); inputRealpaths.delete(file); inputSignatures.delete(file); unstableInputHashes.add(file); return; }`,
  `    inputSignatures.set(file, afterSignature);`,
  `    inputRealpaths.set(file, observedRealpath);`,
  `    inputHashes.set(file, observed);`,
  `  }`,
  `  function recordInput(file) {`,
  `    file = path.resolve(file);`,
  `    recordOneInput(file);`,
  `    const parsed = path.parse(file);`,
  `    let current = parsed.root;`,
  `    const relative = path.relative(parsed.root, file);`,
  `    for (const segment of relative.split(path.sep).slice(0, -1)) {`,
  `      if (segment === "") continue;`,
  `      current = path.join(current, segment);`,
  `      try {`,
  `        if (fs.lstatSync(current).isSymbolicLink()) recordOneInput(current);`,
  `      } catch {`,
  `        break;`,
  `      }`,
  `    }`,
  `  }`,
  `  function asFile(resolved) {`,
  `    if (typeof resolved !== "string") return undefined;`,
  `    if (!resolved.startsWith("file:")) return path.isAbsolute(resolved) ? path.resolve(resolved) : undefined;`,
  `    try { return path.resolve(fileURLToPath(resolved)); } catch { return undefined; }`,
  `  }`,
  `  function recordFile(resolved) {`,
  `    const file = asFile(resolved);`,
  `    if (file === undefined) return;`,
  `    recordInput(file);`,
  `    for (let directory = path.dirname(file);;) {`,
  `      const manifest = path.join(directory, "package.json");`,
  `      recordInput(manifest);`,
  `      if (existingFile(manifest)) break;`,
  `      const parent = path.dirname(directory);`,
  `      if (parent === directory) break;`,
  `      directory = parent;`,
  `    }`,
  `  }`,
  `  function recordPackageManifests(file) {`,
  `    for (let directory = path.dirname(path.resolve(file));;) {`,
  `      const manifest = path.join(directory, "package.json");`,
  `      recordInput(manifest);`,
  `      if (existingFile(manifest)) return;`,
  `      const parent = path.dirname(directory);`,
  `      if (parent === directory) return;`,
  `      directory = parent;`,
  `    }`,
  `  }`,
  `  recordFile(request);`,
  `  const moduleProbeExtensions = typeof globalThis.Bun === "object" ? [".tsx", ".jsx", ".ts", ".mjs", ".js", ".cjs", ".json"] : [".ts", ".tsx", ".mts", ".cts", ".js", ".mjs", ".cjs", ".json", ".node"];`,
  `  const jsToTsProbeExtensions = new Map([[".js", [".ts", ".tsx"]], [".jsx", [".tsx"]], [".mjs", [".mts"]], [".cjs", [".cts"]]]);`,
  `  function sourceSubstitutionCandidates(base) {`,
  `    const extension = path.extname(base).toLowerCase();`,
  `    const substitutions = jsToTsProbeExtensions.get(extension);`,
  `    if (substitutions === undefined) return [];`,
  `    const stem = base.slice(0, base.length - extension.length);`,
  `    return substitutions.map((candidate) => stem + candidate);`,
  `  }`,
  `  function moduleCandidates(base) {`,
  `    return [base, ...sourceSubstitutionCandidates(base), ...moduleProbeExtensions.map((extension) => base + extension), path.join(base, "package.json"), ...moduleProbeExtensions.map((extension) => path.join(base, "index" + extension))];`,
  `  }`,
  `  const recordedModuleBases = new Set();`,
  `  function recordManifestTargets(value, directory, allowBare = false) {`,
  `    if (typeof value === "string") {`,
  `      if (value !== "" && (allowBare || value.startsWith("./") || value.startsWith("../"))) recordModuleCandidates(path.resolve(directory, value));`,
  `      return;`,
  `    }`,
  `    if (Array.isArray(value)) { for (const item of value) recordManifestTargets(item, directory, allowBare); return; }`,
  `    if (value && typeof value === "object") for (const item of Object.values(value)) recordManifestTargets(item, directory, allowBare);`,
  `  }`,
  `  function recordModuleCandidates(base) {`,
  `    const resolvedBase = path.resolve(base);`,
  `    if (recordedModuleBases.has(resolvedBase)) return;`,
  `    recordedModuleBases.add(resolvedBase);`,
  `    for (const candidate of moduleCandidates(resolvedBase)) recordInput(candidate);`,
  `    try {`,
  `      const manifest = JSON.parse(fs.readFileSync(path.join(resolvedBase, "package.json"), "utf8").replace(/^\uFEFF/, ""));`,
  `      recordManifestTargets(manifest.exports, resolvedBase);`,
  `      recordManifestTargets(manifest.module, resolvedBase, true);`,
  `      recordManifestTargets(manifest.main, resolvedBase, true);`,
  `    } catch {}`,
  `  }`,
  `  function candidateSelected(base, selected) {`,
  `    if (selected === undefined) return false;`,
  `    for (const candidate of moduleCandidates(base)) {`,
  `      try {`,
  `        const canonical = fs.realpathSync.native(candidate);`,
  `        const relative = path.relative(canonical, selected);`,
  `        if (relative === "" || (fs.statSync(canonical).isDirectory() && relative !== ".." && !relative.startsWith(".." + path.sep) && !path.isAbsolute(relative))) return true;`,
  `      } catch {}`,
  `    }`,
  `    return false;`,
  `  }`,
  `  function localBases(specifier, parentFile) {`,
  `    if (specifier.startsWith("file:")) return [fileURLToPath(specifier)];`,
  `    const directory = path.dirname(parentFile);`,
  `    const raw = path.resolve(directory, specifier);`,
  `    const suffixStart = specifier.search(/[?#]/);`,
  `    if (suffixStart === -1) return [raw];`,
  `    const pathname = specifier.slice(0, suffixStart);`,
  `    return pathname === "" ? [raw] : [...new Set([raw, path.resolve(directory, pathname)])];`,
  `  }`,
  `  function recordResolutionCandidates(specifier, parent, resolved) {`,
  `    const parentFile = asFile(parent);`,
  `    if (typeof specifier !== "string" || parentFile === undefined) return;`,
  `    let selected;`,
  `    try { const file = asFile(resolved); selected = file === undefined ? undefined : fs.realpathSync.native(file); } catch {}`,
  `    if (specifier.startsWith(".") || path.isAbsolute(specifier) || specifier.startsWith("file:")) {`,
  `      try {`,
  `        for (const base of localBases(specifier, parentFile)) {`,
  `          recordPackageManifests(base);`,
  `          let exact = false;`,
  `          try { exact = selected === undefined ? fs.statSync(base).isFile() : fs.realpathSync.native(base) === selected; } catch {}`,
  `          if (exact) recordInput(base);`,
  `          if (!exact) recordModuleCandidates(base);`,
  `        }`,
  `      } catch {}`,
  `      return;`,
  `    }`,
  `    if (Module.isBuiltin(specifier) || specifier.startsWith("#")) return;`,
  `    const parts = specifier.split("/");`,
  `    const packageParts = parts[0].startsWith("@") ? parts.slice(0, 2) : parts.slice(0, 1);`,
  `    if (packageParts.some((part) => part === undefined || part === "")) return;`,
  `    const packageName = packageParts.join("/");`,
  `    const subpath = parts.slice(packageParts.length);`,
  `    const searchPaths = Module.createRequire(parentFile).resolve.paths(specifier) ?? [];`,
  `    for (const searchPath of searchPaths) {`,
  `      const packageDirectory = path.join(searchPath, packageName);`,
  `      recordModuleCandidates(packageDirectory);`,
  `      if (subpath.length !== 0) recordModuleCandidates(path.join(packageDirectory, ...subpath));`,
  `      if (candidateSelected(packageDirectory, selected)) break;`,
  `    }`,
  `  }`,
  `  function scanBunModuleGraph(entry) {`,
  `    if (typeof globalThis.Bun !== "object" || typeof globalThis.Bun.Transpiler !== "function") return;`,
  `    const scanned = new Set();`,
  `    function scan(file) {`,
  `      file = asFile(file);`,
  `      if (file === undefined) return;`,
  `      let canonical;`,
  `      try { canonical = fs.realpathSync.native(file); } catch { return; }`,
  `      if (scanned.has(canonical)) return;`,
  `      scanned.add(canonical);`,
  `      const extension = path.extname(canonical).toLowerCase();`,
  `      if (![".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts"].includes(extension)) return;`,
  `      const loader = extension === ".tsx" ? "tsx" : extension === ".jsx" ? "jsx" : [".ts", ".mts", ".cts"].includes(extension) ? "ts" : "js";`,
  `      let imports;`,
  `      try {`,
  `        const source = fs.readFileSync(canonical, "utf8");`,
  `        imports = new globalThis.Bun.Transpiler({ loader }).scan(source).imports;`,
  `      } catch { return; }`,
  `      for (const imported of imports) {`,
  `        const specifier = imported && imported.path;`,
  `        if (typeof specifier !== "string" || specifier.startsWith("node:") || Module.isBuiltin(specifier)) continue;`,
  `        recordResolutionCandidates(specifier, canonical, undefined);`,
  `        try {`,
  `          const resolved = globalThis.Bun.resolveSync(specifier, path.dirname(canonical));`,
  `          recordResolutionCandidates(specifier, canonical, resolved);`,
  `          recordFile(resolved);`,
  `          scan(resolved);`,
  `        } catch {`,
  `          // The real descriptor load below owns user-facing resolution errors.`,
  `        }`,
  `      }`,
  `    }`,
  `    scan(entry);`,
  `  }`,
  `  if (typeof Module.registerHooks === "function") {`,
  `    Module.registerHooks({`,
  `      load(url, loadContext, nextLoad) {`,
  `        try { return nextLoad(url, loadContext); }`,
  `        catch (error) {`,
  `          if (error && (typeof error === "object" || typeof error === "function")) moduleLoadFailures.set(error, { retryWithTtsx: error.code === "ERR_UNKNOWN_FILE_EXTENSION" });`,
  `          throw error;`,
  `        }`,
  `      },`,
  `      resolve(specifier, resolveContext, nextResolve) {`,
  `        recordResolutionCandidates(specifier, resolveContext.parentURL, undefined);`,
  `        let resolved;`,
  `        try {`,
  `          resolved = nextResolve(specifier, resolveContext);`,
  `        } catch (error) {`,
  `          if (error && (typeof error === "object" || typeof error === "function")) {`,
  `            const parent = asFile(resolveContext.parentURL);`,
  `            const anchor = typeof parent === "string" ? parent : request;`,
  `            const candidate = specifier.startsWith(".") && path.extname(specifier) === "" ? path.resolve(path.dirname(anchor), specifier) : undefined;`,
  `            const retryWithTtsx = candidate !== undefined && [".ts", ".cts", ".mts", ".tsx"].some((extension) => existingFile(candidate + extension) || existingFile(path.join(candidate, "index" + extension)));`,
  `            moduleResolutionFailures.set(error, { retryWithTtsx });`,
  `          }`,
  `          throw error;`,
  `        }`,
  `        const url = typeof resolved === "string" ? resolved : resolved && resolved.url;`,
  `        recordResolutionCandidates(specifier, resolveContext.parentURL, url);`,
  `        recordFile(url);`,
  `        return resolved;`,
  `      },`,
  `    });`,
  `  }`,
  `  if (typeof globalThis.Bun === "object" && typeof globalThis.Bun.plugin === "function") {`,
  `    let insideBunResolve = false;`,
  `    globalThis.Bun.plugin({`,
  `      name: "ttsc-plugin-descriptor-inputs",`,
  `      setup(build) {`,
  `        build.onResolve({ filter: /.*/ }, (args) => {`,
  `          if (insideBunResolve || args.path.startsWith("node:")) return;`,
  `          try {`,
  `            insideBunResolve = true;`,
  `            const importer = args.importer && args.importer.startsWith("file:") ? fileURLToPath(args.importer) : args.importer;`,
  `            const from = importer ? path.dirname(importer) : process.cwd();`,
  `            recordResolutionCandidates(args.path, importer, undefined);`,
  `            const resolved = globalThis.Bun.resolveSync(args.path, from);`,
  `            recordResolutionCandidates(args.path, importer, resolved);`,
  `            recordFile(resolved);`,
  `          } catch {`,
  `            // The real resolver below owns user-facing resolution errors.`,
  `          } finally {`,
  `            insideBunResolve = false;`,
  `          }`,
  `        });`,
  `      },`,
  `    });`,
  `  }`,
  `  scanBunModuleGraph(request);`,
  `  let mod;`,
  `  try {`,
  `    mod = require(request);`,
  `  } catch (error) {`,
  `    retryWithTtsx = shouldRetryWithTtsx(error);`,
  `    throw error;`,
  `  }`,
  `  const candidate = mod.createTtscPlugin ?? mod.default ?? mod.plugin ?? mod;`,
  `  const descriptor = typeof candidate === "function" ? candidate(context) : candidate;`,
  `  if (descriptor && typeof descriptor === "object" && ("transformSource" in descriptor || "transformOutput" in descriptor)) {`,
  `    throw new Error("ttsc: plugin descriptor declares unsupported JS transform functions; declare a native backend instead");`,
  `  }`,
  // Serialize the descriptor while the module-resolution hooks are still
  // collecting. Getters are allowed by JavaScript's object model and can
  // lazily require a config; snapshotting inputs first would silently omit
  // that influence.
  `  const serializedDescriptor = JSON.stringify(descriptor);`,
  `  for (const input of [...inputs]) recordInput(input);`,
  `  const payload = { inputHashes: Object.fromEntries(inputHashes), inputRealpaths: Object.fromEntries(inputRealpaths), inputs: [...inputs].sort() };`,
  `  if (serializedDescriptor !== undefined) payload.descriptor = JSON.parse(serializedDescriptor);`,
  `  fs.writeFileSync(out, JSON.stringify(payload));`,
  `} catch (error) {`,
  `  const message = error instanceof Error ? error.message : String(error);`,
  `  const stack = error instanceof Error && error.stack ? error.stack : String(error);`,
  `  try {`,
  `    fs.writeFileSync(out, JSON.stringify({ __ttscLoaderError: message, __ttscRetryWithTtsx: retryWithTtsx }));`,
  `  } catch {}`,
  `  try { process.stderr.write(stack + "\\n"); } catch {}`,
  `  process.exit(1);`,
  `}`,
  ``,
].join("\n");
