package lspserver

import (
  "sync"
  "testing"
)

// TestLSPHintsRefreshServesCompletionWhileRunning pins the reader's view during
// a refresh.
//
// Two writer and four reader goroutines exercise actual cache stores/accessors.
// Each observed snapshot must have the expected count, manifest order, scope
// and an allowed insertion per producer. Scheduling does not guarantee a
// particular read/write interleaving, and this unit does not observe editor
// typing, native producer refresh or a race-detector result.
//
//  1. Seed two producers so a torn snapshot is distinguishable from a whole one.
//  2. Rewrite both producers' corpora repeatedly while readers ask for them.
//  3. Assert selected fields of every observed snapshot against literal expectations.
//
// @evidence contracts/testing.md#behavioral-verification Actual cache stores and Proxy hint accessors run in two writer/four reader goroutines. Each observed snapshot has two hints in literal trigger order, each with scope jsdoc and one item whose insertion is the producer's initial value or refreshed. The unit joins its goroutines and reports collected failures; unobserved interleavings, other fields and a race-detector result are not certified.
// @evidence contracts/testing.md#independent-expectations Count two, trigger order @ then @evidence-space, scope jsdoc and allowed insertion pairs param/refreshed and docs/rfc.md/refreshed are authored literals, not values generated by the store or accessor.
// @evidence contracts/testing.md#distinguishing-cases Two producers with distinguishable corpora make a torn snapshot detectable.
// @evidence contracts/testing.md#execution-ownership This Go unit invokes actual NativePluginSource cache storage and Proxy hint accessors on owned entries/corpora and waits for both goroutine groups. Binary/name are opaque cache metadata, not executable selection; no directory, sidecar, compiler, process, host or LSP transport runs, and no operation is substituted. Runtime/race-mode selection remains unverified.
func TestLSPHintsRefreshServesCompletionWhileRunning(t *testing.T) {
  first := NativeLSPPluginEntry{Binary: "ttsc-lint", Name: "@ttsc/lint"}
  second := NativeLSPPluginEntry{Binary: "ttsc-evidence", Name: "@samchon/evidence"}
  source := &NativePluginSource{plugins: []NativeLSPPluginEntry{first, second}}
  proxy := &Proxy{source: source}

  corpus := func(plugin NativeLSPPluginEntry, insert string) []LSPCompletionHint {
    after := "@"
    if plugin.Binary == second.Binary {
      after = "@evidence "
    }
    return []LSPCompletionHint{
      {Scope: "jsdoc", After: after, Items: []LSPCompletionItem{{Insert: insert}}},
    }
  }
  source.storeCompletionHints(first, 1, corpus(first, "param"))
  source.storeCompletionHints(second, 1, corpus(second, "docs/rfc.md"))

  const cycles = 200
  var writers sync.WaitGroup
  writers.Add(2)
  for _, plugin := range []NativeLSPPluginEntry{first, second} {
    go func(plugin NativeLSPPluginEntry) {
      defer writers.Done()
      for generation := uint64(2); generation < cycles; generation++ {
        source.storeCompletionHints(plugin, generation, corpus(plugin, "refreshed"))
      }
    }(plugin)
  }

  var readers sync.WaitGroup
  failures := make(chan string, 16)
  for reader := 0; reader < 4; reader++ {
    readers.Add(1)
    go func() {
      defer readers.Done()
      for i := 0; i < cycles; i++ {
        hints := proxy.pluginCompletionHints()
        if len(hints) != 2 {
          select {
          case failures <- "a completion request saw a partially rebuilt corpus":
          default:
          }
          return
        }
        if hints[0].After != "@" || hints[1].After != "@evidence " {
          select {
          case failures <- "a completion request saw producers out of manifest order":
          default:
          }
          return
        }
        for index, hint := range hints {
          if len(hint.Items) != 1 || hint.Items[0].Insert == "" {
            select {
            case failures <- "a completion request saw an empty hint group":
            default:
            }
            return
          }
          if hint.Scope != "jsdoc" ||
            (index == 0 && hint.Items[0].Insert != "param" && hint.Items[0].Insert != "refreshed") ||
            (index == 1 && hint.Items[0].Insert != "docs/rfc.md" && hint.Items[0].Insert != "refreshed") {
            select {
            case failures <- "a snapshot contained scope or insertion outside the literal producer corpus":
            default:
            }
            return
          }
        }
      }
    }()
  }
  writers.Wait()
  readers.Wait()
  close(failures)
  for failure := range failures {
    t.Error(failure)
  }
}
