package lspserver

import (
  "bytes"
  "encoding/json"
  "testing"
)

// TestLSPPluginCompletionResolveStaysLocal verifies completion ownership.
//
// The merger creates a marked item and the direct editor-envelope handler
// answers its resolve request through a buffered frame. No upstream compiler
// is running here, so this unit does not observe an upstream crash or forwarding.
//
//  1. Encode a plugin completion and send that item back as a resolve request.
//  2. Assert the proxy answers locally with the item unchanged.
//  3. Assert the supplied unmarked item remains unhandled with no editor output.
//
// @evidence contracts/testing.md#behavioral-verification A merged plugin item's resolve request is handled locally and its decoded result equals the decoded submitted item; the supplied unmarked item returns unhandled and writes no editor bytes. Actual upstream forwarding is outside this direct dispatch unit.
// @evidence contracts/testing.md#independent-expectations Decoded equality with the submitted item is a preservation oracle, not an independent oracle for every field generated by the merger. A separate literal evidence label and insertion check establishes the supplied item's content; JSON whitespace and response IDs are not asserted.
// @evidence contracts/testing.md#distinguishing-cases A plugin item and an upstream item differ by ownership marker.
// @evidence contracts/testing.md#execution-ownership The discoverable Go unit directly invokes the actual merger and Proxy dispatcher, then decodes one response from bytes.Buffer through FrameReader and ParseEnvelope. It starts no child or host, installs no consumer and creates no temporary project; supported owned streams carry the observations.
func TestLSPPluginCompletionResolveStaysLocal(t *testing.T) {
  merged := mergeCompletionResponse(
    []byte(`{"jsonrpc":"2.0","id":1,"result":null}`),
    []LSPCompletionItem{{Insert: "evidence"}},
  )
  var completion struct {
    Result struct {
      Items []json.RawMessage `json:"items"`
    } `json:"result"`
  }
  if err := json.Unmarshal(merged, &completion); err != nil || len(completion.Result.Items) != 1 {
    t.Fatalf("decode plugin completion item: %v\n%s", err, merged)
  }
  item := completion.Result.Items[0]

  var editor bytes.Buffer
  proxy := &Proxy{editorOut: &editor}
  handled, err := proxy.handleEditorEnvelope(Envelope{
    JSONRPC: "2.0",
    ID:      json.RawMessage("7"),
    Method:  methodCompletionResolve,
    Params:  item,
  }, nil)
  if err != nil {
    t.Fatalf("resolve plugin completion: %v", err)
  }
  if !handled {
    t.Fatal("plugin completion resolve was forwarded upstream")
  }
  _, body, err := NewFrameReader(bytes.NewReader(editor.Bytes())).Read()
  if err != nil {
    t.Fatalf("read local resolve response: %v", err)
  }
  response, err := ParseEnvelope(body)
  if err != nil {
    t.Fatalf("parse local resolve response: %v", err)
  }
  var got any
  var want any
  if err := json.Unmarshal(response.Result, &got); err != nil {
    t.Fatalf("decode local resolve result: %v", err)
  }
  if err := json.Unmarshal(item, &want); err != nil {
    t.Fatalf("decode original plugin item: %v", err)
  }
  submitted, ok := want.(map[string]any)
  if !ok || submitted["label"] != "evidence" || submitted["insertText"] != "evidence" {
    t.Fatalf("plugin item lost its literal content: %s", item)
  }
  gotJSON, _ := json.Marshal(got)
  wantJSON, _ := json.Marshal(want)
  if !bytes.Equal(gotJSON, wantJSON) {
    t.Errorf("local resolve changed the plugin item:\n got %s\nwant %s", gotJSON, wantJSON)
  }

  editor.Reset()
  handled, err = proxy.handleEditorEnvelope(Envelope{
    JSONRPC: "2.0",
    ID:      json.RawMessage("8"),
    Method:  methodCompletionResolve,
    Params:  json.RawMessage(`{"label":"upstream","data":{"fileName":"/project/main.ts"}}`),
  }, nil)
  if err != nil {
    t.Fatalf("route upstream completion resolve: %v", err)
  }
  if handled || editor.Len() != 0 {
    t.Error("upstream completion resolve was intercepted instead of forwarded")
  }
}
