package lspserver

import (
  "bytes"
  "os/exec"
  "path/filepath"
  "strings"
  "testing"
)

// TestLSPProjectDiagnosticsRefreshesOnlyInputOwners verifies flattened client
// snapshot ownership can select one failed producer query. This direct unit
// does not register a client watcher or receive an actual watched-file event.
//
//  1. Give two diagnostics-capable producers disjoint exact input snapshots.
//  2. Resolve the first input's owner from the merged source.
//  3. Refresh that owner and assert the unrelated producer is never invoked.
//
// @evidence contracts/testing.md#behavioral-verification The first supplied .md URI resolves to one literal transport identity; a refresh using that list selects one producer, is incomplete and logs only its name. This observes failed-call selection rather than a successful publication or real watch dispatch.
// @evidence contracts/testing.md#independent-expectations The owner key, selected count one, complete=false and positive/negative producer names are authored expectations. Both binary lookup failures are checked before native attempts; the owner expectation is not generated by pluginKey.
// @evidence contracts/testing.md#distinguishing-cases Two producers with disjoint exact inputs separate owner-scoped from broadcast refresh.
// @evidence contracts/testing.md#execution-ownership The discoverable Go unit directly stores NativePluginSource snapshots and calls its owner matcher and owner-scoped diagnostic refresh. An owned temporary root supplies native URI identity and checked missing binaries reach failed resident/direct starts; there is no substitute query operation, installed consumer or running product host.
func TestLSPProjectDiagnosticsRefreshesOnlyInputOwners(t *testing.T) {
  root := t.TempDir()
  first := NativeLSPPluginEntry{
    Binary:             "ttsc-no-such-first-owner-sidecar",
    Name:               "@ttsc/first",
    ProjectDiagnostics: true,
    ProjectInputs:      true,
  }
  second := NativeLSPPluginEntry{
    Binary:             "ttsc-no-such-second-owner-sidecar",
    Name:               "@ttsc/second",
    ProjectDiagnostics: true,
    ProjectInputs:      true,
  }
  for _, plugin := range []NativeLSPPluginEntry{first, second} {
    if path, err := exec.LookPath(plugin.Binary); err == nil {
      t.Fatalf("missing-binary premise is false: %s", path)
    }
  }
  var log bytes.Buffer
  source := &NativePluginSource{
    err:     &log,
    plugins: []NativeLSPPluginEntry{first, second},
  }
  firstInput := filepath.Join(root, "docs", "first.md")
  source.storeProjectInputs(first, 1, LSPProjectInputSnapshot{
    Root:  filepath.ToSlash(root),
    Files: []string{filepath.ToSlash(firstInput)},
  })
  source.storeProjectInputs(second, 1, LSPProjectInputSnapshot{
    Root: filepath.ToSlash(root),
    Files: []string{
      filepath.ToSlash(filepath.Join(root, "docs", "second.md")),
    },
  })
  owners := source.ProjectInputOwnersForURI(testFileURI(firstInput))
  if len(owners) != 1 || owners[0] != "ttsc-no-such-first-owner-sidecar\x000" {
    t.Fatalf("first input owners = %#v", owners)
  }

  result := source.ProjectDiagnosticsForOwners(owners)

  if result.selected != 1 || result.complete {
    t.Fatalf("scoped failed refresh = %#v", result)
  }
  if !strings.Contains(log.String(), first.Name) {
    t.Fatalf("owned producer was not invoked:\n%s", log.String())
  }
  if strings.Contains(log.String(), second.Name) {
    t.Fatalf("unrelated producer was invoked:\n%s", log.String())
  }
}
