export { discoverNearestProjectTsconfig } from "./discovery/discoverNearestProjectTsconfig";
export { findNearestProjectTsconfig } from "./discovery/findNearestProjectTsconfig";
export { findProjectTsconfigs } from "./discovery/findProjectTsconfigs";
export type { TtscProjectDiscoveryFilesystem } from "./discovery/TtscProjectDiscoveryFilesystem";
export type { TtscProjectTreeDiscoveryFilesystem } from "./discovery/TtscProjectTreeDiscoveryFilesystem";
export type { TtscProjectTsconfigCandidate } from "./discovery/TtscProjectTsconfigCandidate";
export type { TtscProjectTsconfigDiscovery } from "./discovery/TtscProjectTsconfigDiscovery";
export { isTransformTarget } from "./isTransformTarget";
export { resolveOptions } from "./options/resolveOptions";
export type { TtscUnpluginCompilerOptionsJson } from "./options/TtscUnpluginCompilerOptionsJson";
export type { TtscUnpluginOptions } from "./options/TtscUnpluginOptions";
export { sourceFilePattern } from "./sourceFilePattern";
export { beginTtscTransformBuild } from "./transform/cache/beginTtscTransformBuild";
export { createTtscTransformCache } from "./transform/cache/createTtscTransformCache";
export { resetTtscTransformCache } from "./transform/cache/resetTtscTransformCache";
export type { TtscTransformFilesystemOperations } from "./transform/filesystem/TtscTransformFilesystemOperations";
export { collectExternalInputHashes } from "./transform/project/collectExternalInputHashes";
export { collectProjectInputHashes } from "./transform/project/collectProjectInputHashes";
export { collectProjectInputHashSnapshot } from "./transform/project/collectProjectInputHashSnapshot";
export { isProjectWalkPath } from "./transform/project/isProjectWalkPath";
export type { TtscProjectInputHashSnapshot } from "./transform/project/TtscProjectInputHashSnapshot";
export { transformTtsc } from "./transform/transformTtsc";
export { captureWatchInputBaseline } from "./transform/watch/captureWatchInputBaseline";
export { captureWatchInputFileBaseline } from "./transform/watch/captureWatchInputFileBaseline";
export { isWatchInputKeyBaseline } from "./transform/watch/isWatchInputKeyBaseline";
export type { TtscTransformHooks } from "./transform/watch/TtscTransformHooks";
export type { TtscWatchInput } from "./transform/watch/TtscWatchInput";
export type { TtscWatchInputBaseline } from "./transform/watch/TtscWatchInputBaseline";
export type { TtscWatchInputEvidence } from "./transform/watch/TtscWatchInputEvidence";
export type { TtscWatchInputFileBaseline } from "./transform/watch/TtscWatchInputFileBaseline";
export type { TtscWatchInputKeyBaseline } from "./transform/watch/TtscWatchInputKeyBaseline";
export type { TtscWatchInputState } from "./transform/watch/TtscWatchInputState";
export { watchInputEvidenceMatchesBaseline } from "./transform/watch/watchInputEvidenceMatchesBaseline";
export type { ITsconfigSourceSnapshotEntry } from "./tsconfig/ITsconfigSourceSnapshotEntry";
export type { ITtscProjectMembershipPolicy } from "./tsconfig/ITtscProjectMembershipPolicy";
export { mergeMembershipPolicyOverlay } from "./tsconfig/mergeMembershipPolicyOverlay";
export { readProjectMembershipPolicy } from "./tsconfig/readProjectMembershipPolicy";
export { readTsconfigSourceSnapshot } from "./tsconfig/readTsconfigSourceSnapshot";
export { searchedReferencedProjects } from "./tsconfig/searchedReferencedProjects";
export { unplugin, unplugin as default } from "./unplugin";
