import { TestProject } from "@ttsc/testing";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import { runtimeRunsDirectory } from "../../internal/ttsx-run";

/**
 * Verifies clean does not take an unreadable run index as an empty one.
 *
 * A failed listing proves nothing about the runs beneath it. Treating `EACCES`
 * as an absent index selected the entire runtime root for removal, including
 * any live run the process lacked permission to inspect.
 *
 * 1. Make the run index unreadable on a host that enforces that permission.
 * 2. Run the real `ttsc clean` command.
 * 3. Assert it fails without removing the runtime directory.
 *
 * @evidence contracts/testing.md#behavioral-verification After native readdir proves permission denial, public ttsc clean must fail while preserving the runtime directory, distinguishing unreadable evidence from an empty index.
 * @evidence contracts/testing.md#independent-expectations The host filesystem supplies EACCES or EPERM for the fixture; nonzero command status and surviving runtime are fixed fail-closed expectations, not outputs generated by the resolver.
 * @evidence contracts/testing.md#distinguishing-cases Unreadable runs are tested only where chmod actually denies listing; Windows and privileged hosts return without exercising this case. Missing and readable index decisions belong to other cleanup cases.
 * @evidence contracts/testing.md#execution-ownership The named E2E feature entry owns the real public clean invocation; its platform and capability returns limit execution and must not be reported as permission coverage on every host.
 * @evidence contracts/e2e.md#necessary-boundary Native permission denial must reach the assembled CLI without being converted into deletion authority; portable errno decision units cannot demonstrate that filesystem-to-command transport.
 * @evidence contracts/e2e.md#shared-execution One unreadable fixture and one clean command suffice, without native compilation or installation; no additional host is started when permission denial cannot be established.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity The fixture declares its own workspace boundary so an ancestor installation cannot select an external cache. Only the fixture index is chmodded and finally restores 0755 even after failure; no test process is retained after the synchronous CLI call.
 * @evidence contracts/e2e.md#preserved-coverage Actual denial-code validation, nonzero clean status and runtime preservation remain; real denied-permission execution is not available on Windows or privileged hosts.
 */
export function test_ttsc_clean_refuses_an_unreadable_runtime_index(): void {
  if (process.platform === "win32") return;
  const root = TestProject.createProject({
    "package.json": JSON.stringify({ name: "unreadable-runs", private: true, workspaces: ["packages/*"] }),
    "tsconfig.json": JSON.stringify({ include: ["src"] }),
    "src/main.ts": "export const value = 1;\n",
  });
  const runs = runtimeRunsDirectory(root);
  const runtime = path.dirname(runs);
  fs.mkdirSync(path.join(runs, "held"), { recursive: true });
  fs.chmodSync(runs, 0o000);
  try {
    try {
      fs.readdirSync(runs);
      return;
    } catch (error) {
      assert.ok(
        ["EACCES", "EPERM"].includes(
          (error as NodeJS.ErrnoException).code ?? "",
        ),
      );
    }
    const result = TestProject.spawn(
      TestProject.TTSC_BIN,
      ["clean", "--cwd", root],
      { cwd: root },
    );
    assert.notEqual(result.status, 0, result.stdout);
    assert.equal(fs.existsSync(runtime), true);
  } finally {
    fs.chmodSync(runs, 0o755);
  }
}
