import { TestProject } from "../../../../utils/src/TestProject";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { runtimeExecutableIdentity } from "../../../../../packages/ttsc/src/internal/runtimeExecutableIdentity";

/**
 * Verifies executable fingerprint semantics without compiling or executing one.
 *
 * Metadata-only reuse can accept a replaced compiler. Direct fixture-file
 * observations isolate fingerprint decisions from native runtime startup.
 *
 * 1. Compare stable reads with same-path timestamp and byte mutations.
 * 2. Check empty and multi-buffer SHA-256 content witnesses.
 * 3. Reject relative, missing and non-file candidates.
 *
 * @evidence contracts/testing.md#behavioral-verification Calls the actual streamed identity owner on fixture files. Stable reads repeat identity, same-path future-mtime mutation changes it while bytes stay identical, and changed bytes plus a multi-buffer tail require their complete SHA-256 witness. Relative, missing and directory candidates are rejected; an empty regular file has the empty-content witness.
 * @evidence contracts/testing.md#independent-expectations Literal SHA-256 of abc and empty input establish the small-file witnesses. Node crypto hashes the complete authored large buffer as an independent reference for the owner's descriptor/chunk traversal; expected identities are never generated by runtimeExecutableIdentity. Native stat confirms actual timestamp and byte controls.
 * @evidence contracts/testing.md#distinguishing-cases The former future-mtime compiler-cache case's identity decision executes directly here, beside unchanged, changed-content, empty, multi-buffer, absent and invalid-path controls. The surviving mtime-restored orphan E2E owns actual cold lowering, warm planted-marker reuse and next-host invalidation.
 * @evidence contracts/testing.md#execution-ownership This named source unit creates small regular-file inputs and calls authored filesystem/crypto logic in process. Files are fingerprint inputs rather than fabricated successful compiler artifacts; no binary is run, native artifact built, installed consumer prepared or product host started. Labeled assertions collect all independent controls.
 */
export function test_runtime_executable_identity_tracks_bytes_and_metadata_without_running_a_binary(): void {
  const root = TestProject.createProject({ "candidate": "abc", "empty": "" });
  const file = path.join(root, "candidate");
  const original = runtimeExecutableIdentity(file);
  const failures: unknown[] = [];
  const check = (label: string, work: () => void): void => {
    try { work(); } catch (error) { failures.push(new Error(label, { cause: error })); }
  };
  check("stable content", () => {
    assert.ok(original);
    assert.ok(original.includes("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
    assert.equal(runtimeExecutableIdentity(file), original);
  });
  const before = fs.statSync(file, { bigint: true });
  const later = new Date(Date.now() + 60_000);
  fs.writeFileSync(file, fs.readFileSync(file));
  fs.utimesSync(file, later, later);
  const changedMetadata = runtimeExecutableIdentity(file);
  check("same-path metadata", () => {
    assert.equal(fs.readFileSync(file, "utf8"), "abc");
    assert.equal(fs.statSync(file, { bigint: true }).size, before.size);
    assert.notEqual(fs.statSync(file, { bigint: true }).mtimeNs, before.mtimeNs);
    assert.ok(changedMetadata);
    assert.notEqual(changedMetadata, original);
  });
  fs.writeFileSync(file, "abd");
  fs.utimesSync(file, later, later);
  check("same-size content", () => {
    const changed = runtimeExecutableIdentity(file);
    assert.ok(changed);
    assert.notEqual(changed, changedMetadata);
    assert.ok(changed.includes(createHash("sha256").update("abd").digest("hex")));
  });
  const large = Buffer.alloc(64 * 1024 + 17, 0x61);
  large.fill(0x62, 64 * 1024);
  fs.writeFileSync(path.join(root, "large"), large);
  check("multi-buffer content", () => assert.ok(runtimeExecutableIdentity(path.join(root, "large"))?.includes(createHash("sha256").update(large).digest("hex"))));
  check("empty regular file", () => assert.ok(runtimeExecutableIdentity(path.join(root, "empty"))?.includes("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")));
  check("relative path", () => assert.equal(runtimeExecutableIdentity("candidate"), undefined));
  check("missing path", () => assert.equal(runtimeExecutableIdentity(path.join(root, "missing")), undefined));
  check("directory", () => assert.equal(runtimeExecutableIdentity(root), undefined));
  if (failures.length) throw new AggregateError(failures, "executable identity controls failed");
}
