// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.
// Source of truth: pinned native OptionsDeclarations and OptionsForWatch.
// Regenerate with: pnpm format
// Verify in CI with: node packages/ttsc/scripts/check-flags.cjs

import type { CompilerOptionSpec } from "./CompilerOptionSpec";

/** Pinned native option grammar, including alias, list and config-only boundaries. */
export const COMPILER_OPTIONS: ReadonlyMap<string, CompilerOptionSpec> =
  new Map<string, CompilerOptionSpec>([
    ["?", { name: "help", kind: "boolean", configOnly: false }],
    ["all", { name: "all", kind: "boolean", configOnly: false }],
    [
      "allowarbitraryextensions",
      { name: "allowArbitraryExtensions", kind: "boolean", configOnly: false },
    ],
    [
      "allowimportingtsextensions",
      {
        name: "allowImportingTsExtensions",
        kind: "boolean",
        configOnly: false,
      },
    ],
    ["allowjs", { name: "allowJs", kind: "boolean", configOnly: false }],
    [
      "allowsyntheticdefaultimports",
      {
        name: "allowSyntheticDefaultImports",
        kind: "boolean",
        configOnly: false,
      },
    ],
    [
      "allowumdglobalaccess",
      { name: "allowUmdGlobalAccess", kind: "boolean", configOnly: false },
    ],
    [
      "allowunreachablecode",
      { name: "allowUnreachableCode", kind: "boolean", configOnly: false },
    ],
    [
      "allowunusedlabels",
      { name: "allowUnusedLabels", kind: "boolean", configOnly: false },
    ],
    [
      "alwaysstrict",
      { name: "alwaysStrict", kind: "boolean", configOnly: false },
    ],
    [
      "assumechangesonlyaffectdirectdependencies",
      {
        name: "assumeChangesOnlyAffectDirectDependencies",
        kind: "boolean",
        configOnly: false,
      },
    ],
    ["baseurl", { name: "baseUrl", kind: "string", configOnly: false }],
    ["checkers", { name: "checkers", kind: "number", configOnly: false }],
    ["checkjs", { name: "checkJs", kind: "boolean", configOnly: false }],
    ["composite", { name: "composite", kind: "boolean", configOnly: true }],
    [
      "customconditions",
      {
        name: "customConditions",
        kind: "list",
        element: "string",
        configOnly: false,
      },
    ],
    ["d", { name: "declaration", kind: "boolean", configOnly: false }],
    [
      "declaration",
      { name: "declaration", kind: "boolean", configOnly: false },
    ],
    [
      "declarationdir",
      { name: "declarationDir", kind: "string", configOnly: false },
    ],
    [
      "declarationmap",
      { name: "declarationMap", kind: "boolean", configOnly: false },
    ],
    [
      "deduplicatepackages",
      { name: "deduplicatePackages", kind: "boolean", configOnly: false },
    ],
    [
      "diagnostics",
      { name: "diagnostics", kind: "boolean", configOnly: false },
    ],
    [
      "disablereferencedprojectload",
      {
        name: "disableReferencedProjectLoad",
        kind: "boolean",
        configOnly: true,
      },
    ],
    [
      "disablesizelimit",
      { name: "disableSizeLimit", kind: "boolean", configOnly: false },
    ],
    [
      "disablesolutionsearching",
      { name: "disableSolutionSearching", kind: "boolean", configOnly: true },
    ],
    [
      "disablesourceofprojectreferenceredirect",
      {
        name: "disableSourceOfProjectReferenceRedirect",
        kind: "boolean",
        configOnly: true,
      },
    ],
    [
      "downleveliteration",
      { name: "downlevelIteration", kind: "boolean", configOnly: false },
    ],
    ["emitbom", { name: "emitBOM", kind: "boolean", configOnly: false }],
    [
      "emitdeclarationonly",
      { name: "emitDeclarationOnly", kind: "boolean", configOnly: false },
    ],
    [
      "emitdecoratormetadata",
      { name: "emitDecoratorMetadata", kind: "boolean", configOnly: false },
    ],
    [
      "erasablesyntaxonly",
      { name: "erasableSyntaxOnly", kind: "boolean", configOnly: false },
    ],
    [
      "esmoduleinterop",
      { name: "esModuleInterop", kind: "boolean", configOnly: false },
    ],
    [
      "exactoptionalpropertytypes",
      {
        name: "exactOptionalPropertyTypes",
        kind: "boolean",
        configOnly: false,
      },
    ],
    [
      "excludedirectories",
      {
        name: "excludeDirectories",
        kind: "list",
        element: "string",
        configOnly: false,
      },
    ],
    [
      "excludefiles",
      {
        name: "excludeFiles",
        kind: "list",
        element: "string",
        configOnly: false,
      },
    ],
    [
      "experimentaldecorators",
      { name: "experimentalDecorators", kind: "boolean", configOnly: false },
    ],
    [
      "explainfiles",
      { name: "explainFiles", kind: "boolean", configOnly: false },
    ],
    [
      "extendeddiagnostics",
      { name: "extendedDiagnostics", kind: "boolean", configOnly: false },
    ],
    [
      "fallbackpolling",
      { name: "fallbackPolling", kind: "enum", configOnly: false },
    ],
    [
      "forceconsistentcasinginfilenames",
      {
        name: "forceConsistentCasingInFileNames",
        kind: "boolean",
        configOnly: false,
      },
    ],
    [
      "generatecpuprofile",
      { name: "generateCpuProfile", kind: "string", configOnly: false },
    ],
    [
      "generatetrace",
      { name: "generateTrace", kind: "string", configOnly: false },
    ],
    ["h", { name: "help", kind: "boolean", configOnly: false }],
    ["help", { name: "help", kind: "boolean", configOnly: false }],
    ["i", { name: "incremental", kind: "boolean", configOnly: false }],
    [
      "ignoreconfig",
      { name: "ignoreConfig", kind: "boolean", configOnly: false },
    ],
    [
      "ignoredeprecations",
      { name: "ignoreDeprecations", kind: "string", configOnly: false },
    ],
    [
      "importhelpers",
      { name: "importHelpers", kind: "boolean", configOnly: false },
    ],
    [
      "incremental",
      { name: "incremental", kind: "boolean", configOnly: false },
    ],
    ["init", { name: "init", kind: "boolean", configOnly: false }],
    [
      "inlinesourcemap",
      { name: "inlineSourceMap", kind: "boolean", configOnly: false },
    ],
    [
      "inlinesources",
      { name: "inlineSources", kind: "boolean", configOnly: false },
    ],
    [
      "isolateddeclarations",
      { name: "isolatedDeclarations", kind: "boolean", configOnly: false },
    ],
    [
      "isolatedmodules",
      { name: "isolatedModules", kind: "boolean", configOnly: false },
    ],
    ["jsx", { name: "jsx", kind: "enum", configOnly: false }],
    ["jsxfactory", { name: "jsxFactory", kind: "string", configOnly: false }],
    [
      "jsxfragmentfactory",
      { name: "jsxFragmentFactory", kind: "string", configOnly: false },
    ],
    [
      "jsximportsource",
      { name: "jsxImportSource", kind: "string", configOnly: false },
    ],
    ["lib", { name: "lib", kind: "list", element: "enum", configOnly: false }],
    [
      "libreplacement",
      { name: "libReplacement", kind: "boolean", configOnly: false },
    ],
    [
      "listemittedfiles",
      { name: "listEmittedFiles", kind: "boolean", configOnly: false },
    ],
    ["listfiles", { name: "listFiles", kind: "boolean", configOnly: false }],
    [
      "listfilesonly",
      { name: "listFilesOnly", kind: "boolean", configOnly: false },
    ],
    ["locale", { name: "locale", kind: "string", configOnly: false }],
    ["m", { name: "module", kind: "enum", configOnly: false }],
    ["maproot", { name: "mapRoot", kind: "string", configOnly: false }],
    [
      "maxnodemodulejsdepth",
      { name: "maxNodeModuleJsDepth", kind: "number", configOnly: false },
    ],
    ["module", { name: "module", kind: "enum", configOnly: false }],
    [
      "moduledetection",
      { name: "moduleDetection", kind: "enum", configOnly: false },
    ],
    [
      "moduleresolution",
      { name: "moduleResolution", kind: "enum", configOnly: false },
    ],
    [
      "modulesuffixes",
      {
        name: "moduleSuffixes",
        kind: "list",
        element: "string",
        configOnly: false,
      },
    ],
    ["newline", { name: "newLine", kind: "enum", configOnly: false }],
    ["nocheck", { name: "noCheck", kind: "boolean", configOnly: false }],
    ["noemit", { name: "noEmit", kind: "boolean", configOnly: false }],
    [
      "noemithelpers",
      { name: "noEmitHelpers", kind: "boolean", configOnly: false },
    ],
    [
      "noemitonerror",
      { name: "noEmitOnError", kind: "boolean", configOnly: false },
    ],
    [
      "noerrortruncation",
      { name: "noErrorTruncation", kind: "boolean", configOnly: false },
    ],
    [
      "nofallthroughcasesinswitch",
      {
        name: "noFallthroughCasesInSwitch",
        kind: "boolean",
        configOnly: false,
      },
    ],
    [
      "noimplicitany",
      { name: "noImplicitAny", kind: "boolean", configOnly: false },
    ],
    [
      "noimplicitoverride",
      { name: "noImplicitOverride", kind: "boolean", configOnly: false },
    ],
    [
      "noimplicitreturns",
      { name: "noImplicitReturns", kind: "boolean", configOnly: false },
    ],
    [
      "noimplicitthis",
      { name: "noImplicitThis", kind: "boolean", configOnly: false },
    ],
    ["nolib", { name: "noLib", kind: "boolean", configOnly: false }],
    [
      "nopropertyaccessfromindexsignature",
      {
        name: "noPropertyAccessFromIndexSignature",
        kind: "boolean",
        configOnly: false,
      },
    ],
    ["noresolve", { name: "noResolve", kind: "boolean", configOnly: false }],
    [
      "nouncheckedindexedaccess",
      { name: "noUncheckedIndexedAccess", kind: "boolean", configOnly: false },
    ],
    [
      "nouncheckedsideeffectimports",
      {
        name: "noUncheckedSideEffectImports",
        kind: "boolean",
        configOnly: false,
      },
    ],
    [
      "nounusedlocals",
      { name: "noUnusedLocals", kind: "boolean", configOnly: false },
    ],
    [
      "nounusedparameters",
      { name: "noUnusedParameters", kind: "boolean", configOnly: false },
    ],
    ["outdir", { name: "outDir", kind: "string", configOnly: false }],
    ["outfile", { name: "outFile", kind: "string", configOnly: false }],
    ["p", { name: "project", kind: "string", configOnly: false }],
    ["paths", { name: "paths", kind: "object", configOnly: true }],
    [
      "plugins",
      { name: "plugins", kind: "list", element: "object", configOnly: true },
    ],
    ["pprofdir", { name: "pprofDir", kind: "string", configOnly: false }],
    [
      "preserveconstenums",
      { name: "preserveConstEnums", kind: "boolean", configOnly: false },
    ],
    [
      "preservesymlinks",
      { name: "preserveSymlinks", kind: "boolean", configOnly: false },
    ],
    [
      "preservewatchoutput",
      { name: "preserveWatchOutput", kind: "boolean", configOnly: false },
    ],
    ["pretty", { name: "pretty", kind: "boolean", configOnly: false }],
    ["project", { name: "project", kind: "string", configOnly: false }],
    ["q", { name: "quiet", kind: "boolean", configOnly: false }],
    ["quiet", { name: "quiet", kind: "boolean", configOnly: false }],
    [
      "reactnamespace",
      { name: "reactNamespace", kind: "string", configOnly: false },
    ],
    [
      "removecomments",
      { name: "removeComments", kind: "boolean", configOnly: false },
    ],
    [
      "resolvejsonmodule",
      { name: "resolveJsonModule", kind: "boolean", configOnly: false },
    ],
    [
      "resolvepackagejsonexports",
      { name: "resolvePackageJsonExports", kind: "boolean", configOnly: false },
    ],
    [
      "resolvepackagejsonimports",
      { name: "resolvePackageJsonImports", kind: "boolean", configOnly: false },
    ],
    [
      "rewriterelativeimportextensions",
      {
        name: "rewriteRelativeImportExtensions",
        kind: "boolean",
        configOnly: false,
      },
    ],
    ["rootdir", { name: "rootDir", kind: "string", configOnly: false }],
    [
      "rootdirs",
      { name: "rootDirs", kind: "list", element: "string", configOnly: true },
    ],
    ["showconfig", { name: "showConfig", kind: "boolean", configOnly: false }],
    [
      "singlethreaded",
      { name: "singleThreaded", kind: "boolean", configOnly: false },
    ],
    [
      "skipdefaultlibcheck",
      { name: "skipDefaultLibCheck", kind: "boolean", configOnly: false },
    ],
    [
      "skiplibcheck",
      { name: "skipLibCheck", kind: "boolean", configOnly: false },
    ],
    ["sourcemap", { name: "sourceMap", kind: "boolean", configOnly: false }],
    ["sourceroot", { name: "sourceRoot", kind: "string", configOnly: false }],
    [
      "stabletypeordering",
      { name: "stableTypeOrdering", kind: "boolean", configOnly: false },
    ],
    ["strict", { name: "strict", kind: "boolean", configOnly: false }],
    [
      "strictbindcallapply",
      { name: "strictBindCallApply", kind: "boolean", configOnly: false },
    ],
    [
      "strictbuiltiniteratorreturn",
      {
        name: "strictBuiltinIteratorReturn",
        kind: "boolean",
        configOnly: false,
      },
    ],
    [
      "strictfunctiontypes",
      { name: "strictFunctionTypes", kind: "boolean", configOnly: false },
    ],
    [
      "strictnullchecks",
      { name: "strictNullChecks", kind: "boolean", configOnly: false },
    ],
    [
      "strictpropertyinitialization",
      {
        name: "strictPropertyInitialization",
        kind: "boolean",
        configOnly: false,
      },
    ],
    [
      "stripinternal",
      { name: "stripInternal", kind: "boolean", configOnly: false },
    ],
    [
      "synchronouswatchdirectory",
      { name: "synchronousWatchDirectory", kind: "boolean", configOnly: false },
    ],
    ["t", { name: "target", kind: "enum", configOnly: false }],
    ["target", { name: "target", kind: "enum", configOnly: false }],
    [
      "traceresolution",
      { name: "traceResolution", kind: "boolean", configOnly: false },
    ],
    [
      "tsbuildinfofile",
      { name: "tsBuildInfoFile", kind: "string", configOnly: false },
    ],
    [
      "typeroots",
      { name: "typeRoots", kind: "list", element: "string", configOnly: false },
    ],
    [
      "types",
      { name: "types", kind: "list", element: "string", configOnly: false },
    ],
    [
      "usedefineforclassfields",
      { name: "useDefineForClassFields", kind: "boolean", configOnly: false },
    ],
    [
      "useunknownincatchvariables",
      {
        name: "useUnknownInCatchVariables",
        kind: "boolean",
        configOnly: false,
      },
    ],
    ["v", { name: "version", kind: "boolean", configOnly: false }],
    [
      "verbatimmodulesyntax",
      { name: "verbatimModuleSyntax", kind: "boolean", configOnly: false },
    ],
    ["version", { name: "version", kind: "boolean", configOnly: false }],
    ["w", { name: "watch", kind: "boolean", configOnly: false }],
    ["watch", { name: "watch", kind: "boolean", configOnly: false }],
    [
      "watchdirectory",
      { name: "watchDirectory", kind: "enum", configOnly: false },
    ],
    ["watchfile", { name: "watchFile", kind: "enum", configOnly: false }],
    [
      "watchinterval",
      { name: "watchInterval", kind: "number", configOnly: false },
    ],
  ]);
