// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.
// Source of truth: pinned native OptionsDeclarations.
// Regenerate with: pnpm format
// Verify in CI with: node packages/ttsc/scripts/check-flags.cjs

/** Native Unicode simple-case folds into the ASCII option-name domain. */
export const COMPILER_OPTION_ASCII_FOLDS: ReadonlyMap<string, string> = new Map<
  string,
  string
>([
  ["İ", "i"],
  ["K", "k"],
]);
