// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.
// Source of truth: pinned native OptionsDeclarations and OptionsForWatch.
// Regenerate with: pnpm format
// Verify in CI with: node packages/ttsc/scripts/check-flags.cjs

/** Native enum-item trimming; distinct from Go list-level TrimSpace. */
export const COMPILER_ENUM_WHITESPACE: ReadonlySet<string> = new Set<string>([
  "\t",
  "\n",
  "\u000b",
  "\f",
  "\r",
  " ",
  "",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  "​",
  " ",
  " ",
  " ",
  " ",
  "　",
  "﻿",
]);
