// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.
// Source of truth: pinned native OptionsDeclarations and OptionsForWatch.
// Regenerate with: pnpm format
// Verify in CI with: node packages/ttsc/scripts/check-flags.cjs
import { COMPILER_OPTIONS } from "./COMPILER_OPTIONS";

/** Compatibility projection for callers that only need nominal kind. */
export const COMPILER_OPTION_KINDS: ReadonlyMap<string, "boolean" | "value"> =
  new Map(
    [...COMPILER_OPTIONS].map(([name, option]) => [
      name,
      option.kind === "boolean" ? "boolean" : "value",
    ]),
  );
