import assert from "node:assert/strict";
import path from "node:path";
import { createFilesystemPathIdentityContext } from "../../../../../packages/ttsc/src/internal/pathIdentity/createFilesystemPathIdentityContext";
import { createProjectInputPathIdentityContext } from "../../../../../packages/ttsc/src/internal/pathIdentity/createProjectInputPathIdentityContext";

/**
 * Verifies project-input identities use explicit filesystem authority for aliases and missing suffixes.
 *
 * @evidence contracts/testing.md#behavioral-verification Actual authored identity resolvers converge physical aliases and insensitive missing descendants while preserving sensitive siblings and suffixes; UNC authority/share aliases converge independently of host OS.
 * @evidence contracts/testing.md#independent-expectations Explicit realpath responses and case-authority decisions establish the virtual filesystem contract, with literal canonical paths and equality/inequality expectations rather than outputs generated by the resolver.
 * @evidence contracts/testing.md#distinguishing-cases Sensitive/insensitive missing suffixes, physical aliases, Windows root spelling, sensitive siblings and UNC authority retain all original portable assertions. Actual volume observation and fsutil-sensitive-directory behavior remain in the named actual E2E entry.
 * @evidence contracts/testing.md#execution-ownership The named src/features/watch entry directly calls authored identity sources with supported explicit filesystem operations; it spawns no native process and performs no volume mutation or actual kernel observation.
 */
export function test_project_input_path_identity_respects_explicit_directory_case_authority() {
    const root = path.resolve("virtual-project-input-root");
    const physical = path.join(root, "Physical");
    const alias = path.join(root, "Alias");
    const realpath = (location: string): string => {
      if (location === physical || location === alias) return physical;
      throw Object.assign(new Error("missing"), { code: "ENOENT" });
    };
    const insensitive = createProjectInputPathIdentityContext({
      caseSensitive: () => false,
      realpath,
    });
    const sensitive = createProjectInputPathIdentityContext({
      caseSensitive: () => true,
      realpath,
    });

    const insensitivePath = path.join(physical, "future", "spec.md");
    const insensitiveVolume = path.parse(insensitivePath).root;
    assert.deepEqual(
      insensitive.resolve(path.join(alias, "Future", "Spec.md")),
      {
        key:
          process.platform === "win32"
            ? `${insensitiveVolume.toLowerCase()}${insensitivePath.slice(insensitiveVolume.length)}`
            : insensitivePath,
        path: insensitivePath,
      },
    );
    assert.equal(
      insensitive.resolve(path.join(alias, "future", "spec.md")).key,
      insensitive.resolve(path.join(alias, "Future", "Spec.md")).key,
    );
    assert.notEqual(
      sensitive.resolve(path.join(alias, "future", "spec.md")).key,
      sensitive.resolve(path.join(alias, "Future", "Spec.md")).key,
    );

    const missing = (): never => {
      throw Object.assign(new Error("missing"), { code: "ENOENT" });
    };
    const windows = createFilesystemPathIdentityContext({
      platform: "win32",
      caseSensitive: (directory) =>
        path.win32.resolve(directory).toLowerCase().startsWith("c:\\sensitive"),
      realpath: (location) => {
        const resolved = path.win32.resolve(location);
        const folded = resolved.toLowerCase();
        if (folded === "c:\\ordinary") return "C:\\Ordinary";
        if (folded === "c:\\ordinary\\repo") return "C:\\Ordinary\\Repo";
        if (resolved === "C:\\Sensitive") return resolved;
        if (resolved === "C:\\Sensitive\\Project") return resolved;
        if (resolved === "C:\\Sensitive\\project") return resolved;
        if (/^\\\\[^\\]+\\[^\\]+\\Work$/i.test(resolved)) return resolved;
        return missing();
      },
    });
    assert.equal(
      windows.resolve("C:\\ORDINARY\\repo").key,
      windows.resolve("c:\\ordinary\\REPO").key,
      "ordinary Windows aliases converge through physical spelling",
    );
    assert.notEqual(
      windows.resolve("C:\\Sensitive\\Project").key,
      windows.resolve("C:\\Sensitive\\project").key,
      "case-sensitive Windows siblings remain distinct",
    );
    assert.notEqual(
      windows.resolve("C:\\Sensitive\\Project\\Future.ts").key,
      windows.resolve("C:\\Sensitive\\Project\\future.ts").key,
      "missing descendants inherit sensitive ownership",
    );
    assert.equal(
      windows.resolve("C:\\Ordinary\\Repo\\Future.ts").key,
      windows.resolve("c:\\ordinary\\repo\\future.ts").key,
      "missing descendants inherit insensitive ownership",
    );
    assert.equal(
      windows.resolve("\\\\SERVER\\Share\\Work").key,
      windows.resolve("\\\\server\\share\\Work").key,
      "UNC authority and share aliases identify one volume",
    );

}
