// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package transformers is the documented github.com/microsoft/typescript-go/shim/transformers plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/transformers, the
// bridge that reaches the compiler's internal packages.
package transformers

import (
  tsctransformers "github.com/microsoft/TypeScript/tsc/shim/transformers"
)

type Transformer = tsctransformers.Transformer
