import { FixtureFiles } from "../../../internal/FixtureFiles";
import { TestProject } from "@ttsc/testing";

import {
  assert,
  createProject,
  path,
  spawn,
  ttscBin,
  workspaceRoot,
} from "../../../internal/ttsc/internal/toolchain";

/**
 * Verifies ttsc cache paths JSON reports source build cache roots.
 *
 * Split CI jobs need stable cache paths without copying ttsc internals such as
 * `~/.cache/ttsc/plugins`. The cache paths command is the public contract for
 * discovering the source-plugin binary cache and the Go object cache ttsc uses
 * while building those binaries.
 *
 * 1. Create a project and request a relative `--cache-dir` from a different
 *    process cwd.
 * 2. Run `ttsc cache paths --json` with an explicit `TTSC_GO_CACHE_DIR`.
 * 3. Assert the JSON points at the cwd-resolved cache root, plugin root, and
 *    cacheable Go build root.
 *
 * @evidence contracts/testing.md#behavioral-verification A real cache paths --json command from workspace cwd with --cwd consumer and relative --cache-dir must report physical cwd/project/cache roots, plugins, explicit TTSC_GO_CACHE_DIR source and exact required/cacheable/accelerator arrays.
 * @evidence contracts/testing.md#independent-expectations The authored relative .ci/ttsc argument and explicit Go cache path independently determine literal joined paths and role arrays. The expected record is enumerated by the case rather than generated by the command's resolver; no physical cache creation is asserted.
 * @evidence contracts/testing.md#distinguishing-cases Process cwd differs from the --cwd consumer and GOCACHE is emptied so TTSC_GO_CACHE_DIR must win. Schema spelling and unsupported cache flags are covered separately.
 * @evidence contracts/testing.md#execution-ownership TestExecutor discovers test_ttsc_cache_paths_json_reports_source_build_cache_roots in features/compiler through the test-ttsc boundary runner. This named E2E entry owns its actual launcher invocations and local scenario loops; portable source units are dispatched separately by the unit-module executor.
 * @evidence contracts/e2e.md#necessary-boundary The public Node launcher's cache subcommand resolves filesystem project identity and child environment into machine-readable discovery output. Direct cache-root functions cannot establish JSON serialization and --cwd dispatch from a different process directory.
 * @evidence contracts/e2e.md#shared-execution One minimal consumer and built JS launcher serve this command; no native compile or Go cache warmup is needed to report paths. Its child environment supplies explicit cache inputs without constructing another installation.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity createProject allocates a unique TestProject directory, so authored config and emitted outputs cannot inherit another entry's result. spawn injects explicit workspace native and tsgo binary identities in the child environment without modifying the parent. The synchronous child has exited before assertions, and TestProject cleans temporary directories on runner exit.
 * @evidence contracts/e2e.md#preserved-coverage All original CLI status, output and generated-artifact assertions remain in test_ttsc_cache_paths_json_reports_source_build_cache_roots. No assertion or case is removed or transferred; this entry retains its real launcher connection rather than claiming a parser unit executes it.
 */
export const test_ttsc_cache_paths_json_reports_source_build_cache_roots =
  () => {
    const root = TestProject.physicalPath(
      createProject(FixtureFiles.read("ttsc/ttsc_cache_paths_json_reports_source_build_cache_roots/inputs-1")),
    );
    const goBuildCache = path.join(root, ".ci-go-build");

    const result = spawn(
      ttscBin,
      ["cache", "paths", "--json", "--cwd", root, "--cache-dir", ".ci/ttsc"],
      {
        cwd: workspaceRoot,
        env: {
          GOCACHE: "",
          TTSC_GO_CACHE_DIR: goBuildCache,
        },
      },
    );

    assert.equal(result.status, 0, result.stderr);
    const parsed = JSON.parse(result.stdout) as {
      cacheRoot: string;
      cacheableRoots: string[];
      acceleratorRoots: string[];
      cwd: string;
      goBuildCacheRoot: string;
      goBuildCacheSource: string;
      pluginCacheRoot: string;
      projectRoot: string;
      requiredRoots: string[];
    };
    const cacheRoot = path.join(root, ".ci", "ttsc");
    assert.equal(parsed.cwd, root);
    assert.equal(parsed.projectRoot, root);
    assert.equal(parsed.cacheRoot, cacheRoot);
    assert.equal(parsed.pluginCacheRoot, path.join(cacheRoot, "plugins"));
    assert.equal(parsed.goBuildCacheRoot, goBuildCache);
    assert.equal(parsed.goBuildCacheSource, "TTSC_GO_CACHE_DIR");
    assert.deepEqual(parsed.cacheableRoots, [cacheRoot, goBuildCache]);
    assert.deepEqual(parsed.requiredRoots, [path.join(cacheRoot, "plugins")]);
    assert.deepEqual(parsed.acceleratorRoots, [goBuildCache]);
  };
