package linthost

import "testing"

// TestUnicornPreferStringRawSkipsLiteralsWithOtherEscapes verifies the rule
// stays silent when a literal carries an escape other than `\\`.
//
// Pins upstream's `unescapeBackslash(raw) !== node.value` guard. `String.raw`
// emits every escape by its source spelling, so converting `"\\d\t"` would
// turn the TAB into the two characters `\t` — a silent value change. The port
// used to report any literal whose raw source contained `\\`, which advised
// exactly that corruption (issue #575). The escaped backslash on its own
// (`"\\n"` — a backslash followed by the letter `n`) must still report, so the
// guard cannot be implemented as "raw contains a second backslash".
//
//  1. Enable unicorn/prefer-string-raw on a fixture whose only annotated line
//     is a literal escaping nothing but backslashes.
//  2. Add string and template literals that mix `\\` with a tab, a hex, and a
//     newline escape.
//  3. Assert the annotated line is the ONLY finding.
//
// @evidence contracts/testing.md#behavioral-verification The corpus helper runs Engine.Run and verifies escaped backslash followed by n reports, but mixed tab, hex, newline and template-tab escapes do not; annotated rule/severity/line equality or explicit zero count rejects extra findings.
// @evidence contracts/testing.md#independent-expectations Authored literal annotations and zero-finding controls express the supported upstream prefer-string-raw value-preservation policy; their expected results are not generated by the Go escape/value comparison implementation.
// @evidence contracts/testing.md#distinguishing-cases Authored positive and negative fixtures distinguish a literal backslash-n payload from a newline escape, so raw conversion cannot silently change values.
// @evidence contracts/testing.md#execution-ownership TestUnicornPreferStringRawSkipsLiteralsWithOtherEscapes is a discoverable Go unit entry; its source fixtures run owning AST/engine operations in the shared Go process without installed consumers, native builds or product hosts. Corpus failure output retains the virtual source identity and expected/actual finding positions.
func TestUnicornPreferStringRawSkipsLiteralsWithOtherEscapes(t *testing.T) {
  assertRuleCorpusCase(
    t,
    "unicorn/prefer-string-raw-other-escapes.ts",
    "// expect: unicorn/prefer-string-raw error\n"+
      "const backslashOnly = \"\\\\n\";\n"+
      "const tab = \"\\\\d\\t\";\n"+
      "const hex = \"\\\\d\\x41\";\n"+
      "const newline = \"\\\\d\\n\";\n"+
      "const template = `\\\\d\\t`;\n",
  )
}
