package linthost

import "testing"

// TestUnicornPreferStringRawUnescapesOnlyTheDelimiterQuote verifies the value
// comparison unescapes the literal's OWN quote and no other.
//
// Upstream builds its unescape pattern from the literal's delimiter
// (`[\\${quote}]`), so `\"` cancels out in a double-quoted literal but stays
// an escape in a single-quoted one — where `String.raw` would emit the
// backslash and change the value. A port that unescaped both quote characters,
// or neither, would flip one of these two lines.
//
//  1. Double-quote a literal that escapes its own delimiter alongside `\\`.
//  2. Single-quote a literal escaping the OTHER quote alongside `\\`.
//  3. Assert only the double-quoted line, whose escapes all cancel, reports.
//
// @evidence contracts/testing.md#behavioral-verification The corpus helper runs Engine.Run and verifies a double-quoted literal escaping its own quote reports while the single-quoted literal escaping the other quote stays clean; annotated rule/severity/line equality or explicit zero count rejects extra findings.
// @evidence contracts/testing.md#independent-expectations Authored literal annotations and zero-finding controls express the supported upstream prefer-string-raw value-preservation policy; their expected results are not generated by the Go escape/value comparison implementation.
// @evidence contracts/testing.md#distinguishing-cases The two authored source lines differ in delimiter only, detecting both over-unescaping and under-unescaping of quote characters.
// @evidence contracts/testing.md#execution-ownership TestUnicornPreferStringRawUnescapesOnlyTheDelimiterQuote is a discoverable Go unit entry; its source fixtures run owning AST/engine operations in the shared Go process without installed consumers, native builds or product hosts. Corpus failure output retains the virtual source identity and expected/actual finding positions.
func TestUnicornPreferStringRawUnescapesOnlyTheDelimiterQuote(t *testing.T) {
  assertRuleCorpusCase(
    t,
    "unicorn/prefer-string-raw-delimiter-quote.ts",
    "// expect: unicorn/prefer-string-raw error\n"+
      "const own = \"a\\\"b\\\\c\";\n"+
      "const other = 'a\\\"b\\\\c';\n",
  )
}
