package linthost

import "testing"

// TestRuleCorpusUnicornPreferStringRaw verifies the rule reports a
// string literal whose escapes are nothing but backslashes.
//
// The positive case the suppression guards must never swallow: every escape
// in the literal is `\\`, so `String.raw` respells the value character for
// character. A Windows-shaped path is the canonical example and the minimal
// positive case.
//
// 1. Enable unicorn/prefer-string-raw via an expect annotation.
// 2. Write a string literal whose only escapes are `\\` (`"C:\\Users\\me"`).
// 3. Assert the string literal is reported.
//
// @evidence contracts/testing.md#behavioral-verification The corpus helper runs Engine.Run and verifies the complete Windows-shaped path with only escaped backslashes reports; annotated rule/severity/line equality or explicit zero count rejects extra findings.
// @evidence contracts/testing.md#independent-expectations Authored literal annotations and zero-finding controls express the supported upstream prefer-string-raw value-preservation policy; their expected results are not generated by the Go escape/value comparison implementation.
// @evidence contracts/testing.md#distinguishing-cases The authored annotation follows upstream value-preserving raw-string advice; TestUnicornPreferStringRawSkipsLiteralsWithoutEscapedBackslashes and other named Skip entries own adjacent empty, semantic-escape and delimiter exclusions.
// @evidence contracts/testing.md#execution-ownership TestRuleCorpusUnicornPreferStringRaw is a discoverable Go unit entry; its source fixtures run owning AST/engine operations in the shared Go process without installed consumers, native builds or product hosts. Corpus failure output retains the virtual source identity and expected/actual finding positions.
func TestRuleCorpusUnicornPreferStringRaw(t *testing.T) {
  assertRuleCorpusCase(t, "unicorn/prefer-string-raw.ts", "// expect: unicorn/prefer-string-raw error\nconst p = \"C:\\\\Users\\\\me\";\n")
}
