package linthost

import "testing"

// TestUnicornPreferStringRawSkipsJsxAttributeStrings verifies the rule stays
// silent on a JSX attribute value.
//
// Upstream exempts JSX attribute values by position, because JSX strings have
// no escape sequences: `title="C:\\Users"` really does hold two backslashes,
// and a `String.raw` template would halve them. The value comparison reaches
// the same verdict from the value side — the scanner cooks a JSX attribute
// string verbatim, so its cooked text keeps the doubled backslash the unescape
// drops — which is exactly why the comparison must stay in place for TSX.
//
//  1. Parse a TSX fixture whose annotated line is an ordinary string literal.
//  2. Give a JSX attribute the same backslash-escaped path as its value.
//  3. Assert only the ordinary literal reports.
//
// @evidence contracts/testing.md#behavioral-verification The corpus helper runs Engine.Run and verifies an ordinary string reports while the identical backslash spelling in a JSX attribute stays clean; annotated rule/severity/line equality or explicit zero count rejects extra findings.
// @evidence contracts/testing.md#independent-expectations Authored literal annotations and zero-finding controls express the supported upstream prefer-string-raw value-preservation policy; their expected results are not generated by the Go escape/value comparison implementation.
// @evidence contracts/testing.md#distinguishing-cases The TSX fixture distinguishes JavaScript escape cooking from JSX verbatim attribute text without using a platform filesystem.
// @evidence contracts/testing.md#execution-ownership TestUnicornPreferStringRawSkipsJsxAttributeStrings is a discoverable Go unit entry; its source fixtures run owning AST/engine operations in the shared Go process without installed consumers, native builds or product hosts. Corpus failure output retains the virtual source identity and expected/actual finding positions.
func TestUnicornPreferStringRawSkipsJsxAttributeStrings(t *testing.T) {
  assertRuleCorpusCaseTSX(
    t,
    "unicorn/prefer-string-raw-jsx-attribute.tsx",
    "// expect: unicorn/prefer-string-raw error\n"+
      "const path = \"C:\\\\Users\\\\me\";\n"+
      "const element = <div title=\"C:\\\\Users\\\\me\" />;\n",
  )
}
