// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package tspath is the documented github.com/microsoft/typescript-go/shim/tspath plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/tspath, the
// bridge that reaches the compiler's internal packages.
package tspath

import (
  tsctspath "github.com/microsoft/TypeScript/tsc/shim/tspath"
)

var AllSupportedExtensions = tsctspath.AllSupportedExtensions

var AllSupportedExtensionsWithJson = tsctspath.AllSupportedExtensionsWithJson

const CaseInsensitive = tsctspath.CaseInsensitive

const CaseSensitive = tsctspath.CaseSensitive

type CaseSensitivity = tsctspath.CaseSensitivity

func ChangeAnyExtension(p0 string, p1 string, p2 []string, p3 tsctspath.CaseSensitivity) string {
  return tsctspath.ChangeAnyExtension(p0, p1, p2, p3)
}

func ChangeExtension(p0 string, p1 string) string {
  return tsctspath.ChangeExtension(p0, p1)
}

func ChangeFullExtension(p0 string, p1 string) string {
  return tsctspath.ChangeFullExtension(p0, p1)
}

func CombinePaths(p0 string, p1 ...string) string {
  return tsctspath.CombinePaths(p0, p1...)
}

func CompareNumberOfDirectorySeparators(p0 string, p1 string) int {
  return tsctspath.CompareNumberOfDirectorySeparators(p0, p1)
}

func ComparePaths(p0 string, p1 string, p2 tsctspath.CaseSensitivity) int {
  return tsctspath.ComparePaths(p0, p1, p2)
}

func ComparePathsRelativeTo(p0 string, p1 string, p2 tsctspath.RootedDirectoryPath, p3 tsctspath.CaseSensitivity) int {
  return tsctspath.ComparePathsRelativeTo(p0, p1, p2, p3)
}

func ContainsIgnoredDirectory(p0 tsctspath.RootedDirectoryPath) bool {
  return tsctspath.ContainsIgnoredDirectory(p0)
}

func ContainsIgnoredPath(p0 tsctspath.RootedPath) bool {
  return tsctspath.ContainsIgnoredPath(p0)
}

func ContainsIgnoredPathKey(p0 tsctspath.PathKey) bool {
  return tsctspath.ContainsIgnoredPathKey(p0)
}

func ContainsPath(p0 string, p1 string, p2 tsctspath.CaseSensitivity) bool {
  return tsctspath.ContainsPath(p0, p1, p2)
}

func ConvertToRelativePath(p0 string, p1 tsctspath.RootedDirectoryPath, p2 tsctspath.CaseSensitivity) string {
  return tsctspath.ConvertToRelativePath(p0, p1, p2)
}

func DecodeDynamicURINoPath(p0 string) (string, bool) {
  return tsctspath.DecodeDynamicURINoPath(p0)
}

func DecodeDynamicURIPath(p0 string) string {
  return tsctspath.DecodeDynamicURIPath(p0)
}

func DecodeDynamicURIPathForDisk(p0 string) (string, bool) {
  return tsctspath.DecodeDynamicURIPathForDisk(p0)
}

func DecodeDynamicURIPathSegment(p0 string) string {
  return tsctspath.DecodeDynamicURIPathSegment(p0)
}

const DirectorySeparator = tsctspath.DirectorySeparator

const DynamicURIFileNamePrefix = tsctspath.DynamicURIFileNamePrefix

func DynamicURIPathToModuleSpecifier(p0 string) string {
  return tsctspath.DynamicURIPathToModuleSpecifier(p0)
}

func EncodeDynamicDirectorySpecifier(p0 string) string {
  return tsctspath.EncodeDynamicDirectorySpecifier(p0)
}

func EncodeDynamicLogicalModuleSpecifier(p0 string) string {
  return tsctspath.EncodeDynamicLogicalModuleSpecifier(p0)
}

func EncodeDynamicModuleSpecifier(p0 string) string {
  return tsctspath.EncodeDynamicModuleSpecifier(p0)
}

func EncodeDynamicRelativeURIDirectoryPath(p0 string) string {
  return tsctspath.EncodeDynamicRelativeURIDirectoryPath(p0)
}

func EncodeDynamicRelativeURIPath(p0 string) string {
  return tsctspath.EncodeDynamicRelativeURIPath(p0)
}

func EncodeDynamicURIDirectoryPath(p0 string) string {
  return tsctspath.EncodeDynamicURIDirectoryPath(p0)
}

func EncodeDynamicURINoPath(p0 string) string {
  return tsctspath.EncodeDynamicURINoPath(p0)
}

func EncodeDynamicURIPath(p0 string) string {
  return tsctspath.EncodeDynamicURIPath(p0)
}

func EncodeDynamicURIPathWithSuffix(p0 string, p1 string) string {
  return tsctspath.EncodeDynamicURIPathWithSuffix(p0, p1)
}

func EnsurePathIsNonModuleName(p0 string) string {
  return tsctspath.EnsurePathIsNonModuleName(p0)
}

func EnsureTrailingDirectorySeparator(p0 string) string {
  return tsctspath.EnsureTrailingDirectorySeparator(p0)
}

const ExtensionCjs = tsctspath.ExtensionCjs

const ExtensionCts = tsctspath.ExtensionCts

const ExtensionDcts = tsctspath.ExtensionDcts

const ExtensionDmts = tsctspath.ExtensionDmts

const ExtensionDts = tsctspath.ExtensionDts

func ExtensionIsOneOf(p0 string, p1 []string) bool {
  return tsctspath.ExtensionIsOneOf(p0, p1)
}

func ExtensionIsTs(p0 string) bool {
  return tsctspath.ExtensionIsTs(p0)
}

const ExtensionJs = tsctspath.ExtensionJs

const ExtensionJson = tsctspath.ExtensionJson

const ExtensionJsx = tsctspath.ExtensionJsx

const ExtensionMjs = tsctspath.ExtensionMjs

const ExtensionMts = tsctspath.ExtensionMts

const ExtensionTs = tsctspath.ExtensionTs

const ExtensionTsBuildInfo = tsctspath.ExtensionTsBuildInfo

const ExtensionTsx = tsctspath.ExtensionTsx

var ExtensionsNotSupportingExtensionlessResolution = tsctspath.ExtensionsNotSupportingExtensionlessResolution

func FileExtensionIs(p0 string, p1 string) bool {
  return tsctspath.FileExtensionIs(p0, p1)
}

func FileExtensionIsOneOf(p0 string, p1 []string) bool {
  return tsctspath.FileExtensionIsOneOf(p0, p1)
}

type FileNameStem = tsctspath.FileNameStem

type FileSpec = tsctspath.FileSpec

func ForceEncodeDynamicURIPathSegment(p0 string, p1 bool) string {
  return tsctspath.ForceEncodeDynamicURIPathSegment(p0, p1)
}

func GetAnyExtensionFromPath(p0 string, p1 []string, p2 tsctspath.CaseSensitivity) string {
  return tsctspath.GetAnyExtensionFromPath(p0, p1, p2)
}

func GetBaseFileName(p0 string) string {
  return tsctspath.GetBaseFileName(p0)
}

func GetCommonParentDirectories(p0 []tsctspath.RootedDirectoryPath, p1 int, p2 func(tsctspath.RootedDirectoryPath) []string, p3 tsctspath.CaseSensitivity) ([]tsctspath.RootedDirectoryPath, map[tsctspath.RootedDirectoryPath]struct{}) {
  return tsctspath.GetCommonParentDirectories(p0, p1, p2, p3)
}

func GetDeclarationEmitExtensionForPath(p0 string) string {
  return tsctspath.GetDeclarationEmitExtensionForPath(p0)
}

func GetDeclarationFileExtension(p0 string) string {
  return tsctspath.GetDeclarationFileExtension(p0)
}

func GetDirectoryPath(p0 string) string {
  return tsctspath.GetDirectoryPath(p0)
}

func GetEncodedRootLength(p0 string) int {
  return tsctspath.GetEncodedRootLength(p0)
}

func GetLongestExtensionFromPath(p0 string, p1 []string, p2 tsctspath.CaseSensitivity) string {
  return tsctspath.GetLongestExtensionFromPath(p0, p1, p2)
}

func GetNormalizedAbsolutePath(p0 string, p1 tsctspath.RootedDirectoryPath) string {
  return tsctspath.GetNormalizedAbsolutePath(p0, p1)
}

func GetNormalizedPathComponents(p0 string, p1 string) []string {
  return tsctspath.GetNormalizedPathComponents(p0, p1)
}

func GetPathComponents(p0 string) []string {
  return tsctspath.GetPathComponents(p0)
}

func GetPathComponentsRelativeTo(p0 string, p1 string, p2 tsctspath.CaseSensitivity) []string {
  return tsctspath.GetPathComponentsRelativeTo(p0, p1, p2)
}

func GetPathFromPathComponents(p0 []string) string {
  return tsctspath.GetPathFromPathComponents(p0)
}

func GetPossibleOriginalInputExtensionForExtension(p0 string) []string {
  return tsctspath.GetPossibleOriginalInputExtensionForExtension(p0)
}

func GetRelativePathFromDirectory(p0 string, p1 string, p2 tsctspath.CaseSensitivity) string {
  return tsctspath.GetRelativePathFromDirectory(p0, p1, p2)
}

func GetRelativePathFromFile(p0 string, p1 string, p2 tsctspath.CaseSensitivity) string {
  return tsctspath.GetRelativePathFromFile(p0, p1, p2)
}

func GetRelativePathToDirectoryOrUrl(p0 string, p1 string, p2 bool, p3 tsctspath.CaseSensitivity) string {
  return tsctspath.GetRelativePathToDirectoryOrUrl(p0, p1, p2, p3)
}

func GetRootLength(p0 string) int {
  return tsctspath.GetRootLength(p0)
}

func HasExtension(p0 string) bool {
  return tsctspath.HasExtension(p0)
}

func HasImplementationTSFileExtension(p0 string) bool {
  return tsctspath.HasImplementationTSFileExtension(p0)
}

func HasJSFileExtension(p0 string) bool {
  return tsctspath.HasJSFileExtension(p0)
}

func HasJSONFileExtension(p0 string) bool {
  return tsctspath.HasJSONFileExtension(p0)
}

func HasTSFileExtension(p0 string) bool {
  return tsctspath.HasTSFileExtension(p0)
}

func HasTrailingDirectorySeparator(p0 string) bool {
  return tsctspath.HasTrailingDirectorySeparator(p0)
}

func IsDeclarationFileName(p0 string) bool {
  return tsctspath.IsDeclarationFileName(p0)
}

func IsDynamicFileName(p0 string) bool {
  return tsctspath.IsDynamicFileName(p0)
}

func IsEncodedDynamicFileName(p0 string) bool {
  return tsctspath.IsEncodedDynamicFileName(p0)
}

func IsExternalModuleNameRelative(p0 string) bool {
  return tsctspath.IsExternalModuleNameRelative(p0)
}

func IsRootedDiskPath(p0 string) bool {
  return tsctspath.IsRootedDiskPath(p0)
}

func IsUrl(p0 string) bool {
  return tsctspath.IsUrl(p0)
}

func IsVolumeCharacter(p0 byte) bool {
  return tsctspath.IsVolumeCharacter(p0)
}

type ModuleSpecifier = tsctspath.ModuleSpecifier

func NormalizePath(p0 string) string {
  return tsctspath.NormalizePath(p0)
}

func NormalizeSlashes(p0 string) string {
  return tsctspath.NormalizeSlashes(p0)
}

func PathIsAbsolute(p0 string) bool {
  return tsctspath.PathIsAbsolute(p0)
}

func PathIsRelative(p0 string) bool {
  return tsctspath.PathIsRelative(p0)
}

type PathKey = tsctspath.PathKey

func PathKeyFromCanonical(p0 string) tsctspath.PathKey {
  return tsctspath.PathKeyFromCanonical(p0)
}

type PathPattern = tsctspath.PathPattern

type RelativePath = tsctspath.RelativePath

func RelativePathFromNormalized(p0 string) tsctspath.RelativePath {
  return tsctspath.RelativePathFromNormalized(p0)
}

func RemoveAnyFileExtension(p0 string) string {
  return tsctspath.RemoveAnyFileExtension(p0)
}

func RemoveExtension(p0 string, p1 string) string {
  return tsctspath.RemoveExtension(p0, p1)
}

func RemoveFileExtension(p0 string) string {
  return tsctspath.RemoveFileExtension(p0)
}

func RemoveTrailingDirectorySeparator(p0 string) string {
  return tsctspath.RemoveTrailingDirectorySeparator(p0)
}

func ResolvePath(p0 string, p1 ...string) string {
  return tsctspath.ResolvePath(p0, p1...)
}

func ResolvePathWithoutTrailingDirectorySeparator(p0 string, p1 ...string) string {
  return tsctspath.ResolvePathWithoutTrailingDirectorySeparator(p0, p1...)
}

func ResolveRelativePathFromDirectory(p0 string, p1 string, p2 tsctspath.RootedDirectoryPath, p3 tsctspath.CaseSensitivity) string {
  return tsctspath.ResolveRelativePathFromDirectory(p0, p1, p2, p3)
}

func ResolveRelativePathToDirectoryOrUrl(p0 string, p1 string, p2 bool, p3 tsctspath.RootedDirectoryPath, p4 tsctspath.CaseSensitivity) string {
  return tsctspath.ResolveRelativePathToDirectoryOrUrl(p0, p1, p2, p3, p4)
}

type RootedDirectoryPath = tsctspath.RootedDirectoryPath

func RootedDirectoryPathFromAbsolute(p0 string) tsctspath.RootedDirectoryPath {
  return tsctspath.RootedDirectoryPathFromAbsolute(p0)
}

func RootedDirectoryPathFromNormalized(p0 string) tsctspath.RootedDirectoryPath {
  return tsctspath.RootedDirectoryPathFromNormalized(p0)
}

func RootedDirectoryPathFromPath(p0 tsctspath.RootedPath) tsctspath.RootedDirectoryPath {
  return tsctspath.RootedDirectoryPathFromPath(p0)
}

type RootedFilePath = tsctspath.RootedFilePath

func RootedFilePathFromAbsolute(p0 string) tsctspath.RootedFilePath {
  return tsctspath.RootedFilePathFromAbsolute(p0)
}

func RootedFilePathFromNormalized(p0 string) tsctspath.RootedFilePath {
  return tsctspath.RootedFilePathFromNormalized(p0)
}

func RootedFilePathFromPath(p0 tsctspath.RootedPath) tsctspath.RootedFilePath {
  return tsctspath.RootedFilePathFromPath(p0)
}

type RootedPath = tsctspath.RootedPath

func RootedPathFromAbsolute(p0 string) tsctspath.RootedPath {
  return tsctspath.RootedPathFromAbsolute(p0)
}

func RootedPathFromNormalized(p0 string) tsctspath.RootedPath {
  return tsctspath.RootedPathFromNormalized(p0)
}

type SourceMapLocation = tsctspath.SourceMapLocation

func SplitVolumePath(p0 string) (string, string, bool) {
  return tsctspath.SplitVolumePath(p0)
}

func StartsWithDirectory(p0 string, p1 string, p2 tsctspath.CaseSensitivity) bool {
  return tsctspath.StartsWithDirectory(p0, p1, p2)
}

var SupportedDeclarationExtensions = tsctspath.SupportedDeclarationExtensions

var SupportedJSExtensions = tsctspath.SupportedJSExtensions

var SupportedJSExtensionsFlat = tsctspath.SupportedJSExtensionsFlat

var SupportedTSExtensions = tsctspath.SupportedTSExtensions

var SupportedTSExtensionsFlat = tsctspath.SupportedTSExtensionsFlat

var SupportedTSExtensionsWithJson = tsctspath.SupportedTSExtensionsWithJson

var SupportedTSExtensionsWithJsonFlat = tsctspath.SupportedTSExtensionsWithJsonFlat

var SupportedTSImplementationExtensions = tsctspath.SupportedTSImplementationExtensions

func ToFileNameLowerCase(p0 string) string {
  return tsctspath.ToFileNameLowerCase(p0)
}

func ToFileSpec(p0 string) tsctspath.FileSpec {
  return tsctspath.ToFileSpec(p0)
}

func ToModuleSpecifier(p0 string) tsctspath.ModuleSpecifier {
  return tsctspath.ToModuleSpecifier(p0)
}

func ToPathPattern(p0 string) tsctspath.PathPattern {
  return tsctspath.ToPathPattern(p0)
}

func ToRelativePath(p0 string) tsctspath.RelativePath {
  return tsctspath.ToRelativePath(p0)
}

func ToRootedDirectoryPath(p0 string, p1 tsctspath.RootedDirectoryPath) tsctspath.RootedDirectoryPath {
  return tsctspath.ToRootedDirectoryPath(p0, p1)
}

func ToRootedFilePath(p0 string, p1 tsctspath.RootedDirectoryPath) tsctspath.RootedFilePath {
  return tsctspath.ToRootedFilePath(p0, p1)
}

func ToRootedPath(p0 string, p1 tsctspath.RootedDirectoryPath) tsctspath.RootedPath {
  return tsctspath.ToRootedPath(p0, p1)
}

func ToSourceMapLocation(p0 string) tsctspath.SourceMapLocation {
  return tsctspath.ToSourceMapLocation(p0)
}

func TryDecodeDynamicURIPath(p0 string) (string, bool) {
  return tsctspath.TryDecodeDynamicURIPath(p0)
}

func TryDecodeDynamicURIPathSegment(p0 string) (string, bool) {
  return tsctspath.TryDecodeDynamicURIPathSegment(p0)
}

func TryExtractTSExtension(p0 string) string {
  return tsctspath.TryExtractTSExtension(p0)
}

func TryGetExtensionFromPath(p0 string) string {
  return tsctspath.TryGetExtensionFromPath(p0)
}

func TryPathKeyFromCanonical(p0 string) (tsctspath.PathKey, bool) {
  return tsctspath.TryPathKeyFromCanonical(p0)
}

func TryRootedFilePathFromAbsolute(p0 string) (tsctspath.RootedFilePath, bool) {
  return tsctspath.TryRootedFilePathFromAbsolute(p0)
}

func TryRootedFilePathFromNormalized(p0 string) (tsctspath.RootedFilePath, bool) {
  return tsctspath.TryRootedFilePathFromNormalized(p0)
}

func TryRootedPathFromAbsolute(p0 string) (tsctspath.RootedPath, bool) {
  return tsctspath.TryRootedPathFromAbsolute(p0)
}

func TryRootedPathFromNormalized(p0 string) (tsctspath.RootedPath, bool) {
  return tsctspath.TryRootedPathFromNormalized(p0)
}
