import assert from "node:assert/strict";
import { spawn, spawnSync, type ChildProcessWithoutNullStreams } from "node:child_process";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";
import { TestProject } from "@ttsc/testing";

type Peer = {
  alive(): boolean;
  write(line: string, done: (error?: Error | null) => void): void;
  close(terminate: boolean): void | Promise<void>;
};
type Open = (
  binary: string,
  args: string[],
  events: { line(line: string): void; error(error: Error): void; exit(code: number | null, signal: NodeJS.Signals | null): void },
  options: { stderr: "capture" | "drain" },
) => Peer;

/**
 * Verifies the real line adapter joins process and stdio lifetime.
 *
 * A Node exit event can precede inherited stdio closure. These authored child
 * programs exercise kernel lifetime only and produce no native graph frames.
 *
 * 1. Open actual Node children through the owning adapter's executable/argv API.
 * 2. Check EOF success, exit failure, forced retirement and inherited stdio.
 * 3. Collect every independent case, preserving rejected shutdown authority.
 *
 * @evidence contracts/testing.md#behavioral-verification Actual child close promises distinguish zero-exit EOF joining from nonzero and forced termination, and remain pending at a parent's exit while inherited stdio remains open.
 * @evidence contracts/testing.md#independent-expectations Authored Node programs define literal zero/two exit codes and a child-held pipe; no response, expected field or result is generated by the adapter.
 * @evidence contracts/testing.md#distinguishing-cases EOF, duplicate close, preexisting exit, exit two, ignored EOF and inherited pipes exercise distinct release paths. The blocking-child row distinguishes delayed event-loop dispatch from refusal of stdin EOF without changing forced or unknown failure into success. A valid changed-list frame larger than pipe capacity sent to an unread child requires bounded close rejection, queued-write rejection and actual child exit; repeated close retains the same failed completion.
 * @evidence contracts/testing.md#execution-ownership This matching os-boundaries export executes actual Node processes; the shared OS collector executes this authored-source Graph boundary; it does not certify an installed Graph package.
 * @evidence contracts/e2e.md#necessary-boundary Process exit and stdio close ordering, actual stdin EOF and forced kill cannot be established by a declared in-memory transport.
 * @evidence contracts/e2e.md#shared-execution All seven cases share the adapter, current Node executable and the same authored OS fixture family as ResidentCheckProcess without building a compiler or installing another consumer. Each distinct child lifetime needs its own child.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each case joins its owned process before the next. The Windows process-handle observer initializes before creating the inherited-pipe holder, so shell startup cannot race holder release; POSIX observes its absence. The static worker inputs and release marker end after all known child joins; no cache state is created.
 * @evidence contracts/e2e.md#preserved-coverage Real Go resident protocol and facade joining remain separate integration obligations; these assertions establish only the adapter's OS lifetime authority.
 */
export async function case_ttscgraph_line_peer_joins_actual_child_lifetimes(
  supplied?: Open,
): Promise<void> {
  const open: Open = supplied ?? (await import(new URL("../../../../../../../packages/graph/src/model/TtscGraphLinePeer.ts", import.meta.url).href)).TtscGraphLinePeer.open;
  assert.equal(typeof open, "function", "the owning open operation must exist before allocation");
  const failures: Error[] = [];
  const root = TestProject.tmpdir("ttsc-graph-stdio-");
  TestProject.copyDirectory(path.resolve(import.meta.dirname, "../../../../../fixtures/os/process-lifetime"), root);
  let retained = false;
  const hold = path.join(root, "hold");
  for (const scenario of ["eof", "nonzero", "forced", "already-exited", "inherited-stdio", "blocked-event-loop", "unread"] as const) {
    let peer: Peer | undefined;
    let descendantJoin: Promise<void> | undefined;
    let descendantJoined = false;
    let observer: ChildProcessWithoutNullStreams | undefined;
    let observerOutput = "";
    let acquired: Promise<void> | undefined;
    try {
      let ready!: () => void;
      let exited!: () => void;
      const started = new Promise<void>((resolve) => { ready = resolve; });
      const exit = new Promise<void>((resolve) => { exited = resolve; });
      let observed!: () => void;
      const identity = new Promise<void>((resolve) => { observed = resolve; });
      let descendantPid = 0;
      const inherited = scenario === "inherited-stdio";
      if (inherited && process.platform === "win32") {
        // Start the process-handle observer before creating the pipe holder.
        // PowerShell initialization is not part of the adapter's lifetime.
        observer = spawn(path.join(process.env.SystemRoot!, "System32/WindowsPowerShell/v1.0/powershell.exe"), [
          "-NoProfile", "-NonInteractive", "-Command",
          "[Console]::WriteLine('ready'); $identity=[Console]::ReadLine(); if ($identity -eq $null) { exit 0 }; $p=Get-Process -Id ([int]$identity) -ErrorAction Stop; $handle=$p.Handle; [Console]::WriteLine('opened'); $p.WaitForExit(); [Console]::WriteLine('joined'); $p.Dispose()",
        ], { stdio: "pipe", windowsHide: true });
        let stderr = "";
        let initialized!: () => void;
        let opened!: () => void;
        const initialization = new Promise<void>((resolve) => { initialized = resolve; });
        acquired = new Promise<void>((resolve) => { opened = resolve; });
        observer.stdout.on("data", (chunk) => {
          observerOutput += String(chunk);
          if (observerOutput.includes("ready")) initialized();
          if (observerOutput.includes("opened")) opened();
        });
        observer.stderr.on("data", (chunk) => { stderr += String(chunk); });
        descendantJoin = new Promise<void>((resolve, reject) => {
          observer!.once("error", (error) => { initialized(); opened(); reject(error); });
          observer!.once("close", (code, signal) => {
            initialized();
            opened();
            if (code === 0 && signal === null && observerOutput.includes("joined")) resolve();
            else reject(new Error(`descendant handle join failed: ${code}/${signal}: ${stderr}`));
          });
        });
        void descendantJoin.catch(() => undefined);
        await bounded(initialization, "process observer initialization", 30_000);
        assert.ok(observerOutput.includes("ready"), "process observer must initialize before the pipe holder");
      }
      if (inherited) {
        fs.writeFileSync(hold, "owned");
      }
      const binary = process.execPath;
      const args = [path.join(root, "worker.cjs"), "graph", scenario, hold];
      peer = open(binary, args, {
        line: (line) => {
          ready();
          const prefix = `${process.execPath} `;
          if (line.startsWith(prefix)) {
            descendantPid = Number(line.slice(prefix.length));
            observed();
          }
        }, error: () => ready(), exit: () => { exited(); ready(); },
      }, { stderr: "capture" });
      await bounded(started, "child readiness");
      if (scenario === "already-exited" || scenario === "inherited-stdio") await bounded(exit, "parent exit");
      if (inherited) {
        await bounded(identity, "descendant identity");
        assert.ok(Number.isSafeInteger(descendantPid) && descendantPid > 0);
        if (observer !== undefined) {
          // Acquire the actual process handle before retirement. WaitForExit
          // keeps this identity even if its numeric PID is later recycled.
          observer.stdin.end(String(descendantPid) + "\n");
          await bounded(acquired!, "descendant handle acquisition");
          assert.ok(observerOutput.includes("opened"), "actual descendant handle acquired");
        }
      }
      const pendingWrite = scenario === "unread" ? new Promise<void>((resolve, reject) => {
        peer!.write(JSON.stringify({ changed: ["x".repeat(8 * 1024 * 1024)] }), (error) => error ? reject(error) : resolve());
      }) : undefined;
      void pendingWrite?.catch(() => undefined);
      const closing = peer.close(true);
      assert.ok(closing instanceof Promise, "actual adapter must expose joined completion");
      assert.equal(peer.close(true), closing, "repeated close owns one completion");
      if (scenario === "blocked-event-loop") {
        const blocked = spawnSync(process.execPath, [path.join(root, "blocker.cjs")]);
        assert.equal(blocked.status, 0, "test-owned blocking child must join");
      }
      if (scenario === "inherited-stdio") {
        let settled = false;
        void closing.then(() => { settled = true; }, () => { settled = true; });
        await Promise.resolve();
        assert.equal(settled, false, "parent exit does not join inherited stdio");
        fs.unlinkSync(hold);
      }
      if (scenario === "unread") await assert.rejects(bounded(closing, "unread child retirement"), (error: unknown) => {
        assert.ok(error instanceof Error);
        // Node may publish the real pipe write error before joined close. The
        // adapter preserves that native error instead of replacing its cause.
        assert.ok(/shutdown failed/.test(error.message) || ["EOF", "EPIPE", "ERR_STREAM_DESTROYED"].includes((error as NodeJS.ErrnoException).code ?? ""), `Unexpected unread-input failure: ${String(error)}`);
        return true;
      });
      else if (scenario === "nonzero" || scenario === "forced") await assert.rejects(bounded(closing, "failed child retirement"), /shutdown failed/);
      else await closing;
      if (pendingWrite !== undefined) await assert.rejects(bounded(pendingWrite, "unread input completion"));
      await bounded(exit, "parent exit");
      assert.equal(peer.alive(), false);
      if (descendantJoin !== undefined) {
        await bounded(descendantJoin, "descendant handle exit");
        descendantJoined = true;
      }
      else if (inherited) {
        let absent = false;
        for (let attempt = 0; attempt < 100 && !absent; attempt++) {
          try { process.kill(descendantPid, 0); }
          catch (error) { if ((error as NodeJS.ErrnoException).code === "ESRCH") absent = true; else throw error; }
          if (!absent) await new Promise((resolve) => setTimeout(resolve, 10));
        }
        assert.equal(absent, true, "observed descendant has exited");
        descendantJoined = true;
      }
    } catch (error) {
      failures.push(new Error(`${scenario}: ${String(error)}`, { cause: error }));
    } finally {
      observer?.stdin.end();
      if (fs.existsSync(hold)) fs.unlinkSync(hold);
      if (peer !== undefined) await Promise.resolve(peer.close(true)).catch((error) => {
        if (scenario !== "nonzero" && scenario !== "forced" && scenario !== "unread") failures.push(new Error(`${scenario} cleanup: ${String(error)}`));
      });
      if (descendantJoin !== undefined) await bounded(descendantJoin, "descendant cleanup").then(() => {
        descendantJoined = true;
      }, (error) => failures.push(new Error(`${scenario} descendant: ${String(error)}`)));
      if (scenario === "inherited-stdio" && !descendantJoined) {
        retained = true;
        TestProject.retainTemporaryDirectory(root, "The inherited output-pipe owner was not joined.");
      }
    }
  }
  assert.equal(path.dirname(root), path.resolve(os.tmpdir()));
  if (!retained) {
    await fs.promises.rm(root, { recursive: true });
    assert.equal(fs.existsSync(root), false);
  }
  if (failures.length > 0) throw new AggregateError(failures, "line peer lifetime matrix failed");
}

/** Bound test-owned readiness and handle observations without changing adapter deadlines. */
async function bounded<T>(pending: Promise<T>, name: string, milliseconds = 8_000): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([pending, new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error(`${name} did not settle`)), milliseconds); })]);
  } finally { if (timer !== undefined) clearTimeout(timer); }
}
