// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package printer is the documented github.com/microsoft/typescript-go/shim/printer plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/printer, the
// bridge that reaches the compiler's internal packages.
package printer

import (
  tscast "github.com/microsoft/TypeScript/tsc/shim/ast"
  tsccore "github.com/microsoft/TypeScript/tsc/shim/core"
  tscprinter "github.com/microsoft/TypeScript/tsc/shim/printer"
)

type AutoGenerateOptions = tscprinter.AutoGenerateOptions

type EmitContext = tscprinter.EmitContext

type EmitHost = tscprinter.EmitHost

type EmitResolver = tscprinter.EmitResolver

func EmitSourceFile(p0 *tscprinter.Printer, p1 *tscast.SourceFile) string {
  return tscprinter.EmitSourceFile(p0, p1)
}

func EmitSourceFileWithSourceMap(p0 tscprinter.PrinterOptions, p1 tscprinter.PrintHandlers, p2 *tscprinter.EmitContext, p3 *tscast.SourceFile) (string, string) {
  return tscprinter.EmitSourceFileWithSourceMap(p0, p1, p2, p3)
}

type EmitTextWriter = tscprinter.EmitTextWriter

type GeneratedIdentifierFlags = tscprinter.GeneratedIdentifierFlags

const GeneratedIdentifierFlagsAllowNameSubstitution = tscprinter.GeneratedIdentifierFlagsAllowNameSubstitution

const GeneratedIdentifierFlagsAuto = tscprinter.GeneratedIdentifierFlagsAuto

const GeneratedIdentifierFlagsFileLevel = tscprinter.GeneratedIdentifierFlagsFileLevel

const GeneratedIdentifierFlagsKindMask = tscprinter.GeneratedIdentifierFlagsKindMask

const GeneratedIdentifierFlagsLoop = tscprinter.GeneratedIdentifierFlagsLoop

const GeneratedIdentifierFlagsNode = tscprinter.GeneratedIdentifierFlagsNode

const GeneratedIdentifierFlagsNone = tscprinter.GeneratedIdentifierFlagsNone

const GeneratedIdentifierFlagsOptimistic = tscprinter.GeneratedIdentifierFlagsOptimistic

const GeneratedIdentifierFlagsReservedInNestedScopes = tscprinter.GeneratedIdentifierFlagsReservedInNestedScopes

const GeneratedIdentifierFlagsUnique = tscprinter.GeneratedIdentifierFlagsUnique

func NewEmitContext() *tscprinter.EmitContext {
  return tscprinter.NewEmitContext()
}

func NewPrinter(p0 tscprinter.PrinterOptions, p1 tscprinter.PrintHandlers, p2 *tscprinter.EmitContext) *tscprinter.Printer {
  return tscprinter.NewPrinter(p0, p1, p2)
}

func NewTextWriter(p0 string, p1 int) tscprinter.EmitTextWriter {
  return tscprinter.NewTextWriter(p0, p1)
}

type PrintHandlers = tscprinter.PrintHandlers

type Printer = tscprinter.Printer

type PrinterOptions = tscprinter.PrinterOptions

func RangeStartPositionsAreOnSameLine(p0 tsccore.TextRange, p1 tsccore.TextRange, p2 *tscast.SourceFile) bool {
  return tscprinter.RangeStartPositionsAreOnSameLine(p0, p1, p2)
}
