// Code generated by packages/ttsc/tools/gen_facade. DO NOT EDIT.

// Package osvfs is the documented github.com/microsoft/typescript-go/shim/vfs/osvfs plugin import path.
// It aliases every exported identity of github.com/microsoft/TypeScript/tsc/shim/vfs/osvfs, the
// bridge that reaches the compiler's internal packages.
package osvfs

import (
  tscvfs "github.com/microsoft/TypeScript/tsc/shim/vfs"
  tscosvfs "github.com/microsoft/TypeScript/tsc/shim/vfs/osvfs"
)

func FS() tscvfs.FS {
  return tscosvfs.FS()
}

func GetGlobalTypingsCacheLocation() string {
  return tscosvfs.GetGlobalTypingsCacheLocation()
}
