// Code generated by packages/ttsc/tools/shim_audit -fix. DO NOT EDIT.
//
// Closes every exposed enum family: re-exports each upstream member so a
// plugin that can name the enum type can name all of its values. Prevents
// the #230 class (a sibling const silently missing). Regenerate after a
// typescript-go bump with `go run ./tools/shim_audit -fix`.

package core

import innercore "github.com/microsoft/typescript-go/internal/core"

const (
  TSUnknown = innercore.TSUnknown
)
