import { TestProject, TestUnpluginRuntime } from "@ttsc/testing";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import { BatchWorkspace } from "../batch/BatchWorkspace";

/**
 * Executes repeated completed builds and a fresh public runtime preload over
 * the same source graph and native producer. The original single-entry
 * lifecycle owns a separate upfront project inside that workspace: its two
 * builds share the existing build child, while its immutable public preload
 * needs a distinct process from the full graph's configured preload.
 *
 * @evidence contracts/testing.md#behavioral-verification One Bun child performs two full-graph builds with the same adapter object and loads distinct delivered CommonJS artifacts with the full value/effect oracle. Each full graph epoch requires exactly one named native ApplyProgram invocation and its configured admission receipts, including under Bun's incomplete observer. In the same child, two original single-entry builds retain literal PLUGIN and exact named ApplyProgram ticks 0/1/2. Distinct public preload processes execute the full typed graph and original single entry; the latter prints PLUGIN and adds one invocation after the four additional Turbopack loader lifecycle calls. Production returns PLUGIN with one cacheable(false), absent/throwing withdrawal and development refuse, and each actual loader call owns one invocation.
 * @evidence contracts/testing.md#independent-expectations Literal42/retained and pre-print UTF-16 inputs are independent of Bun's generated bytes. Actual installed runtime emit owns the throwing strip control; this API consumer retains parsed source values.
 * @evidence contracts/testing.md#distinguishing-cases JSX quoting, control characters, JSON aliases and stripped versus retained statements coexist in one source graph.
 * @evidence contracts/testing.md#execution-ownership Selected Bun owns one build child with four actual builds, four real Turbopack loader callbacks under Bun and two distinct fresh preload children. The single-entry producer is the real owning SDK fixture. Native admission receipts and probe ticks count named hook invocations, not all Programs, processes or cache hits.
 * @evidence contracts/e2e.md#necessary-boundary Actual Bun resolves the built adapter, runs its native transform callbacks and delivers loadable bundle bytes; callback units cannot certify that host delivery.
 * @evidence contracts/e2e.md#shared-execution Both graph builds share one child/adapter/source population; both single-entry builds share a second adapter in that same child and one upfront namespace. No extra install or prepare is added. Incompatible immutable preload configurations require separate process sessions, adding one actual Bun lifetime and two actual builds over the prior graph-only batch. The four loader lifecycle calls reuse this child and the same prepared single-entry native plugin, adding no installation or preparation namespace. Named native ApplyProgram invocations are measured, not all compiler Programs or native tool subprocesses.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each child receives an explicit cache path and leaves authored graph/config inputs unchanged. Nonzero status, signal or spawn error fails; synchronous return and actual PID ESRCH precede completed reuse. No overlapping loader pretends to change a locked runtime configuration. Uncertain consumers keep shared inputs; these joins do not independently certify every native descendant.
 * @evidence contracts/e2e.md#preserved-coverage The original one-entry two-build/fresh-preload PLUGIN and exact tick contrast has its own shared namespace. Full typed graph values, side effects and actual fresh native preload remain distinct supplemental checks; the full graph now requires one named native invocation per pass as the #1712 regression oracle. Portable notifyWatchInputs and registration option/name/fallthrough semantics retain their owning units. The named probe tick counts actual ApplyProgram invocations, not all native Programs or host processes. Written connections await actual execution.
 */
export async function test_e2e_bun_batch(): Promise<void> {
  const workspace = await BatchWorkspace.open();
  const receiptOffset = BatchWorkspace.readContextReceipts(workspace).length;
  const tickOffset = fs.existsSync(workspace.programRunLog)
    ? fs.statSync(workspace.programRunLog).size
    : 0;
  const result = TestProject.spawn(
    process.env.TTSC_BUN_BINARY ?? "bun",
    ["bun-entry.mjs"],
    {
      cwd: workspace.root,
      env: {
        TTSC_CACHE_DIR: workspace.cache,
        TTSC_E2E_BUN_RECEIPTS: workspace.contextReceipt,
        TTSC_E2E_BUN_PROGRAM_LOG: workspace.programRunLog,
      },
    },
  );
  assert.equal(result.error, undefined);
  assert.equal(result.signal, null);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(
    result.stdout
      .split(/\r?\n/)
      .filter(
        (line) =>
          line ===
          "TTSC_TURBOPACK_LIFECYCLES:production,missing,throwing,development",
      ).length,
    1,
  );
  BatchWorkspace.assertResult(
    BatchWorkspace.readPayload(result.stdout),
    workspace.expected,
  );
  const second = result.stdout
    .split(/\r?\n/)
    .filter((line) => line.startsWith("TTSC_BUN_SECOND:"));
  assert.equal(second.length, 1);
  const [secondLine] = second;
  assert.equal(typeof secondLine, "string");
  assert.ok(secondLine !== undefined);
  BatchWorkspace.assertResult(
    JSON.parse(secondLine.slice("TTSC_BUN_SECOND:".length)),
    workspace.expected,
  );
  const epochLines = result.stdout
    .split(/\r?\n/)
    .filter((line) => line.startsWith("TTSC_BUN_EPOCHS:"));
  assert.equal(epochLines.length, 1);
  const [epochLinesLine] = epochLines;
  assert.equal(typeof epochLinesLine, "string");
  assert.ok(epochLinesLine !== undefined);
  const epochs = JSON.parse(
    epochLinesLine.slice("TTSC_BUN_EPOCHS:".length),
  ) as number[];
  assert.equal(epochs.length, 3);
  assert.equal(epochs[0], receiptOffset);
  const receipts = BatchWorkspace.readContextReceipts(workspace);
  assert.equal(epochs[2], receipts.length);
  const tickLines = result.stdout
    .split(/\r?\n/)
    .filter((line) => line.startsWith("TTSC_BUN_TICKS:"));
  assert.equal(tickLines.length, 1);
  const [tickLinesLine] = tickLines;
  assert.equal(typeof tickLinesLine, "string");
  assert.ok(tickLinesLine !== undefined);
  const deliveredTicks = JSON.parse(
    tickLinesLine.slice("TTSC_BUN_TICKS:".length),
  ) as number[];
  assert.equal(deliveredTicks.length, 3);
  assert.equal(deliveredTicks[0], tickOffset);
  for (let pass = 0; pass < 2; pass++) {
    const currentTick = deliveredTicks[pass];
    const nextTick = deliveredTicks[pass + 1];
    assert.ok(currentTick !== undefined && nextTick !== undefined);
    assert.equal(
      nextTick,
      currentTick + 1,
      "each full graph build must compile once, sharing its coherent local result across every module (#1712)",
    );
  }
  assert.equal(fs.statSync(workspace.programRunLog).size, deliveredTicks[2]);
  const singleTicks = result.stdout
    .split(/\r?\n/)
    .filter((line) => line.startsWith("TTSC_BUN_SINGLE_ENTRY_TICKS:"));
  assert.equal(singleTicks.length, 1);
  const [singleTicksLine] = singleTicks;
  assert.equal(typeof singleTicksLine, "string");
  assert.ok(singleTicksLine !== undefined);
  assert.deepEqual(
    JSON.parse(singleTicksLine.slice("TTSC_BUN_SINGLE_ENTRY_TICKS:".length)),
    [0, 1, 2],
  );
  for (let pass = 0; pass < 2; pass++) {
    const currentEpoch = epochs[pass];
    const nextEpoch = epochs[pass + 1];
    assert.ok(currentEpoch !== undefined && nextEpoch !== undefined);
    assert.ok(Number.isInteger(nextEpoch) && nextEpoch > currentEpoch);
    BatchWorkspace.assertContextReceipts(
      receipts.slice(currentEpoch, nextEpoch),
    );
  }
  if (!(result.pid > 0)) {
    BatchWorkspace.retain("Bun build child returned no owned process identity");
    throw new Error("Bun build child closure unresolved");
  }
  try {
    process.kill(result.pid, 0);
    BatchWorkspace.retain(
      "Bun build child remains live before fresh runtime startup",
    );
    throw new Error("Bun build child closure unresolved");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ESRCH") throw error;
  }
  const runtime = TestProject.spawn(
    process.env.TTSC_BUN_BINARY ?? "bun",
    [
      "--preload",
      path.join(
        path.dirname(TestUnpluginRuntime.libPath("bun", "mjs")),
        "bun-register.mjs",
      ),
      "bun-runtime-entry.mjs",
    ],
    { cwd: workspace.root, env: { TTSC_CACHE_DIR: workspace.cache } },
  );
  assert.equal(runtime.error, undefined);
  assert.equal(runtime.signal, null);
  assert.equal(runtime.status, 0, runtime.stderr);
  BatchWorkspace.assertResult(
    BatchWorkspace.readPayload(runtime.stdout),
    workspace.expected,
  );
  BatchWorkspace.assertContextReceipts(
    BatchWorkspace.readContextReceipts(workspace).slice(epochs[2]),
  );
  const lastDeliveredTick = deliveredTicks[2];
  assert.ok(lastDeliveredTick !== undefined);
  assert.equal(
    fs.statSync(workspace.programRunLog).size,
    lastDeliveredTick + 1,
    "the fresh full graph preload must not borrow a completed build's generation",
  );
  const singleRoot = path.join(workspace.root, "tools/bun-native-sessions");
  assert.equal(
    fs.statSync(path.join(singleRoot, "program-runs.bin")).size,
    6,
    "two single-entry builds and four real loader lifecycle calls each compile once",
  );
  const singleRuntime = TestProject.spawn(
    process.env.TTSC_BUN_BINARY ?? "bun",
    [
      "--preload",
      path.join(
        path.dirname(TestUnpluginRuntime.libPath("bun", "mjs")),
        "bun-register.mjs",
      ),
      "runtime.mjs",
    ],
    { cwd: singleRoot, env: { TTSC_CACHE_DIR: workspace.cache } },
  );
  assert.equal(singleRuntime.error, undefined);
  assert.equal(singleRuntime.signal, null);
  assert.equal(singleRuntime.status, 0, singleRuntime.stderr);
  assert.equal(singleRuntime.stdout.trim(), "PLUGIN");
  assert.equal(
    fs.statSync(path.join(singleRoot, "program-runs.bin")).size,
    7,
    "two original builds, four isolated loader lifecycle deliveries and one fresh preload each own one named ApplyProgram invocation",
  );
  for (const child of [runtime, singleRuntime]) {
    if (!(child.pid > 0)) {
      BatchWorkspace.retain("Bun preload returned no owned process identity");
      throw new Error("Bun preload closure unresolved");
    }
    try {
      process.kill(child.pid, 0);
      BatchWorkspace.retain(
        "Bun preload remains live after its synchronous return",
      );
      throw new Error("Bun preload closure unresolved");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ESRCH") throw error;
    }
  }
}
