import { TestProject } from "@ttsc/testing";
import assert from "node:assert/strict";
import { BatchWorkspace } from "../batch/BatchWorkspace";

/**
 * Executes the shared source graph through one actual Bun build host.
 *
 * @evidence contracts/testing.md#behavioral-verification One Bun child performs one Bun.build and evaluates its delivered CommonJS bytes; status0 and its sole labeled payload must contain every original value and utility observation.
 * @evidence contracts/testing.md#independent-expectations Literal42/retained and pre-print UTF-16 inputs are independent of Bun's generated bytes. The throwing discard call distinguishes missing strip behavior.
 * @evidence contracts/testing.md#distinguishing-cases JSX quoting, control characters, JSON aliases and stripped versus retained statements coexist in one source graph.
 * @evidence contracts/testing.md#execution-ownership Exactly one TestProject.spawn owns the Bun host. The authored entry invokes Bun.build once and assertion iteration invokes no product again.
 * @evidence contracts/e2e.md#necessary-boundary Actual Bun resolves the built adapter, runs its native transform callbacks and delivers loadable bundle bytes; callback units cannot certify that host delivery.
 * @evidence contracts/e2e.md#shared-execution The one prepared workspace serves one Bun host with the same source population used by all other immutable consumers.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity The child receives an explicit cache path and leaves the input graph unchanged. Nonzero status, signal or spawn error fails; uncertain consumers keep the shared inputs.
 * @evidence contracts/e2e.md#preserved-coverage Preserves actual Bun build delivery and the complete shared value oracle. This does not claim separate Bun preload, runtime registration or repeated lifecycle scenarios are certified by a single build.
 */
export async function test_e2e_bun_batch(): Promise<void> {
  const workspace = await BatchWorkspace.open();
  const result = TestProject.spawn(process.env.TTSC_BUN_BINARY ?? "bun", ["bun-entry.mjs"], {
    cwd: workspace.root,
    env: { TTSC_CACHE_DIR: workspace.cache },
  });
  assert.equal(result.error, undefined);
  assert.equal(result.signal, null);
  assert.equal(result.status, 0, result.stderr);
  BatchWorkspace.assertResult(BatchWorkspace.readPayload(result.stdout), workspace.expected);
}
