import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";

type Peer = {
  alive(): boolean;
  close(terminate: boolean): void | Promise<void>;
};
type Open = (
  binary: string,
  args: string[],
  events: { line(line: string): void; error(error: Error): void; exit(code: number | null, signal: NodeJS.Signals | null): void },
  options: { stderr: "capture" | "drain" },
) => Peer;

/**
 * Verifies the real line adapter joins process and stdio lifetime.
 *
 * A Node exit event can precede inherited stdio closure. These authored child
 * programs exercise kernel lifetime only and produce no native graph frames.
 *
 * 1. Open actual Node children through the owning adapter's executable/argv API.
 * 2. Check EOF success, exit failure, forced retirement and inherited stdio.
 * 3. Collect every independent case, preserving rejected shutdown authority.
 *
 * @evidence contracts/testing.md#behavioral-verification Actual child close promises distinguish zero-exit EOF joining from nonzero and forced termination, and remain pending at a parent's exit while inherited stdio remains open.
 * @evidence contracts/testing.md#independent-expectations Authored Node programs define literal zero/two exit codes and a child-held pipe; no response, expected field or result is generated by the adapter.
 * @evidence contracts/testing.md#distinguishing-cases EOF, duplicate close, preexisting exit, exit two, ignored EOF and inherited pipes exercise distinct release paths without changing unknown failure into success.
 * @evidence contracts/testing.md#execution-ownership This matching os-boundaries export executes actual Node processes; the shared OS collector executes this authored-source Graph boundary; it does not certify an installed Graph package.
 * @evidence contracts/e2e.md#necessary-boundary Process exit and stdio close ordering, actual stdin EOF and forced kill cannot be established by a declared in-memory transport.
 * @evidence contracts/e2e.md#shared-execution All five cases share the adapter and current Node executable without building a compiler or installing another consumer.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Each case joins its owned process before the next. The inherited-pipe row also waits for its observed descendant, using a native Windows process handle or POSIX absence observation; one confined release-file fixture controls the pipe holder and is removed after all known child joins; no cache state is created.
 * @evidence contracts/e2e.md#preserved-coverage Real Go resident protocol and facade joining remain separate integration obligations; these assertions establish only the adapter's OS lifetime authority.
 */
export async function test_ttscgraph_line_peer_joins_actual_child_lifetimes(
  supplied?: Open,
): Promise<void> {
  const open: Open = supplied ?? (await import(new URL("../../../../../../packages/graph/src/model/TtscGraphLinePeer.ts", import.meta.url).href)).TtscGraphLinePeer.open;
  assert.equal(typeof open, "function", "the owning open operation must exist before allocation");
  const failures: Error[] = [];
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "ttsc-graph-stdio-"));
  const hold = path.join(root, "hold");
  for (const scenario of ["eof", "nonzero", "forced", "already-exited", "inherited-stdio"] as const) {
    let peer: Peer | undefined;
    let descendantJoin: Promise<void> | undefined;
    try {
      let ready!: () => void;
      let exited!: () => void;
      const started = new Promise<void>((resolve) => { ready = resolve; });
      const exit = new Promise<void>((resolve) => { exited = resolve; });
      let observed!: () => void;
      const identity = new Promise<void>((resolve) => { observed = resolve; });
      let descendantPid = 0;
      const program = scenario === "already-exited"
          ? "console.log('ready');process.exit(0);"
          : "console.log('ready');process.stdin.resume();" + (scenario === "forced" ? "setInterval(()=>{},1000);" : `process.stdin.on('end',()=>process.exit(${scenario === "nonzero" ? 2 : 0}));`);
      const inherited = scenario === "inherited-stdio";
      const script = path.join(root, "holder.cjs");
      if (inherited) {
        fs.writeFileSync(hold, "owned");
        fs.writeFileSync(script, `const fs=require('node:fs');console.log(process.execPath,process.pid);const timer=setInterval(()=>{if(!fs.existsSync(${JSON.stringify(hold)})){clearInterval(timer);process.exit(0);}},10);`);
      }
      const binary = inherited ? (process.platform === "win32" ? process.env.ComSpec! : "/bin/sh") : process.execPath;
      const args = inherited
        ? process.platform === "win32"
          ? ["/d", "/s", "/c", `start /b "" "${process.execPath}" "${script}" & echo ready & exit /b 0`]
          : ["-c", `'${process.execPath.replaceAll("'", "'\\''")}' '${script.replaceAll("'", "'\\''")}' & echo ready; exit 0`]
        : ["-e", program];
      peer = open(binary, args, {
        line: (line) => {
          ready();
          const prefix = `${process.execPath} `;
          if (line.startsWith(prefix)) {
            descendantPid = Number(line.slice(prefix.length));
            observed();
          }
        }, error: () => ready(), exit: () => { exited(); ready(); },
      }, { stderr: "capture" });
      await bounded(started, "child readiness");
      if (scenario === "already-exited" || scenario === "inherited-stdio") await bounded(exit, "parent exit");
      if (inherited) {
        await bounded(identity, "descendant identity");
        assert.ok(Number.isSafeInteger(descendantPid) && descendantPid > 0);
        if (process.platform === "win32") {
          // Acquire the actual process handle before retirement. WaitForExit
          // keeps this identity even if its numeric PID is later recycled.
          const observer = spawn(path.join(process.env.SystemRoot!, "System32/WindowsPowerShell/v1.0/powershell.exe"), [
            "-NoProfile", "-NonInteractive", "-Command",
            `$p=Get-Process -Id ${descendantPid} -ErrorAction Stop; $handle=$p.Handle; [Console]::WriteLine('opened'); $p.WaitForExit(); [Console]::WriteLine('joined'); $p.Dispose()`,
          ], { stdio: ["ignore", "pipe", "pipe"], windowsHide: true });
          let output = "";
          let stderr = "";
          let opened!: () => void;
          const acquired = new Promise<void>((resolve) => { opened = resolve; });
          observer.stdout.on("data", (chunk) => { output += String(chunk); if (output.includes("opened")) opened(); });
          observer.stderr.on("data", (chunk) => { stderr += String(chunk); });
          descendantJoin = new Promise<void>((resolve, reject) => {
            observer.once("error", reject);
            observer.once("close", (code, signal) => {
              opened();
              if (code === 0 && signal === null && output.includes("joined")) resolve();
              else reject(new Error(`descendant handle join failed: ${code}/${signal}: ${stderr}`));
            });
          });
          void descendantJoin.catch(() => undefined);
          await bounded(acquired, "descendant handle acquisition");
          assert.ok(output.includes("opened"), "actual descendant handle acquired");
        }
      }
      const closing = peer.close(true);
      assert.ok(closing instanceof Promise, "actual adapter must expose joined completion");
      assert.equal(peer.close(true), closing, "repeated close owns one completion");
      if (scenario === "inherited-stdio") {
        let settled = false;
        void closing.then(() => { settled = true; }, () => { settled = true; });
        await Promise.resolve();
        assert.equal(settled, false, "parent exit does not join inherited stdio");
        fs.unlinkSync(hold);
      }
      if (scenario === "nonzero" || scenario === "forced") await assert.rejects(closing, /shutdown failed/);
      else await closing;
      await bounded(exit, "parent exit");
      assert.equal(peer.alive(), false);
      if (descendantJoin !== undefined) await bounded(descendantJoin, "descendant handle exit");
      else if (inherited) {
        let absent = false;
        for (let attempt = 0; attempt < 100 && !absent; attempt++) {
          try { process.kill(descendantPid, 0); }
          catch (error) { if ((error as NodeJS.ErrnoException).code === "ESRCH") absent = true; else throw error; }
          if (!absent) await new Promise((resolve) => setTimeout(resolve, 10));
        }
        assert.equal(absent, true, "observed descendant has exited");
      }
    } catch (error) {
      failures.push(new Error(`${scenario}: ${String(error)}`, { cause: error }));
    } finally {
      if (fs.existsSync(hold)) fs.unlinkSync(hold);
      if (peer !== undefined) await Promise.resolve(peer.close(true)).catch((error) => {
        if (scenario !== "nonzero" && scenario !== "forced") failures.push(new Error(`${scenario} cleanup: ${String(error)}`));
      });
      if (descendantJoin !== undefined) await bounded(descendantJoin, "descendant cleanup").catch((error) => failures.push(new Error(`${scenario} descendant: ${String(error)}`)));
    }
  }
  assert.equal(path.dirname(root), path.resolve(os.tmpdir()));
  await fs.promises.rm(root, { recursive: true });
  assert.equal(fs.existsSync(root), false);
  if (failures.length > 0) throw new AggregateError(failures, "line peer lifetime matrix failed");
}

/** Bound test-owned readiness and handle observations without changing adapter deadlines. */
async function bounded<T>(pending: Promise<T>, name: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([pending, new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error(`${name} did not settle`)), 8_000); })]);
  } finally { if (timer !== undefined) clearTimeout(timer); }
}
