import assert from "node:assert/strict";

import {
  type ObservedProcessReading,
  updateObservedProcessTree,
} from "../../../utils/src/ObservedProcessTree";

/**
 * Verifies observed ancestry rejects stale parent generations conservatively.
 *
 * A recorded old process cannot become the child of a newly created compiler
 * merely because its numeric parent ID matches. Equal-resolution values remain
 * possible edges, and malformed relevant identities remain explicit failures.
 * These typed records do not claim an OS recycling experiment or kernel join.
 *
 * 1. Replay the recorded stale-parent tree alongside the actual native lineage.
 * 2. Contrast fractional Windows order, equal POSIX seconds and calendar bounds.
 * 3. Preserve original root/child identities across replacement, orphan and
 *    malformed observations without adopting unrelated generations.
 *
 * @evidence contracts/testing.md#behavioral-verification The actual shared updateObservedProcessTree owner consumes typed OS readings and updates its caller-owned map. Literal accepted PID sets, original record identity and thrown observation errors distinguish legitimate ancestry from the recorded stale-PPID adoption and unknown metadata.
 * @evidence contracts/testing.md#independent-expectations A child predating its alleged parent cannot belong to that creation generation under the documented Win32 comparison premise. Authored valid Gregorian UTC dates, earlier/later microseconds and equal POSIX seconds define literal outcomes; no expected ancestry is generated by the owner. Equal values mean possible membership only, never certified native retirement.
 * @evidence contracts/testing.md#distinguishing-cases The recorded eight-process Windows lineage, reverse-order descendants, sub-millisecond older/newer/equal creation, Linux/Darwin second ties, year/month/leap/calendar boundaries, unavailable identities, unrelated malformed rows, duplicate relevant PIDs, replaced roots and parents, missing parents and still-live orphan children cover this owner's admission and retention differences. Actual Graph E2E separately owns OS production and original native completion.
 * @evidence contracts/testing.md#execution-ownership One discoverable Graph source unit calls the pure maintained helper directly in-process. It starts no scanner, process observer, compiler, host, installer or native producer and imports no E2E internals.
 */
export function test_graph_observed_process_tree_rejects_stale_parent_generations(): void {
  const reading = (
    pid: number,
    parent: number,
    identity: string,
    name = "owned",
  ): ObservedProcessReading => ({ pid, parent, identity, name, command: null });
  const keys = (tree: Map<number, ObservedProcessReading>): number[] =>
    [...tree.keys()].sort((left, right) => left - right);
  const win = (fraction: string): string => `2026-10-09T01:15:59.${fraction}Z`;

  const actual = [
    reading(45336, 13524, "2026-10-09T01:14:53.2093390Z", "node.exe"),
    reading(70384, 45336, "2026-10-09T01:15:55.9464370Z", "ttsc.exe"),
    reading(57360, 70384, "2026-10-09T01:15:56.0432110Z", "ttsc.exe"),
    reading(28132, 57360, "2026-10-09T01:15:56.1321760Z", "go.exe"),
    reading(54124, 28132, "2026-10-09T01:15:59.7333140Z", "compile.exe"),
    reading(48308, 54124, "2026-10-08T16:49:55.6874220Z", "unrelated"),
    reading(69220, 48308, "2026-10-08T16:49:55.9049440Z", "unrelated"),
    reading(59236, 69220, "2026-10-08T16:49:55.9296860Z", "unrelated"),
  ];
  const recorded = new Map<number, ObservedProcessReading>();
  updateObservedProcessTree(recorded, 45336, [...actual].reverse(), "win32");
  assert.deepEqual(keys(recorded), [28132, 45336, 54124, 57360, 70384]);
  updateObservedProcessTree(recorded, 45336, actual.slice(5), "win32");
  assert.deepEqual(keys(recorded), [28132, 45336, 54124, 57360, 70384]);
  assert.equal(actual.slice(5).some((row) => recorded.has(row.pid)), false);

  const root = reading(1, 0, win("0000020"));
  const child = reading(2, 1, win("0000030"));
  const grandchild = reading(3, 2, win("0000040"));
  const earlier = reading(4, 1, win("0000010"));
  const equal = reading(5, 1, root.identity);
  const fractional = new Map<number, ObservedProcessReading>();
  updateObservedProcessTree(
    fractional, 1, [grandchild, earlier, equal, child, root], "win32",
  );
  assert.deepEqual(keys(fractional), [1, 2, 3, 5]);
  assert.strictEqual(fractional.get(1), root);
  assert.strictEqual(fractional.get(2), child);
  updateObservedProcessTree(
    fractional, 1, [{ ...child, command: "changed display" }, root], "win32",
  );
  assert.strictEqual(fractional.get(2), child);

  for (const platform of ["linux", "darwin"] as const) {
    const tree = new Map<number, ObservedProcessReading>();
    const parent = reading(1, 0, "Fri Oct  9 01:15:59 2026");
    updateObservedProcessTree(tree, 1, [
      reading(4, 3, "Sat Oct 10 00:00:00 2026"),
      reading(2, 1, "Fri Oct 9 01:15:59 2026"),
      reading(3, 1, "Sat Oct 10 00:00:00 2026"),
      reading(5, 1, "Thu Oct  8 23:59:59 2026"),
      parent,
    ], platform);
    assert.deepEqual(keys(tree), [1, 2, 3, 4], platform);
    assert.strictEqual(tree.get(1), parent);

    const calendar = new Map<number, ObservedProcessReading>();
    updateObservedProcessTree(calendar, 1, [
      reading(1, 0, "Wed Dec 31 23:59:59 2025"),
      reading(2, 1, "Thu Jan  1 00:00:00 2026"),
      reading(3, 2, "Sun Feb  1 00:00:00 2026"),
    ], platform);
    assert.deepEqual(keys(calendar), [1, 2, 3], platform);
    for (const identity of [
      "Fri Oct  9 01:15:59 2026 UTC",
      "Thu Oct  9 01:15:59 2026",
      "Mon Feb 30 00:00:00 2026",
      "unknown",
    ]) assert.throws(() => updateObservedProcessTree(
      new Map(), 1, [parent, reading(2, 1, identity)], platform,
    ), /Unknown .* process creation identity/);
  }

  const leap = new Map<number, ObservedProcessReading>();
  updateObservedProcessTree(leap, 1, [
    reading(1, 0, "2024-02-29T23:59:59.9999990Z"),
    reading(2, 1, "2024-03-01T00:00:00.0000000Z"),
  ], "win32");
  assert.deepEqual(keys(leap), [1, 2]);
  for (const identity of [
    "", "not-a-date", "2026-02-29T00:00:00.0000000Z",
    "2026-10-09T24:00:00.0000000Z", "2026-10-09T00:60:00.0000000Z",
    "2026-10-09T00:00:60.0000000Z", "2026-10-09T00:00:00.000000Z",
    "2026-10-09T00:00:00.0000000+00:00", "0000-01-01T00:00:00.0000000Z",
  ]) assert.throws(() => updateObservedProcessTree(
    new Map(), 1, [root, reading(2, 1, identity)], "win32",
  ), /Unknown win32 process creation identity/);
  assert.throws(() => updateObservedProcessTree(
    new Map(), 1, [reading(1, 0, "unknown")], "win32",
  ), /Unknown win32 process creation identity/);
  assert.throws(() => updateObservedProcessTree(
    new Map(), 1, [root], "freebsd",
  ), /Unknown freebsd process creation identity/);
  for (const pid of [0, -1, 1.5, Number.MAX_SAFE_INTEGER + 1])
    assert.throws(() => updateObservedProcessTree(
      new Map(), 1, [root, reading(pid, 1, win("0000030"))], "win32",
    ), /Unknown win32 process creation identity/);

  const unrelated = new Map<number, ObservedProcessReading>();
  updateObservedProcessTree(unrelated, 1, [
    root, reading(99, 98, "unknown"), reading(7, 6, win("0000040")),
  ], "win32");
  assert.deepEqual(keys(unrelated), [1]);
  assert.throws(() => updateObservedProcessTree(
    new Map(), 1, [root, { ...root }], "win32",
  ), /Ambiguous observed process generation for PID 1/);
  assert.throws(() => updateObservedProcessTree(
    new Map(), 1, [root, child, { ...child, identity: win("0000040") }], "win32",
  ), /Ambiguous observed process generation for PID 2/);

  const generations = new Map<number, ObservedProcessReading>();
  updateObservedProcessTree(generations, 1, [root, child], "win32");
  const replacement = reading(1, 0, win("0000050"));
  const foreignChild = reading(6, 1, win("0000060"));
  const orphanChild = reading(7, 2, win("0000070"));
  updateObservedProcessTree(
    generations, 1, [replacement, foreignChild, child, orphanChild], "win32",
  );
  assert.deepEqual(keys(generations), [1, 2, 7]);
  assert.strictEqual(generations.get(1), root);
  assert.strictEqual(generations.get(2), child);
  assert.throws(() => updateObservedProcessTree(
    generations, 1, [reading(2, 0, "unknown")], "win32",
  ), /Unknown win32 process creation identity/);
  assert.throws(() => updateObservedProcessTree(
    generations, 1, [child, { ...child, identity: win("0000080") }], "win32",
  ), /Ambiguous observed process generation for PID 2/);
  updateObservedProcessTree(generations, 1, [orphanChild], "win32");
  assert.deepEqual(keys(generations), [1, 2, 7]);
  updateObservedProcessTree(generations, 1, [], "win32");
  assert.strictEqual(generations.get(1), root);

  const reusedParent = new Map<number, ObservedProcessReading>();
  updateObservedProcessTree(reusedParent, 1, [root, child], "win32");
  const newParent = reading(2, 1, win("0000050"));
  const newChild = reading(8, 2, win("0000060"));
  updateObservedProcessTree(reusedParent, 1, [newChild, newParent], "win32");
  assert.deepEqual(keys(reusedParent), [1, 2]);
  assert.strictEqual(reusedParent.get(2), child);
  updateObservedProcessTree(reusedParent, 1, [newChild, newParent, root], "win32");
  assert.deepEqual(keys(reusedParent), [1, 2, 8]);
  assert.strictEqual(reusedParent.get(2), newParent);
  assert.strictEqual(reusedParent.get(8), newChild);
}
